{
  "hash": "90436964bc5fff6c7a9f7ee71a869147",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"HDB resale price Explanatory Modeling\"\nauthor: \"BingBing\"\ndate: \"2025-11-12\"\nformat: html\nexecute:\n  warning: false\n  message: false\n  freeze: true\n---\n\n\n\n## **1** Objective\n\nThis study identifies and evaluates factors influencing HDB resale prices across Singapore during January-September 2025, with focus on understanding spatial variations in pricing mechanisms. Using Geographically Weighted Regression (GWR) on 8,679 four-room flat transactions, the analysis examines whether factors like floor area, building age, proximity to schools, MRT stations, and other amenities impact prices differently across neighborhoods, and whether spatial modeling techniques provide better explanatory power than traditional global regression.\n\n### 1.2 Executive Summary\n\nAnalysis of 8,679 HDB resale transactions reveals significant spatial heterogeneity in pricing mechanisms across Singapore. While global regression (R² = 0.745) identifies kindergartens, building age, and floor area as key price drivers, Geographically Weighted Regression (R² = 0.951) demonstrates that factor importance varies fundamentally by location. Northern family-oriented estates prioritize childcare facilities, eastern regions value educational abundance, while central/western markets emphasize elite school access and MRT proximity. These findings suggest that HDB buyers in different neighborhoods optimize for different attributes, with direct implications for property development strategies, urban planning priorities, and investment decisions. Detailed spatial analysis reveals where specific amenities command premiums and where they add minimal value.\n\n## **2 The Data**\n\nTwo data sets will be used in this model building exercise, they are:\n\n-   **Aspatial dataset**:\n\n    -   HDB Resale data: a list of HDB resale transacted prices in Singapore from Jan 2017 onwards. It is in csv format which can be downloaded from Data.gov.sg.\n\n-   **Geospatial dataset**:\n\n    -   *MP14_SUBZONE_WEB_PL*: a polygon feature data providing information of URA 2014 Master Plan Planning Subzone boundary data. It is in ESRI shapefile format. This data set was also downloaded from Data.gov.sg\n\n-   **Locational factors with geographic coordinates**:\n\n    -   Downloaded from **Data.gov.sg**.\n\n        -   **Eldercare** data is a list of eldercare in Singapore. It is in shapefile format.\n\n        -   **Hawker Centre** data is a list of hawker centres in Singapore. It is in geojson format.\n\n        -   **Parks** data is a list of parks in Singapore. It is in geojson format.\n\n        -   **Supermarket** data is a list of supermarkets in Singapore. It is in geojson format.\n\n        -   **CHAS clinics** data is a list of CHAS clinics in Singapore. It is in geojson format.\n\n        -   **Childcare service** data is a list of childcare services in Singapore. It is in geojson format.\n\n        -   **Kindergartens** data is a list of kindergartens in Singapore. It is in geojson format.\n\n    -   Downloaded from **Datamall.lta.gov.sg**.\n\n        -   **MRT** data is a list of MRT/LRT stations in Singapore with the station names and codes. It is in shapefile format.\n\n        -   **Bus stops** data is a list of bus stops in Singapore. It is in shapefile format.\n\n-   **Locational factors without geographic coordinates**:\n\n    -   Downloaded from **Data.gov.sg**.\n\n        -   **Primary school** data is extracted from the list on General information of schools from data.gov portal. It is in csv format.\n\n    -   Retrieved/Scraped from **other sources**\n\n        -   **CBD** coordinates obtained from Google.\n\n        -   **Shopping malls** data is a list of Shopping malls in Singapore obtained from [Wikipedia](https://en.wikipedia.org/wiki/List_of_shopping_malls_in_Singapore).\n\n        -   **Good primary schools** is a list of primary schools that are ordered in ranking in terms of popularity and this can be found at [Local Salary Forum](https://www.salary.sg/2021/best-primary-schools-2021-by-popularity).\n\n## **3 Installing and Loading R packages**\n\nCheck if R packages on package have been installed in R and if not, should installed first.\n\n### 3.1 The Packages\n\nIn this exercise, we will use following packages:\n\n| Package | Description |\n|------------------------------|------------------------------------------|\n| **sf** | Provides functions to manage, process, and manipulate Simple Features, a formal geospatial data standard for spatial geometries such as points, lines, and polygons. |\n| **sfdep** | Provides functions for spatial autocorrelation analysis and spatial weights matrix computation. |\n| **GWmodel** | Implements Geographically Weighted Regression and related spatial modeling techniques for capturing local variations. |\n| **tmap** | Provides functions for plotting cartographic quality thematic maps with support for both static and interactive visualization. |\n| **tidyverse** | A collection of R packages for data manipulation, transformation, and visualization including dplyr, ggplot2, and tidyr. |\n| **gtsummary** | Creates publication-ready analytical and summary tables for regression models. |\n| **performance** | Provides tools for assessing regression model quality, diagnostics, and assumption validation. |\n| **corrplot** | Visualizes correlation matrices to examine relationships between variables. |\n| **RColorBrewer** | Provides color palettes for data visualization and thematic mapping. |\n| **httr** | Makes HTTP requests to web APIs for data retrieval and geocoding. |\n| **jsonlite** | Parses JSON-formatted data from API responses. |\n| **progress** | Displays progress bars for monitoring long-running operations. |\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(olsrr, corrplot, ggpubr, \n               sf, sfdep, GWmodel, tmap, \n               tidyverse, gtsummary,\n               performance, RColorBrewer,\n               httr,jsonlite,progress,tidyverse)\n```\n:::\n\n\n\n## **4 Geospatial Data Wrangling**\n\n### **4.1 Importing geospatial data**\n\nThe geospatial data used in this hands-on exercise is called MP14_SUBZONE_WEB_PL. It is in ESRI shapefile format. The shapefile consists of URA Master Plan 2014’s planning subzone boundaries. Polygon features are used to represent these geographic boundaries. The GIS data is in svy21 projected coordinates systems.\n\nThe code chunk below is used to import *MP_SUBZONE_WEB_PL* shapefile by using `st_read()` of **sf** packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = st_read(dsn = \"data/geospatial\", \n               layer = \"MP14_SUBZONE_WEB_PL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n### **4.2 Updating CRS information**\n\nThe code chunk below updates the newly imported *mpsz* with the correct ESPG code (i.e. 3414)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_svy21 <- st_transform(mpsz, 3414)\n```\n:::\n\n\n\nAfter transforming the projection metadata, you can varify the projection of the newly transformed *mpsz_svy21* by using `st_crs()` of **sf** package.\n\nThe code chunk below will be used to verify the newly transformed *mpsz_svy21*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\n\nNotice that the EPSG: is indicated as *3414* now.\n\nNext, we will reveal the extent of *mpsz_svy21* by using `st_bbox()` of sf package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_bbox(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     xmin      ymin      xmax      ymax \n 2667.538 15748.721 56396.440 50256.334 \n```\n\n\n:::\n:::\n\n\n\nThe print above reports the extent of mpsz_svy21 layer by its lower and upper limits.\n\n## **5 Aspatial Data Wrangling**\n\n### **5.2 Geocoding HDB resale data**\n\nFirst on all, we download *Resale flat prices based on registration date from Jan-2017 onwards* from [Singapore’s open data portal](https://isss626-ay2025-26aug.netlify.app/in-class_ex/in-class_ex08/data.gov.sg).\n\n### **Selecting data of interest**\n\nThis data set comprises of HDB resale transactions from Jan 2017 onwards. For the purpose of this in-class exercise, the code chunk below will be used to extract a sub-set of transaction records on 4-Room flat transacted from Janaury 2025 to September 2025.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- read_csv(\n  \"data/aspatial/HDBResalefromJan2017onwards.csv\") %>%\n  filter(flat_type == \"4 ROOM\") %>%\n  filter(month >= \"2025-01\" & month <= \"2025-09\")\n```\n:::\n\n\n\nCheck is it have missing value:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(is.na(HDBresale))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              month                town           flat_type               block \n                  0                   0                   0                   0 \n        street_name        storey_range      floor_area_sqm          flat_model \n                  0                   0                   0                   0 \nlease_commence_date     remaining_lease        resale_price \n                  0                   0                   0 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDBresale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,679\nColumns: 11\n$ month               <chr> \"2025-01\", \"2025-01\", \"2025-01\", \"2025-02\", \"2025-…\n$ town                <chr> \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO …\n$ flat_type           <chr> \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", …\n$ block               <chr> \"337\", \"310C\", \"337\", \"226\", \"310C\", \"226\", \"304\",…\n$ street_name         <chr> \"ANG MO KIO AVE 1\", \"ANG MO KIO AVE 1\", \"ANG MO KI…\n$ storey_range        <chr> \"13 TO 15\", \"10 TO 12\", \"10 TO 12\", \"07 TO 09\", \"2…\n$ floor_area_sqm      <dbl> 91, 94, 91, 91, 96, 92, 98, 97, 94, 87, 97, 82, 92…\n$ flat_model          <chr> \"New Generation\", \"Model A\", \"New Generation\", \"Ne…\n$ lease_commence_date <dbl> 1982, 2012, 1982, 1978, 2012, 1978, 1977, 1977, 20…\n$ remaining_lease     <chr> \"56 years 03 months\", \"86 years 09 months\", \"56 ye…\n$ resale_price        <dbl> 582000, 865000, 530000, 560000, 1038000, 542000, 6…\n```\n\n\n:::\n:::\n\n\n\nLet us prepare a geocoding function by using the code chunk below. It aims to perform the following tasks:\n\n-   Combining the block and street name into an address. The addresses will be used to geocode instead of postal code that you learned in In-class Exercise 3b,\n\n-   Passing the address as the **searchVal** in our query,\n\n-   Sending the query to **OneMapSG search**. Note: Since we don’t need all the address details, we can set getAddrDetails as ‘N’,\n\n-   Converting response (JSON object) to text,\n\n-   Saving response in text form as a dataframe, and\n\n-   Retain the latitude and longitude for our output.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeocode <- function(block, streetname) {\n  base_url <- \"https://onemap.gov.sg/api/common/elastic/search\"\n  address <- paste(block, streetname, sep = \" \")\n  query <- list(\"searchVal\" = address, \n                \"returnGeom\" = \"Y\",\n                \"getAddrDetails\" = \"N\",\n                \"pageNum\" = \"1\")\n  \n  res <- GET(base_url, query = query)\n  restext <- content(res, as = \"text\")\n  \n  output <- fromJSON(restext)\n  if (output$found == 0 || length(output$results) == 0) {\n    return(data.frame(results.LATITUDE = NA, results.LONGITUDE = NA))}\n  output <- output %>% \n    as.data.frame %>%\n    select(results.LATITUDE, results.LONGITUDE)\n  \n  return(output)}\n```\n:::\n\n\n\nNext, the code chunk below will be used to to execute the geocoding function（if don't wanna run again or save time just save it and add in begin: #\\| eval: false）:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$LATITUDE <- 0\nHDBresale$LONGITUDE <- 0\n\nfor (i in 1:nrow(HDBresale)){\n  temp_output <- geocode(HDBresale[i, 4], HDBresale[i, 5])\n  \n  HDBresale$LATITUDE[i] <- temp_output$results.LATITUDE\n  HDBresale$LONGITUDE[i] <- temp_output$results.LONGITUDE\n}\n```\n:::\n\n\n\nIgnore the warning message as shown below.\n\n![](images/clipboard-490401431.png){fig-align=\"center\" width=\"553\"}\n\nFor save time we save the output to rds file(remember create a new file in data file for save rds file:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveRDS(HDBresale, \"data/rds/HDBresale_geocoded.rds\")\n```\n:::\n\n\n\nread rds file:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- readRDS(\"data/rds/HDBresale_geocoded.rds\")\n```\n:::\n\n\n\nCheck is it really already add the end of HDBresale. After importing the data file into R, it is important for us to examine if the data file has been imported correctly.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDBresale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,679\nColumns: 13\n$ month               <chr> \"2025-01\", \"2025-01\", \"2025-01\", \"2025-02\", \"2025-…\n$ town                <chr> \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO KIO\", \"ANG MO …\n$ flat_type           <chr> \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", \"4 ROOM\", …\n$ block               <chr> \"337\", \"310C\", \"337\", \"226\", \"310C\", \"226\", \"304\",…\n$ street_name         <chr> \"ANG MO KIO AVE 1\", \"ANG MO KIO AVE 1\", \"ANG MO KI…\n$ storey_range        <chr> \"13 TO 15\", \"10 TO 12\", \"10 TO 12\", \"07 TO 09\", \"2…\n$ floor_area_sqm      <dbl> 91, 94, 91, 91, 96, 92, 98, 97, 94, 87, 97, 82, 92…\n$ flat_model          <chr> \"New Generation\", \"Model A\", \"New Generation\", \"Ne…\n$ lease_commence_date <dbl> 1982, 2012, 1982, 1978, 2012, 1978, 1977, 1977, 20…\n$ remaining_lease     <chr> \"56 years 03 months\", \"86 years 09 months\", \"56 ye…\n$ resale_price        <dbl> 582000, 865000, 530000, 560000, 1038000, 542000, 6…\n$ LATITUDE            <dbl> 1.363196, 1.364612, 1.363196, 1.367728, 1.364612, …\n$ LONGITUDE           <dbl> 103.8516, 103.8449, 103.8516, 103.8384, 103.8449, …\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(HDBresale$LONGITUDE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 103.8516 103.8449 103.8516 103.8384 103.8449 103.8384\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(HDBresale$LATITUDE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.363196 1.364612 1.363196 1.367728 1.364612 1.367728\n```\n\n\n:::\n:::\n\n\n\ncheck the type of LATITUDE and LONGITUDE.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(HDBresale$LATITUDE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n\n```{.r .cell-code}\nclass(HDBresale$LONGITUDE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n:::\n\n\n\nType should be numeric type, if not should change the type use the below code:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- HDBresale %>%\n  mutate(\n    LATITUDE = as.numeric(LATITUDE),\n    LONGITUDE = as.numeric(LONGITUDE))\n\ncat(\"LATITUDE TYPE:\", class(HDBresale$LATITUDE), \"\\n\")\ncat(\"LONGITUDE TYPE:\", class(HDBresale$LONGITUDE), \"\\n\")\ncat(\"Record:\", nrow(HDBresale), \"\\n\\n\")\n\nsaveRDS(HDBresale, \"data/rds/HDBresale_geocoded.rds\")\n```\n:::\n\n\n\nNext, `summary()` of base R is used to display the summary statistics of *HDBresale* tibble data frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(HDBresale)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    month               town            flat_type            block          \n Length:8679        Length:8679        Length:8679        Length:8679       \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n street_name        storey_range       floor_area_sqm    flat_model       \n Length:8679        Length:8679        Min.   : 74.00   Length:8679       \n Class :character   Class :character   1st Qu.: 92.00   Class :character  \n Mode  :character   Mode  :character   Median : 93.00   Mode  :character  \n                                       Mean   : 94.89                     \n                                       3rd Qu.:100.00                     \n                                       Max.   :135.00                     \n lease_commence_date remaining_lease     resale_price        LATITUDE    \n Min.   :1967        Length:8679        Min.   : 300000   Min.   :1.272  \n 1st Qu.:1988        Class :character   1st Qu.: 562000   1st Qu.:1.342  \n Median :2002        Mode  :character   Median : 630000   Median :1.372  \n Mean   :2002                           Mean   : 672451   Mean   :1.373  \n 3rd Qu.:2016                           3rd Qu.: 728000   3rd Qu.:1.402  \n Max.   :2021                           Max.   :1518000   Max.   :1.457  \n   LONGITUDE    \n Min.   :103.7  \n 1st Qu.:103.8  \n Median :103.8  \n Mean   :103.8  \n 3rd Qu.:103.9  \n Max.   :104.0  \n```\n\n\n:::\n:::\n\n\n\n### **5.3 Converting aspatial data frame into a sf object**\n\nCurrently, the *HDBresale* tibble data frame is aspatial. We will convert it to a **sf** object. The code chunk below converts *HDBresale* data frame into a simple feature data frame by using `st_as_sf()` of **sf** packages.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale.sf <- st_as_sf(HDBresale,\n                            coords = c(\"LONGITUDE\", \"LATITUDE\"),\n                            crs=4326) %>%\n  st_transform(crs=3414)\n```\n:::\n\n\n\nNext, `head()` is used to list the content of *HDBresale.sf* object. Notice that the output is in point feature data frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(HDBresale.sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 28566.05 ymin: 38360.76 xmax: 30036.29 ymax: 38861.93\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 6 × 12\n  month town  flat_type block street_name storey_range floor_area_sqm flat_model\n  <chr> <chr> <chr>     <chr> <chr>       <chr>                 <dbl> <chr>     \n1 2025… ANG … 4 ROOM    337   ANG MO KIO… 13 TO 15                 91 New Gener…\n2 2025… ANG … 4 ROOM    310C  ANG MO KIO… 10 TO 12                 94 Model A   \n3 2025… ANG … 4 ROOM    337   ANG MO KIO… 10 TO 12                 91 New Gener…\n4 2025… ANG … 4 ROOM    226   ANG MO KIO… 07 TO 09                 91 New Gener…\n5 2025… ANG … 4 ROOM    310C  ANG MO KIO… 28 TO 30                 96 Model A   \n6 2025… ANG … 4 ROOM    226   ANG MO KIO… 04 TO 06                 92 New Gener…\n# ℹ 4 more variables: lease_commence_date <dbl>, remaining_lease <chr>,\n#   resale_price <dbl>, geometry <POINT [m]>\n```\n\n\n:::\n:::\n\n\n\n## 6. **Locational factors with geographic coordinates**\n\n### 6.1 import & merge\n\n-   Downloaded from **Data.gov.sg**.\n\n    -   **Eldercare** data is a list of eldercare in Singapore. It is in shapefile format.\n\n    -   **Hawker Centre** data is a list of hawker centres in Singapore. It is in geojson format.\n\n    -   **Parks** data is a list of parks in Singapore. It is in geojson format.\n\n    -   **Supermarket** data is a list of supermarkets in Singapore. It is in geojson format.\n\n    -   **CHAS clinics** data is a list of CHAS clinics in Singapore. It is in geojson format.\n\n    -   **Childcare service** data is a list of childcare services in Singapore. It is in geojson format.\n\n    -   **Kindergartens** data is a list of kindergartens in Singapore. It is in geojson format.\n\n-   Downloaded from **Datamall.lta.gov.sg**.\n\n    -   **MRT** data is a list of MRT/LRT stations in Singapore with the station names and codes. It is in shapefile format.\n\n    -   **Bus stops** data is a list of bus stops in Singapore. It is in shapefile format.mrt \\<- st_read(file.path(base_path, \"TrainStation_Aug2025/RapidTransitSystemStation.shp\")) %\\>% st_transform(3414)\n\ngo to check each file:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkindergarten <- st_read(\"data/Locational_factors_with_geographic_coordinates/Kindergartens.geojson\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `KINDERGARTENS' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/Kindergartens.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 448 features and 16 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6887 ymin: 1.247759 xmax: 103.9717 ymax: 1.455452\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nchildcare <- st_read(\"data/Locational_factors_with_geographic_coordinates/ChildCareServices.geojson\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CHILDCARE' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/ChildCareServices.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1925 features and 16 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nCHASClinics <- st_read(\"data/Locational_factors_with_geographic_coordinates/CHASClinics.geojson\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `CHASClinics' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/CHASClinics.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 1193 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.5818 ymin: 1.016264 xmax: 103.9903 ymax: 1.456037\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nsupermarket <- st_read(\"data/Locational_factors_with_geographic_coordinates/SupermarketsGEOJSON.geojson\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SupermarketsGEOJSON' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/SupermarketsGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 526 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6258 ymin: 1.24715 xmax: 104.0036 ymax: 1.461526\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nparks <- st_read(\"data/Locational_factors_with_geographic_coordinates/Parks.geojson\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `NATIONALPARKS' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/Parks.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 450 features and 6 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6929 ymin: 1.263958 xmax: 104.0538 ymax: 1.461944\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nhawker <- st_read(\"data/Locational_factors_with_geographic_coordinates/HawkerCentresGEOJSON.geojson\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SSOT_HAWKERCENTRES' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/HawkerCentresGEOJSON.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 129 features and 20 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 103.6972 ymin: 1.272761 xmax: 103.9882 ymax: 1.448263\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\neldercare <- st_read(\"data/Locational_factors_with_geographic_coordinates/EldercareServicesSHP/ELDERCARE.shp\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ELDERCARE' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/EldercareServicesSHP/ELDERCARE.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 133 features and 18 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 14481.92 ymin: 28218.43 xmax: 41665.14 ymax: 46804.9\nProjected CRS: SVY21\n```\n\n\n:::\n\n```{.r .cell-code}\nbusstop <- st_read(\"data/Locational_factors_with_geographic_coordinates/BusStopLocation_Aug2025/BusStop.shp\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BusStop' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/BusStopLocation_Aug2025/BusStop.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5172 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48285.52 ymax: 52983.82\nProjected CRS: SVY21\n```\n\n\n:::\n\n```{.r .cell-code}\nmrt <- st_read(\"data/Locational_factors_with_geographic_coordinates/MRT_Aug2025/RapidTransitSystemStation.shp\") %>% st_transform(3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `RapidTransitSystemStation' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise03/data/Locational_factors_with_geographic_coordinates/MRT_Aug2025/RapidTransitSystemStation.shp' \n  using driver `ESRI Shapefile'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 231 features and 7 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 6068.209 ymin: 27478.44 xmax: 45377.5 ymax: 47913.58\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n## **7.Locational factors without geographic coordinates**\n\n-   **Locational factors without geographic coordinates**:\n\n    -   Downloaded from **Data.gov.sg**.\n\n        -   **Primary school** data is extracted from the list on General information of schools from data.gov portal. It is in csv format.\n\n    -   Retrieved/Scraped from **other sources**\n\n        -   **CBD** coordinates obtained from Google.\n\n        -   **Shopping malls** data is a list of Shopping malls in Singapore obtained from [Wikipedia](https://en.wikipedia.org/wiki/List_of_shopping_malls_in_Singapore).\n\n        -   **Good primary schools** is a list of primary schools that are ordered in ranking in terms of popularity and this can be found at [Local Salary Forum](https://www.salary.sg/2021/best-primary-schools-2021-by-popularity).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Primary schools from data.gov portal.\nprimary_schools <- read_csv(\"data/Locational_factors_without_geographic_coordinates/Generalinformationofschools.csv\")\n\n# Shopping malls obtained from Wikipedia.\nshopping_malls_list <- c(\n  \"Bugis Junction\", \"Bugis+\", \"Capitol Piazza\", \"Cathay Cineleisure Orchard\",\n  \"The Centrepoint\", \"City Square Mall\", \"CityLink Mall\", \"Chinatown Point\",\n  \"Duo\", \"Far East Plaza\", \"Funan\", \"Great World City\", \"HDB Hub\",\n  \"Holland Village Shopping Mall\", \"ION Orchard\", \"Junction 8\", \"Liat Towers\",\n  \"Lucky Plaza\", \"Marina Bay Sands\", \"Marina Bay Link Mall\", \"Marina Square\",\n  \"Millenia Walk\", \"Mustafa Centre\", \"Ngee Ann City\", \"Orchard Central\",\n  \"Orchard Gateway\", \"Palais Renaissance\", \"The Paragon\", \"People's Park Centre\",\n  \"People's Park Complex\", \"Plaza Singapura\", \"Raffles City\", \"Shaw House and Centre\",\n  \"Sim Lim Square\", \"The South Beach\", \"Square 2\", \"Suntec City\",\n  \"Tanjong Pagar Centre\", \"Tekka Centre\", \"Tiong Bahru Plaza\", \"Thomson Plaza\",\n  \"Novena Square Shopping Mall\", \"Wheelock Place\", \"Wisma Atria\",\n  \"Bedok Mall\", \"Century Square\", \"Changi City Point\", \"Downtown East\",\n  \"Eastpoint Mall\", \"Jewel Changi Airport\", \"Katong Shopping Centre\",\n  \"Kallang Wave Mall\", \"Leisure Park Kallang\", \"i12 Katong\", \"Our Tampines Hub\",\n  \"Parkway Parade\", \"Paya Lebar Quarter\", \"Paya Lebar Square\", \"Singpost Center\",\n  \"Tampines 1\", \"Tampines Mall\", \"White Sands\",\n  \"AMK Hub\", \"Canberra Plaza\", \"Causeway Point\", \"Northpoint City\",\n  \"Sembawang Shopping Centre\", \"Sun Plaza\",\n  \"Compass One\", \"Heartland Mall\", \"Hougang Mall\", \"NEX\", \"Oasis Terraces\",\n  \"Punggol Plaza\", \"Punggol Coast Mall\", \"The Seletar Mall\", \"Waterway Point\",\n  \"Woodland Mall\", \"Junction 10\", \"West Mall\", \"Hillion Mall\", \"Lot 1\", \n  \"Bukit Panjang Plaza\", \"Yee Tee Point\", \"VivoCity\", \"HarbourFront Centre\", \n  \"Alexandra Retail Centre\", \"The Clementi Mall\", \"Gek Poh Shopping Centre\", \n  \"IMM\", \"Jem\", \"Jurong Point\", \"Pioneer Mall\", \"Queensway Shopping Centre\", \n  \"The Rail Mall\", \"The Star Vista\", \"West Coast Plaza\", \"Westgate\")\n\nshopping_malls <- data.frame(\n  MALL_NAME = shopping_malls_list,\n  LATITUDE = NA_real_,\n  LONGITUDE = NA_real_)\n\n# Good primary schools found at Local Salary Forum.\ngood_primary_schools_list <- c(\n  \"Holy Innocents' Primary School\",\n  \"Ai Tong School\",\n  \"Nan Chiau Primary School\",\n  \"Chongfu School\",\n  \"Nanyang Primary School\",\n  \"CHIJ Primary (Toa Payoh)\",\n  \"Methodist Girls' School (Primary)\",\n  \"Tao Nan School\",\n  \"Kong Hwa School\",\n  \"Nan Hua Primary School\",\n  \"Catholic High School (Primary Section)\",\n  \"Rulang Primary School\",\n  \"CHIJ St. Nicholas Girls' School (Primary Section)\",\n  \"Singapore Chinese Girls' Primary School\",\n  \"St. Hilda's Primary School\",\n  \"Anglo-Chinese School (Junior)\",\n  \"St. Joseph's Institution Junior\",\n  \"Fairfield Methodist School (Primary)\",\n  \"Rosyth School\",\n  \"Kuo Chuan Presbyterian Primary School\",\n  \"Maris Stella High School (Primary Section)\",\n  \"Henry Park Primary School\",\n  \"Anglo-Chinese School (Primary)\",\n  \"Red Swastika School\",\n  \"Pei Chun Public School\",\n  \"Princess Elizabeth Primary School\",\n  \"Pei Hwa Presbyterian Primary School\",\n  \"St. Anthony's Primary School\",\n  \"Pasir Ris Primary School\",\n  \"South View Primary School\")\n\ngood_primary_schools <- data.frame(\n  SCHOOL_NAME = good_primary_schools_list,\n  LATITUDE = NA_real_,\n  LONGITUDE = NA_real_)\n```\n:::\n\n\n\nUse the function to find the **geographic coordinates and** save to rds file:**：**\n\n-   **CBD**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#CBD coordinates obtained from Google.\ncbd <- data.frame(\n  name = \"CBD\",\n  LATITUDE = 1.2802,\n  LONGITUDE = 103.8563)\n```\n:::\n\n\n\n-   **Primary schools geocoding**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Primary schools geocoding\nprimary_schools$LATITUDE <- 0\nprimary_schools$LONGITUDE <- 0\nfor (i in 1:nrow(primary_schools)){\n  temp_output <- geocode(primary_schools$school_name[i], \"\")\n  \n  primary_schools$LATITUDE[i] <- temp_output$results.LATITUDE\n  primary_schools$LONGITUDE[i] <- temp_output$results.LONGITUDE}\n\nwrite_rds(primary_schools, \"data/rds/primary_schools_geocoded.rds\")\n```\n:::\n\n\n\nCheck is it have missing value:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_schools %>% filter(LATITUDE == 0) %>% select(school_name)\n```\n:::\n\n\n\nnext time we can just use the code below read the rds file：\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_schools <- read_rds(\"data/rds/primary_schools_geocoded.rds\")\nprimary_schools <- primary_schools %>% mutate(across(c(LATITUDE, LONGITUDE), as.numeric))\nsummary(primary_schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n school_name        url_address          address           postal_code    \n Length:337         Length:337         Length:337         Min.   : 88256  \n Class :character   Class :character   Class :character   1st Qu.:449149  \n Mode  :character   Mode  :character   Mode  :character   Median :548595  \n                                                          Mean   :539754  \n                                                          3rd Qu.:679944  \n                                                          Max.   :828870  \n                                                                          \n telephone_no       telephone_no_2        fax_no            fax_no_2        \n Length:337         Length:337         Length:337         Length:337        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n email_address        mrt_desc           bus_desc         principal_name    \n Length:337         Length:337         Length:337         Length:337        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n first_vp_name      second_vp_name     third_vp_name      fourth_vp_name    \n Length:337         Length:337         Length:337         Length:337        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n fifth_vp_name      sixth_vp_name        dgp_code          zone_code        \n Length:337         Length:337         Length:337         Length:337        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n  type_code         nature_code        session_code       mainlevel_code    \n Length:337         Length:337         Length:337         Length:337        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n   sap_ind          autonomous_ind      gifted_ind           ip_ind         \n Length:337         Length:337         Length:337         Length:337        \n Class :character   Class :character   Class :character   Class :character  \n Mode  :character   Mode  :character   Mode  :character   Mode  :character  \n                                                                            \n                                                                            \n                                                                            \n                                                                            \n mothertongue1_code mothertongue2_code mothertongue3_code    LATITUDE    \n Length:337         Length:337         Length:337         Min.   :1.275  \n Class :character   Class :character   Class :character   1st Qu.:1.331  \n Mode  :character   Mode  :character   Mode  :character   Median :1.354  \n                                                          Mean   :1.361  \n                                                          3rd Qu.:1.388  \n                                                          Max.   :1.457  \n                                                          NA's   :1      \n   LONGITUDE    \n Min.   :103.7  \n 1st Qu.:103.8  \n Median :103.8  \n Mean   :103.8  \n 3rd Qu.:103.9  \n Max.   :104.0  \n NA's   :1      \n```\n\n\n:::\n:::\n\n\n\n-   **Shopping malls geocoding**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshopping_malls$LATITUDE <- 0\nshopping_malls$LONGITUDE <- 0\n\nfor (i in 1:nrow(shopping_malls)){\n  search_term <- paste(shopping_malls$MALL_NAME[i], \"Singapore\")\n  temp_output <- geocode(search_term, \"\")\n  \n  shopping_malls$LATITUDE[i] <- temp_output$results.LATITUDE\n  shopping_malls$LONGITUDE[i] <- temp_output$results.LONGITUDE}\n```\n:::\n\n\n\nList those can not find the LATITUDE and LONGTITUDE:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshopping_malls %>% \n  filter(is.na(LATITUDE)) %>% \n  select(MALL_NAME)\n```\n:::\n\n\n\nFill out the missing data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmissing_malls_coords <- tribble(\n  ~MALL_NAME, ~LATITUDE, ~LONGITUDE,\n  \"Holland Village Shopping Mall\", 1.3119, 103.7959,\n  \"Shaw House and Centre\", 1.3039, 103.8323,\n  \"Tekka Centre\", 1.3063, 103.8509,\n  \"Novena Square Shopping Mall\", 1.3204, 103.8436,\n  \"i12 Katong\", 1.3151, 103.9062,\n  \"Heartland Mall\", 1.3750, 103.8857,\n  \"Woodland Mall\", 1.4368, 103.7860,\n  \"Lot 1\", 1.3847, 103.7476,\n  \"Yee Tee Point\", 1.3972, 103.7478)\n\nshopping_malls <- shopping_malls %>%\n  left_join(missing_malls_coords, by = \"MALL_NAME\", suffix = c(\"\", \"_manual\")) %>%\n  mutate(\n    LATITUDE = ifelse(is.na(LATITUDE), LATITUDE_manual, LATITUDE),\n    LONGITUDE = ifelse(is.na(LONGITUDE), LONGITUDE_manual, LONGITUDE)\n  ) %>%\n  select(MALL_NAME, LATITUDE, LONGITUDE)\n\n\nshopping_malls %>% filter(is.na(LATITUDE))\nwrite_rds(shopping_malls, \"data/rds/shopping_malls_geocoded.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nshopping_malls <- read_rds(\"data/rds/shopping_malls_geocoded.rds\")\n```\n:::\n\n\n\n-   Good primary schools geocoding\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngood_primary_schools$LATITUDE <- 0\ngood_primary_schools$LATITUDE <- 0\ngood_primary_schools$LONGITUDE <- 0\nfor (i in 1:nrow(good_primary_schools)){\n  temp_output <- geocode(good_primary_schools$SCHOOL_NAME[i], \"\")\n  \n  good_primary_schools$LATITUDE[i] <- temp_output$results.LATITUDE\n  good_primary_schools$LONGITUDE[i] <- temp_output$results.LONGITUDE}\n```\n:::\n\n\n\nCheck missing value:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngood_primary_schools %>% filter(is.na(LATITUDE))\n```\n:::\n\n\n\nTry to find it on the primary school list:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprimary_schools %>% \n  filter(grepl(\"Catholic High|CHIJ St. Nicholas|Maris Stella\", \n               school_name, \n               ignore.case = TRUE)) %>%\n  select(school_name)\n```\n:::\n\n\n\n![](images/clipboard-2428886139.png){fig-align=\"center\" width=\"480\"}\n\nNow we find out the issue: on the primary school list no fullname,is abbreviation,but primary school have no mssing value, so we find those school from primary school list:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidx_catholic <- which(good_primary_schools$SCHOOL_NAME == \"Catholic High School (Primary Section)\")\nidx_chij <- which(good_primary_schools$SCHOOL_NAME == \"CHIJ St. Nicholas Girls' School (Primary Section)\")\nidx_maris <- which(good_primary_schools$SCHOOL_NAME == \"Maris Stella High School (Primary Section)\")\n\ngood_primary_schools$LATITUDE[idx_catholic] <- as.numeric(\n  primary_schools %>% filter(school_name == \"CATHOLIC HIGH SCHOOL\") %>% pull(LATITUDE))\ngood_primary_schools$LONGITUDE[idx_catholic] <- as.numeric(\n  primary_schools %>% filter(school_name == \"CATHOLIC HIGH SCHOOL\") %>% pull(LONGITUDE))\n\ngood_primary_schools$LATITUDE[idx_chij] <- as.numeric(\n  primary_schools %>% filter(school_name == \"CHIJ ST. NICHOLAS GIRLS' SCHOOL\") %>% pull(LATITUDE))\ngood_primary_schools$LONGITUDE[idx_chij] <- as.numeric(\n  primary_schools %>% filter(school_name == \"CHIJ ST. NICHOLAS GIRLS' SCHOOL\") %>% pull(LONGITUDE))\n\ngood_primary_schools$LATITUDE[idx_maris] <- as.numeric(\n  primary_schools %>% filter(school_name == \"MARIS STELLA HIGH SCHOOL\") %>% pull(LATITUDE))\ngood_primary_schools$LONGITUDE[idx_maris] <- as.numeric(\n  primary_schools %>% filter(school_name == \"MARIS STELLA HIGH SCHOOL\") %>% pull(LONGITUDE))\ngood_primary_schools %>% filter(is.na(LATITUDE))\ngood_primary_schools <- good_primary_schools %>% mutate(across(c(LATITUDE, LONGITUDE), as.numeric))\n\nwrite_rds(good_primary_schools, \"data/rds/good_primary_schools_geocoded.rds\")\n```\n:::\n\n\n\nRead rds file:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngood_primary_schools <- read_rds(\"data/rds/good_primary_schools_geocoded.rds\")\nsummary(good_primary_schools)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n SCHOOL_NAME           LATITUDE       LONGITUDE    \n Length:30          Min.   :1.294   Min.   :103.7  \n Class :character   1st Qu.:1.320   1st Qu.:103.8  \n Mode  :character   Median :1.340   Median :103.8  \n                    Mean   :1.344   Mean   :103.8  \n                    3rd Qu.:1.359   3rd Qu.:103.9  \n                    Max.   :1.438   Max.   :104.0  \n```\n\n\n:::\n:::\n\n\n\n## **8.Integrate all Locational Factors into one list and save it**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlocational_factors <- list(\n  kindergarten = kindergarten,\n  childcare = childcare,\n  CHASClinics = CHASClinics,\n  supermarket = supermarket,\n  parks = parks,\n  hawker = hawker,\n  eldercare = eldercare,\n  busstop = busstop,\n  mrt = mrt,\n  \n \n  primary_schools = primary_schools %>%\n    filter(!is.na(LATITUDE) & LATITUDE != 0) %>%\n    st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n    st_transform(crs = 3414),\n  \n  shopping_malls = shopping_malls %>%\n    filter(!is.na(LATITUDE)) %>%\n    st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n    st_transform(crs = 3414),\n  \n  good_primary_schools = good_primary_schools %>%\n    filter(!is.na(LATITUDE)) %>%\n    st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n    st_transform(crs = 3414),\n  \n  cbd = cbd %>%\n    st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), crs = 4326) %>%\n    st_transform(crs = 3414))\nwrite_rds(locational_factors, \"data/rds/locational_factors_all.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlocational_factors_all <- read_rds(\"data/rds/locational_factors_all.rds\")\n```\n:::\n\n\n\nCheck data structure and geometry type：\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor(name in names(locational_factors_all)) {\n  cat(sprintf(\"%-25s: \", name))\n  geom_types <- st_geometry_type(locational_factors_all[[name]])\n  unique_types <- unique(geom_types)\n  \n  cat(paste(unique_types, collapse = \", \"))\n  cat(sprintf(\" (%d records)\\n\", nrow(locational_factors_all[[name]])))}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nkindergarten             : POINT (448 records)\nchildcare                : POINT (1925 records)\nCHASClinics              : POINT (1193 records)\nsupermarket              : POINT (526 records)\nparks                    : POINT (450 records)\nhawker                   : POINT (129 records)\neldercare                : POINT (133 records)\nbusstop                  : POINT (5172 records)\nmrt                      : MULTIPOLYGON (231 records)\nprimary_schools          : POINT (336 records)\nshopping_malls           : POINT (98 records)\ngood_primary_schools     : POINT (30 records)\ncbd                      : POINT (1 records)\n```\n\n\n:::\n:::\n\n\n\n## **9. Proximity**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt_coords <- data.frame(\n  station_name = character(),\n  x = numeric(),\n  y = numeric(),\n  stringsAsFactors = FALSE)\n\nfor(i in 1:nrow(locational_factors$mrt)) {\n  tryCatch({\n    centroid <- st_centroid(locational_factors$mrt[i,], of_largest_polygon = TRUE)\n    coords <- st_coordinates(centroid)\n    mrt_coords <- rbind(mrt_coords, data.frame(\n      station_name = locational_factors$mrt$STN_NAM_DE[i],\n      x = coords[1],\n      y = coords[2]\n    ))\n  }, error = function(e) {\n    tryCatch({\n      bbox <- st_bbox(locational_factors$mrt[i,])\n      mrt_coords <<- rbind(mrt_coords, data.frame(\n        station_name = locational_factors$mrt$STN_NAM_DE[i],\n        x = (bbox[\"xmin\"] + bbox[\"xmax\"]) / 2,\n        y = (bbox[\"ymin\"] + bbox[\"ymax\"]) / 2\n      ))\n    }, error = function(e2) {\n      cat(\"Skip\", i, \"\\n\")})})\n  if(i %% 50 == 0) cat(\"processing progress:\", i, \"/\", nrow(locational_factors$mrt), \"\\n\")}\ncat(\"sucessfully extracted\", nrow(mrt_coords), \"MRT Centrepoint\\n\\n\")\nmrt_points <- st_as_sf(mrt_coords, \n                       coords = c(\"x\", \"y\"), \n                       crs = 3414)\nHDBresale.sf <- HDBresale.sf %>%\n  mutate(\n    NUM_KINDERGARTEN_350m = lengths(st_is_within_distance(geometry, locational_factors$kindergarten, dist = 350)),\n    NUM_CHILDCARE_350m = lengths(st_is_within_distance(geometry, locational_factors$childcare, dist = 350)),\n    NUM_BUSSTOP_350m = lengths(st_is_within_distance(geometry, locational_factors$busstop, dist = 350)),\n    NUM_PRISCH_1km = lengths(st_is_within_distance(geometry, locational_factors$primary_schools, dist = 1000)),\n    \n    PROX_CBD = as.numeric(st_distance(geometry, locational_factors$cbd)),\n    PROX_ELDERCARE = as.numeric(apply(st_distance(geometry, locational_factors$eldercare), 1, min)),\n    PROX_HAWKER = as.numeric(apply(st_distance(geometry, locational_factors$hawker), 1, min)),\n    PROX_PARK = as.numeric(apply(st_distance(geometry, locational_factors$parks), 1, min)),\n    PROX_GOOD_PRISCH = as.numeric(apply(st_distance(geometry, locational_factors$good_primary_schools), 1, min)),\n    PROX_MALL = as.numeric(apply(st_distance(geometry, locational_factors$shopping_malls), 1, min)),\n    PROX_SUPERMARKET = as.numeric(apply(st_distance(geometry, locational_factors$supermarket), 1, min)),\n    PROX_MRT = as.numeric(\n      st_distance(geometry,\n                  mrt_points[st_nearest_feature(geometry, mrt_points), ],\n                  by_element = TRUE)))\n\nwrite_rds(HDBresale.sf, \"data/rds/HDBresale_with_all_features.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_with_all_features <- read_rds(\"data/rds/HDBresale_with_all_features.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(HDBresale_with_all_features$PROX_MRT)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  21.36  323.10  552.98  621.95  838.66 2152.49 \n```\n\n\n:::\n:::\n\n\n\n## **10 Exploratory Data Analysis (EDA)**\n\nNext,we will use statistical graphics functions of **ggplot2** package to perform EDA.\n\n### **10.1 EDA using statistical graphics**\n\nWe can plot the distribution of *SELLING_PRICE* by using appropriate Exploratory Data Analysis (EDA) as shown in the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDBresale_with_all_features, \n       aes(x=`resale_price`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n\nThe figure above reveals a right skewed distribution. This means that more condominium units were transacted at relative lower prices.\n\nStatistically, the skewed dsitribution can be normalised by using log transformation. The code chunk below is used to derive a new variable called *LOG_RESALE_PRICE* by using a log transformation on the variable *RESALE_PRICE*. It is performed using `mutate()` of **dplyr** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale.sf <- HDBresale_with_all_features %>%\n  mutate(`LOG_RESALE_PRICE` = log(resale_price))\n```\n:::\n\n\n\nNow, we plot the *LOG_RESALE_PRICE* using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDBresale.sf, \n       aes(x=`LOG_RESALE_PRICE`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\n\nNotice that the distribution is relatively less skewed after the transformation.\n\n### **10.2 Multiple Histogram Plots distribution of variables**\n\nThe code chunk below is used to create 12 histograms. Then, `ggarrange()`is used to organised these histogram into a 3 columns by 4 rows small multiple plot.\n\nAGE = 2025 - lease_commence_date\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale.sf <- HDBresale.sf %>%\n  mutate(AGE = 2025 - lease_commence_date)\n\nFLOOR_AREA <- ggplot(data=HDBresale.sf, aes(x=floor_area_sqm)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nAGE <- ggplot(data=HDBresale.sf, aes(x=AGE)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_CBD <- ggplot(data=HDBresale.sf, aes(x=PROX_CBD)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_ELDERCARE <- ggplot(data=HDBresale.sf, aes(x=PROX_ELDERCARE)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_HAWKER <- ggplot(data=HDBresale.sf, aes(x=PROX_HAWKER)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_MRT <- ggplot(data=HDBresale.sf, aes(x=PROX_MRT)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_PARK <- ggplot(data=HDBresale.sf, aes(x=PROX_PARK)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_MALL <- ggplot(data=HDBresale.sf, aes(x=PROX_MALL)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_GOOD_PRISCH <- ggplot(data=HDBresale.sf, aes(x=PROX_GOOD_PRISCH)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_SUPERMARKET <- ggplot(data=HDBresale.sf, aes(x=PROX_SUPERMARKET)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nNUM_KINDERGARTEN_350m <- ggplot(data=HDBresale.sf, aes(x=NUM_KINDERGARTEN_350m)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nNUM_CHILDCARE_350m <- ggplot(data=HDBresale.sf, aes(x=NUM_CHILDCARE_350m)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nNUM_PRISCH_1km <- ggplot(data=HDBresale.sf, aes(x=NUM_PRISCH_1km)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nggarrange(FLOOR_AREA, AGE, PROX_CBD, PROX_ELDERCARE,\n          PROX_HAWKER, PROX_MRT, PROX_PARK, PROX_MALL,\n          PROX_GOOD_PRISCH, PROX_SUPERMARKET, \n          NUM_KINDERGARTEN_350m, NUM_CHILDCARE_350m,NUM_PRISCH_1km,\n          ncol = 3, nrow = 5 )\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-45-1.png){width=1152}\n:::\n:::\n\n\n\n**floor_area_sqm (area) :**\n\n-   Most 4-bedroom HDB units are between 80 and 120 square meters\n\n-   The normal distribution is concentrated in the middle\n\n**AGE (Building Age) :**\n\n-   Most HDBS are between 10 and 40 years old\n\n-   Some are very old (50 years old)\n\n**PROX_CBD (Distance to CBD) :**\n\n-   Most HDBS are 5,000 to 15,000 meters (5 to 15 kilometers) away from the CBD\n\n-   Few HDBS are located near the CBD\n\n**PROX_MRT (Distance to MRT) :**\n\n-   Most are within the range of 500 to 1,500 meters\n\n-   It rarely exceeds 2,000 meters (Singapore's MRT is very dense).\n\n**NUM_KINDERGARTEN_350m:**\n\n-   There are 0 to 5 kindergartens within a 350-meter radius around most HDBS\n\n### **10.3 Drawing Statistical Point Map**\n\nWe want to reveal the geospatial distribution HDB resale prices in Singapore. The map will be prepared by using **tmap** package.\n\nFirst, we will turn on the interactive mode of tmap by using the code chunk below.(You can use tmap_mode(\"view\") to see each point.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\nNext, the code chunks below is used to create an interactive point symbol map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz_svy21)+\n  tm_polygons() +\ntm_shape(HDBresale.sf) +  \n  tm_dots(fill = \"resale_price\",\n          fill_alpha = 0.6,\n          size = 0.5,\n          fill.scale = tm_scale_intervals(\n            style=\"quantile\")) + \n  tm_layout(\n    legend.outside = TRUE,                   \n    legend.outside.position = \"right\")        \n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-47-1.png){width=864}\n:::\n:::\n\n\n\nBefore moving on to the next section, don't forget change to plot mode avoid long time loading.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n## 11.**Pricing Modelling in R**\n\nIn this section, you will learn how to use R-based lm() to build a hedonic pricing model for HDB resale units.\n\n### 11.1 **Multiple Linear Regression Method**\n\n#### 11.1.1 Visualising the relationships of the independent variables\n\nBefore building a multiple regression model, it is important to ensure that the independent variables used are not highly correlated to each other. If these highly correlated independent variables are used in building a regression model by mistake, the quality of the model will be compromised. This phenomenon is known as multicollinearity in statistics.\n\nCorrelation matrix is commonly used to visualise the relationships between the independent variables. Besides the `pairs()` function of R, there are many packages that support the display of a correlation matrix. In this section, the **corrplot** package will be used.\n\nThe code chunk below is used to plot a correlation matrix of the relationship between the independent variables in the HDB resale dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrplot(cor(HDBresale.sf %>% \n               st_drop_geometry() %>%\n               select(floor_area_sqm, AGE, PROX_CBD, PROX_ELDERCARE, \n                      PROX_HAWKER, PROX_MRT, PROX_PARK, PROX_MALL, \n                      PROX_GOOD_PRISCH, PROX_SUPERMARKET,\n                      NUM_KINDERGARTEN_350m, NUM_CHILDCARE_350m, \n                      NUM_BUSSTOP_350m, NUM_PRISCH_1km)), \n         diag = FALSE, \n         order = \"AOE\",\n         tl.pos = \"td\", \n         tl.cex = 0.8, \n         method = \"number\", \n         type = \"upper\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-49-1.png){width=768}\n:::\n:::\n\n\n\nMatrix reordering is very important for mining the hidden structure and pattern in the correlation matrix. There are four methods in corrplot (parameter order), named \"AOE\", \"FPC\", \"hclust\", and \"alphabet\". In the code chunk above, AOE order is used because it effectively groups highly correlated variables together by using the angular order of the eigenvectors method suggested by Michael Friendly. This ordering method is particularly useful for identifying potential multicollinearity issues, as it arranges variables such that those with similar correlation patterns are positioned adjacent to each other in the matrix, making it easier to spot problematic variable pairs.\n\nFrom the correlation matrix, the highest correlation observed is between NUM_CHILDCARE_350m and NUM_BUSSTOP_350m (r = 0.47), followed by PROX_MRT and PROX_ELDERCARE (r = 0.42). However, none of these correlations exceed the commonly accepted threshold of 0.8 for severe multicollinearity concerns.\n\nTherefore, all 14 independent variables can be retained for subsequent model building without significant multicollinearity issues. This ensures that each variable contributes unique information to the hedonic pricing model, allowing for more comprehensive analysis of factors influencing HDB resale prices.\n\n### 11.2 **Building a HDBresale pricing model using multiple linear regression method**\n\nThe code chunk below uses `lm()` to calibrate the multiple linear regression model with all 14 independent variables identified from the correlation analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb.mlr <- lm(\n  formula = resale_price ~ floor_area_sqm + AGE + \n    PROX_CBD + PROX_ELDERCARE + PROX_HAWKER + \n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_GOOD_PRISCH + PROX_SUPERMARKET +\n    NUM_KINDERGARTEN_350m + NUM_CHILDCARE_350m + \n    NUM_BUSSTOP_350m + NUM_PRISCH_1km,\n  data = HDBresale.sf)\n\nsummary(hdb.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm + AGE + PROX_CBD + \n    PROX_ELDERCARE + PROX_HAWKER + PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_GOOD_PRISCH + PROX_SUPERMARKET + NUM_KINDERGARTEN_350m + \n    NUM_CHILDCARE_350m + NUM_BUSSTOP_350m + NUM_PRISCH_1km, data = HDBresale.sf)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-241579  -52125       1   44401  465649 \n\nCoefficients:\n                        Estimate Std. Error  t value Pr(>|t|)    \n(Intercept)            7.505e+05  1.288e+04   58.285  < 2e-16 ***\nfloor_area_sqm         4.855e+03  1.365e+02   35.577  < 2e-16 ***\nAGE                   -6.866e+03  6.713e+01 -102.287  < 2e-16 ***\nPROX_CBD              -2.261e+01  2.672e-01  -84.600  < 2e-16 ***\nPROX_ELDERCARE        -1.266e+01  1.595e+00   -7.936 2.34e-15 ***\nPROX_HAWKER           -3.058e+01  2.066e+00  -14.804  < 2e-16 ***\nPROX_MRT              -5.206e+01  2.759e+00  -18.866  < 2e-16 ***\nPROX_PARK             -1.287e+01  2.523e+00   -5.100 3.48e-07 ***\nPROX_MALL             -1.508e+01  2.266e+00   -6.656 2.98e-11 ***\nPROX_GOOD_PRISCH       6.162e+00  7.651e-01    8.054 9.08e-16 ***\nPROX_SUPERMARKET      -3.101e+00  5.116e+00   -0.606  0.54448    \nNUM_KINDERGARTEN_350m  9.046e+03  9.588e+02    9.434  < 2e-16 ***\nNUM_CHILDCARE_350m    -1.910e+03  4.749e+02   -4.023 5.80e-05 ***\nNUM_BUSSTOP_350m       1.065e+03  3.281e+02    3.247  0.00117 ** \nNUM_PRISCH_1km        -3.170e+03  4.247e+02   -7.465 9.16e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 81210 on 8664 degrees of freedom\nMultiple R-squared:  0.7448,\tAdjusted R-squared:  0.7444 \nF-statistic:  1806 on 14 and 8664 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThe output report reveals that the multiple linear regression model achieves an R² of 0.7448, indicating that the model explains approximately 74.5% of the variation in HDB resale prices. The F-statistic (1806) with p-value \\< 2.2e-16 suggests that the model as a whole is statistically significant.\n\nHowever, examining individual coefficients shows that PROX_SUPERMARKET (p = 0.54448) is not statistically significant at the 95% confidence level. All other 13 variables are highly significant (p \\< 0.001 or p \\< 0.01). Given this result, we will refine the model by excluding the non-significant variable in the subsequent model calibration.\n\n**Note：**\n\nThe code chunk above consists of two parts:\n\n- `lm()` of Base R is used to calibrate a multiple linear regression model. The model output is stored in an lm object called *condo.mlr*.\n\n- `summary()` is used to print the model output.\n\n### 11.3 **Refining the Model**\n\nWith reference to the report above, it is clear that not all independent variables are statistically significant. Specifically, PROX_SUPERMARKET (p = 0.54448) fails to meet the 95% confidence threshold. We will refine the model by removing this non-significant variable while retaining the 13 statistically significant predictors.\n\nNow, we are ready to calibrate the refined model using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb.mlr1 <- lm(\n  formula = resale_price ~ floor_area_sqm + AGE + \n    PROX_CBD + PROX_ELDERCARE + PROX_HAWKER + \n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_GOOD_PRISCH + \n    NUM_KINDERGARTEN_350m + NUM_CHILDCARE_350m + \n    NUM_BUSSTOP_350m + NUM_PRISCH_1km,\n  data = HDBresale.sf)\n\nsummary(hdb.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm + AGE + PROX_CBD + \n    PROX_ELDERCARE + PROX_HAWKER + PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_GOOD_PRISCH + NUM_KINDERGARTEN_350m + NUM_CHILDCARE_350m + \n    NUM_BUSSTOP_350m + NUM_PRISCH_1km, data = HDBresale.sf)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-241708  -52141     -88   44522  465953 \n\nCoefficients:\n                        Estimate Std. Error  t value Pr(>|t|)    \n(Intercept)            7.496e+05  1.279e+04   58.602  < 2e-16 ***\nfloor_area_sqm         4.852e+03  1.364e+02   35.582  < 2e-16 ***\nAGE                   -6.864e+03  6.706e+01 -102.368  < 2e-16 ***\nPROX_CBD              -2.262e+01  2.665e-01  -84.863  < 2e-16 ***\nPROX_ELDERCARE        -1.264e+01  1.595e+00   -7.923 2.60e-15 ***\nPROX_HAWKER           -3.055e+01  2.065e+00  -14.794  < 2e-16 ***\nPROX_MRT              -5.219e+01  2.751e+00  -18.974  < 2e-16 ***\nPROX_PARK             -1.267e+01  2.503e+00   -5.064 4.20e-07 ***\nPROX_MALL             -1.518e+01  2.260e+00   -6.715 2.00e-11 ***\nPROX_GOOD_PRISCH       6.161e+00  7.651e-01    8.053 9.15e-16 ***\nNUM_KINDERGARTEN_350m  9.054e+03  9.587e+02    9.444  < 2e-16 ***\nNUM_CHILDCARE_350m    -1.871e+03  4.703e+02   -3.977 7.03e-05 ***\nNUM_BUSSTOP_350m       1.068e+03  3.280e+02    3.257  0.00113 ** \nNUM_PRISCH_1km        -3.147e+03  4.230e+02   -7.440 1.10e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 81200 on 8665 degrees of freedom\nMultiple R-squared:  0.7448,\tAdjusted R-squared:  0.7444 \nF-statistic:  1945 on 13 and 8665 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThe output above reveals that all explanatory variables are statistically significant at 95% confident level.\n\n### 11.4 **Preparing Publication Quality Table: gtsummary method**\n\nThe **gtsummary** package provides an elegant and flexible way to create publication-ready summary tables in R. In the code chunk below, `tbl_regression()` is used to create a well-formatted regression report. With the gtsummary package, model statistics can be included in the report by either appending them to the report table using `add_glance_table()` or adding them as a table source note using `add_glance_source_note()` as shown in the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(hdb.mlr1, \n               intercept = TRUE) %>% \n  add_glance_source_note(\n    label = list(sigma ~ \"\\U03C3\"),\n    include = c(r.squared, adj.r.squared, \n                AIC, statistic,\n                p.value, sigma))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"izsuilbtya\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#izsuilbtya table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#izsuilbtya thead, #izsuilbtya tbody, #izsuilbtya tfoot, #izsuilbtya tr, #izsuilbtya td, #izsuilbtya th {\n  border-style: none;\n}\n\n#izsuilbtya p {\n  margin: 0;\n  padding: 0;\n}\n\n#izsuilbtya .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#izsuilbtya .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#izsuilbtya .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#izsuilbtya .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#izsuilbtya .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#izsuilbtya .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#izsuilbtya .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#izsuilbtya .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#izsuilbtya .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#izsuilbtya .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#izsuilbtya .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#izsuilbtya .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#izsuilbtya .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#izsuilbtya .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#izsuilbtya .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izsuilbtya .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#izsuilbtya .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#izsuilbtya .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#izsuilbtya .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izsuilbtya .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#izsuilbtya .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izsuilbtya .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#izsuilbtya .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izsuilbtya .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#izsuilbtya .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#izsuilbtya .gt_left {\n  text-align: left;\n}\n\n#izsuilbtya .gt_center {\n  text-align: center;\n}\n\n#izsuilbtya .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#izsuilbtya .gt_font_normal {\n  font-weight: normal;\n}\n\n#izsuilbtya .gt_font_bold {\n  font-weight: bold;\n}\n\n#izsuilbtya .gt_font_italic {\n  font-style: italic;\n}\n\n#izsuilbtya .gt_super {\n  font-size: 65%;\n}\n\n#izsuilbtya .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#izsuilbtya .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#izsuilbtya .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#izsuilbtya .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#izsuilbtya .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#izsuilbtya .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#izsuilbtya .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#izsuilbtya .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#izsuilbtya div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"PHN0cm9uZz5DaGFyYWN0ZXJpc3RpYzwvc3Ryb25nPg==\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"PHN0cm9uZz5CZXRhPC9zdHJvbmc+\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"PHN0cm9uZz45NSUgQ0k8L3N0cm9uZz4=\"><span class='gt_from_md'><strong>95% CI</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"PHN0cm9uZz5wLXZhbHVlPC9zdHJvbmc+\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">749,591</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">724,518, 774,665</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">floor_area_sqm</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">4,852</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">4,585, 5,119</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AGE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-6,864</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-6,996, -6,733</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CBD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-23</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-23, -22</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-13</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-16, -9.5</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_HAWKER</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-31</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-35, -27</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_MRT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-52</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-58, -47</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-13</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-18, -7.8</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_MALL</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-15</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-20, -11</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_GOOD_PRISCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">6.2</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">4.7, 7.7</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">NUM_KINDERGARTEN_350m</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">9,054</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">7,175, 10,933</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">NUM_CHILDCARE_350m</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-1,871</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-2,793, -949</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">NUM_BUSSTOP_350m</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1,068</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">425, 1,711</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">NUM_PRISCH_1km</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-3,147</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">-3,977, -2,318</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"UsKyID0gMC43NDU7IEFkanVzdGVkIFLCsiA9IDAuNzQ0OyBBSUMgPSAyMjAsODczOyBTdGF0aXN0aWMgPSAxLDk0NTsgcC12YWx1ZSA9ICZsdDswLjAwMTsgz4MgPSA4MSwyMDQ=\"><span class='gt_from_md'>R² = 0.745; Adjusted R² = 0.744; AIC = 220,873; Statistic = 1,945; p-value = &lt;0.001; σ = 81,204</span></span></td>\n    </tr>\n  </tfoot>\n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"Q0kgPSBDb25maWRlbmNlIEludGVydmFs\"><span class='gt_from_md'>CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n### 11.5 **Regression Diagnostics**\n\nBefore applying the model, it is essential to verify that the key assumptions of multiple linear regression are satisfied. This section performs diagnostic tests to assess multicollinearity, linearity, and other potential issues that could compromise model validity.\n\nTo perform comprehensive regression diagnostics, this analysis utilizes the **performance** package, which provides a suite of tools for assessing model quality and validating regression assumptions. It is called [**olsrr**](https://olsrr.rsquaredacademy.com/). Key diagnostic capabilities include:\n\n-   comprehensive regression output\n\n-   residual diagnostics\n\n-   measures of influence\n\n-   heteroskedasticity tests\n\n-   collinearity diagnostics\n\n-   model fit assessment\n\n-   variable contribution assessment\n\n-   variable selection procedures\n\nThese diagnostics ensure that the multiple linear regression model meets the necessary assumptions for valid statistical inference.\n\n#### 11.5.1 **Multicollinearity Test**\n\nMulticollinearity occurs when independent variables are highly correlated with each other, making it difficult to determine the individual effect of each variable on the dependent variable. This can lead to unstable coefficient estimates and inflated standard errors.\n\nThe code chunk below uses `check_collinearity()` from the **performance** package to assess multicollinearity through Variance Inflation Factor (VIF) values.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_collinearity(hdb.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n                  Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n        floor_area_sqm 1.11 [1.09, 1.14]     1.05      0.90     [0.88, 0.92]\n                   AGE 1.18 [1.15, 1.21]     1.08      0.85     [0.83, 0.87]\n              PROX_CBD 1.85 [1.79, 1.90]     1.36      0.54     [0.53, 0.56]\n        PROX_ELDERCARE 1.35 [1.31, 1.38]     1.16      0.74     [0.72, 0.76]\n           PROX_HAWKER 1.18 [1.15, 1.21]     1.09      0.85     [0.83, 0.87]\n              PROX_MRT 1.41 [1.37, 1.45]     1.19      0.71     [0.69, 0.73]\n             PROX_PARK 1.34 [1.30, 1.37]     1.16      0.75     [0.73, 0.77]\n             PROX_MALL 1.41 [1.38, 1.45]     1.19      0.71     [0.69, 0.73]\n      PROX_GOOD_PRISCH 1.19 [1.17, 1.23]     1.09      0.84     [0.82, 0.86]\n NUM_KINDERGARTEN_350m 1.37 [1.34, 1.41]     1.17      0.73     [0.71, 0.75]\n    NUM_CHILDCARE_350m 1.53 [1.48, 1.57]     1.24      0.66     [0.64, 0.67]\n      NUM_BUSSTOP_350m 1.15 [1.12, 1.18]     1.07      0.87     [0.85, 0.89]\n        NUM_PRISCH_1km 1.40 [1.36, 1.44]     1.18      0.72     [0.70, 0.73]\n```\n\n\n:::\n:::\n\n\n\nVisualization of VIF values:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif_results <- check_collinearity(hdb.mlr1)\nplot(vif_results) + \n  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 9)) +\n  labs(y = \"VIF (log-scaled)\") \n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n\nThe VIF diagnostic follows these thresholds:\n\n-   VIF \\< 5: No concern\n\n-   VIF 5-10: Moderate concern\n\n-   VIF \\> 10: Severe multicollinearity\n\nSince the VIF of the independent variables are less than 5. We can safely conclude that there are no sign of multicollinearity among the independent variables.\n\n#### 11.5.2 **Linearity Test**\n\nMultiple linear regression assumes that the relationship between the dependent variable and independent variables is linear and additive. This assumption must be verified to ensure model validity.\n\nThe code chunk below uses `check_model()` from the **performance** package to assess the linearity assumption through residual plots.\n\n\n\n::: {.cell}\n\n:::\n\n\n\nWe can make this graph wider and easier to view by changing the value of Y-axis. (Just for reference）\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fitted(hdb.mlr1), residuals(hdb.mlr1),\n     xlim = c(300000, 1100000),\n     xlab = \"Fitted values\",\n     ylab = \"Residuals\",\n     main = \"Linearity\",\n     pch = 16,\n     col = \"steelblue\")\nabline(h = 0, lty = 2)\nlines(lowess(fitted(hdb.mlr1), residuals(hdb.mlr1)), col = \"green\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n\nThe residual plot shows a slight curved pattern in the LOESS smooth line (green), suggesting some deviation from perfect linearity. The residuals exhibit a subtle U-shaped pattern, with negative residuals at lower price ranges and varying patterns at higher prices.\n\nWhile this indicates that the relationship between HDB resale prices and the predictors is not perfectly linear, the deviation is relatively moderate. This non-linearity may be attributed to the spatial heterogeneity in pricing mechanisms across different locations in Singapore, which motivates the use of Geographically Weighted Regression (GWR) in subsequent analysis. GWR is designed to capture such local variations and non-stationary relationships that a global linear model cannot fully address.\n\n#### 11.5.3 Test for Normality Assumption\n\nThe normality assumption requires that the model's residuals are normally distributed. This is important for the validity of hypothesis tests and confidence intervals. Visual methods such as Q-Q plots and statistical tests like the Shapiro-Wilk test are commonly used to assess this assumption.\n\nThe code chunk below uses `check_normality()` from the **performance** package to test the normality assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_normality(hdb.mlr1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Non-normality of residuals detected (p < .001).\n```\n\n\n:::\n:::\n\n\n\nThe print above reveals that the p-value of the normality assumption test is less than alpha value of 0.05. Hence we reject the normality assumption at 95% confident level.\n\nThe statistical test result indicates whether the residuals deviate significantly from normality. However, it is important to note that formal normality tests like Shapiro-Wilk are highly sensitive to large sample sizes and often yield significant results even for minor deviations. Visual inspection through Q-Q plots is generally more informative for assessing practical significance. The Q-Q plot below provides a visual assessment of normality:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqqnorm(residuals(hdb.mlr1), main = \"Normal Q-Q Plot\")\nqqline(residuals(hdb.mlr1), col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n\nThe Q-Q plot above shows that the majority of data points fall along the diagonal reference line, indicating that the residuals largely follow a normal distribution. The deviations at both tails suggest a slightly heavy-tailed distribution, which is common in large datasets with some extreme values.\n\nAlternatively, `check_model()` from the **performance** package can be used for a comprehensive visual assessment of multiple model assumptions simultaneously, as shown in the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(hdb.mlr1,\n            check= \"normality\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n\nThe figure reveals that the residual of the multiple linear regression model (i.e. hdb.mlr1) is resemble normal distribution.\n\n## 12.**Testing for Spatial Autocorrelation**\n\nSince the hedonic model uses geographically referenced data, it is essential to test for spatial autocorrelation in the residuals. Traditional OLS regression assumes that observations are independent, but spatial data often violates this assumption due to the presence of spatial dependence.\n\nSpatial autocorrelation occurs when a variable is correlated with itself across different spatial locations. This phenomenon is grounded in Tobler's First Law of Geography: \"Everything is related to everything else, but nearby things are more related than distant things.\" In the context of housing prices, properties located near each other tend to have similar prices due to shared neighborhood characteristics, accessibility, and amenities.\n\nIgnoring spatial autocorrelation in a regression model can lead to serious statistical issues:\n\n-   **Biased and inefficient coefficient estimates**: If autocorrelation is present, standard errors of the model coefficients can be wrong, leading to unreliable hypothesis tests (p-values). The model might appear more significant than it is.\n\n-   **Misleading significance tests**: Standard regression models cannot distinguish between true explanatory power and the influence of spatial patterns, resulting in inaccurate p-values.\n\n-   **Model misspecification**: Significant spatial autocorrelation in the regression residuals often signals that important explanatory variables are missing from the model. The spatial patterning of the residuals (over- and under-predictions) can provide clues about what these missing variables might be.\n\n-   **Inflated Type I error rates**: Researchers might incorrectly reject a true null.\n\nTo test for spatial autocorrelation, Moran's I test is performed on the model residuals. Significant spatial autocorrelation in the residuals indicates that the OLS model fails to capture the full spatial structure of the data, providing justification for using Geographically Weighted Regression (GWR).\n\nFirst, extract the residuals from the multiple linear regression model:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmlr.output <- as.data.frame(hdb.mlr1$residuals)\n```\n:::\n\n\n\nSecondly, join the residuals with the spatial data frame:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_resale.res <- cbind(HDBresale.sf, hdb.mlr1$residuals) %>%\n  rename(MLR_RES = `hdb.mlr1.residuals`)\n```\n:::\n\n\n\nVisualize the spatial distribution of residuals:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\ntm_shape(mpsz_svy21) +\n  tm_polygons(fill_alpha = 0.4) +\ntm_shape(hdb_resale.res) +  \n  tm_dots(\n    fill = \"MLR_RES\",\n    size = 0.5,\n    col = \"black\",\n    fill.scale = tm_scale(\n      n = 10,\n      values = rev(brewer.pal(11, \"RdBu\")),\n      style = \"quantile\",\n      midpoint = NA),\n    fill.legend = tm_legend(title = \"Residuals\")\n  ) + \n  tm_title(\"MLR Residuals (Quantile Classification)\") +\n  tm_layout(legend.outside = TRUE) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n\n\nThe map reveals spatial clustering of residuals, suggesting potential spatial autocorrelation. Compute distance-based spatial weights:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhdb_resale.res <- hdb_resale.res %>% \n  mutate(\n    nb = st_dist_band(st_geometry(geometry), upper = 1500),\n    wt = st_weights(nb, style = \"W\"),\n    .before = 1)\n```\n:::\n\n\n\nPerform Moran's I test:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nglobal_moran_perm(\n  hdb_resale.res$MLR_RES, \n  nb = hdb_resale.res$nb, \n  wt = hdb_resale.res$wt,\n  alternative = \"two.sided\", \n  nsim = 499)\n```\n:::\n\n\n\n![](images/clipboard-3782343031.png){fig-align=\"center\" width=\"447\"}\n\nThe Global Moran's I test yields a statistic of 0.35838 (p \\< 2.2e-16), rejecting the null hypothesis of random distribution. The positive Moran's I value indicates strong spatial clustering of residuals, confirming that the OLS model fails to capture spatial dependencies in HDB pricing. This justifies the use of GWR to account for spatial non-stationarity.\n\n## **13 Building** explanatory **Models using GWmodel**\n\n### **13.1 Building Adaptive Bandwidth GWR Model**\n\n#### 13.1.1 Computing the adaptive bandwidth\n\nWe will first use `bw.gwr()` to determine the recommended data point to use.\n\nThe code chunk used look very similar to the one used to compute the fixed bandwidth except the `adaptive` argument has changed to **TRUE**. And for save time we save to rds file：\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- bw.gwr(\n  formula = resale_price ~ floor_area_sqm + AGE  + \n    PROX_CBD + PROX_ELDERCARE + PROX_HAWKER    +\n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_GOOD_PRISCH + \n    NUM_KINDERGARTEN_350m + NUM_CHILDCARE_350m +\n    NUM_BUSSTOP_350m + NUM_PRISCH_1km, \n  data=HDBresale.sf, \n  approach=\"CV\", \n  kernel=\"gaussian\", \n  adaptive=TRUE, \n  longlat=FALSE)\n\nsaveRDS(bw.adaptive, \"data/rds/bw_adaptive.rds\")\n```\n:::\n\n\n\n![](images/clipboard-4037241353.png){fig-align=\"center\" width=\"426\"}\n\nThe result shows that the 41 is the recommended data points to be used.\n\nNext,we can read the rds file for following work:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- readRDS(\"data/rds/bw_adaptive.rds\")\n```\n:::\n\n\n\n#### 13.1.2 Constructing the adaptive bandwidth gwr model\n\nNow, we can go ahead to calibrate the gwr-based explanatory hdbmodel by using adaptive bandwidth and gaussian kernel as shown in the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive <- gwr.basic(\n  formula = resale_price ~ floor_area_sqm + AGE  + \n    PROX_CBD + PROX_ELDERCARE + PROX_HAWKER    +\n    PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_GOOD_PRISCH + \n    NUM_KINDERGARTEN_350m + NUM_CHILDCARE_350m + NUM_BUSSTOP_350m + NUM_PRISCH_1km, \n  data=HDBresale.sf, \n  bw=bw.adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE, \n  longlat = FALSE)\nsaveRDS(gwr.adaptive, \"data/rds/gwr_adaptive.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive <- readRDS(\"data/rds/gwr_adaptive.rds\")\n```\n:::\n\n\n\nThe code below can be used to display the model output.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-16 18:58:24.198375 \n   Call:\n   gwr.basic(formula = resale_price ~ floor_area_sqm + AGE + PROX_CBD + \n    PROX_ELDERCARE + PROX_HAWKER + PROX_MRT + PROX_PARK + PROX_MALL + \n    PROX_GOOD_PRISCH + NUM_KINDERGARTEN_350m + NUM_CHILDCARE_350m + \n    NUM_BUSSTOP_350m + NUM_PRISCH_1km, data = HDBresale.sf, bw = bw.adaptive, \n    kernel = \"gaussian\", adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm AGE PROX_CBD PROX_ELDERCARE PROX_HAWKER PROX_MRT PROX_PARK PROX_MALL PROX_GOOD_PRISCH NUM_KINDERGARTEN_350m NUM_CHILDCARE_350m NUM_BUSSTOP_350m NUM_PRISCH_1km\n   Number of data points: 8679\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n    Min      1Q  Median      3Q     Max \n-241708  -52141     -88   44522  465953 \n\n   Coefficients:\n                           Estimate Std. Error  t value Pr(>|t|)    \n   (Intercept)            7.496e+05  1.279e+04   58.602  < 2e-16 ***\n   floor_area_sqm         4.852e+03  1.364e+02   35.582  < 2e-16 ***\n   AGE                   -6.864e+03  6.706e+01 -102.368  < 2e-16 ***\n   PROX_CBD              -2.262e+01  2.665e-01  -84.863  < 2e-16 ***\n   PROX_ELDERCARE        -1.264e+01  1.595e+00   -7.923 2.60e-15 ***\n   PROX_HAWKER           -3.055e+01  2.065e+00  -14.794  < 2e-16 ***\n   PROX_MRT              -5.219e+01  2.751e+00  -18.974  < 2e-16 ***\n   PROX_PARK             -1.267e+01  2.503e+00   -5.064 4.20e-07 ***\n   PROX_MALL             -1.518e+01  2.260e+00   -6.715 2.00e-11 ***\n   PROX_GOOD_PRISCH       6.161e+00  7.651e-01    8.053 9.15e-16 ***\n   NUM_KINDERGARTEN_350m  9.054e+03  9.587e+02    9.444  < 2e-16 ***\n   NUM_CHILDCARE_350m    -1.871e+03  4.703e+02   -3.977 7.03e-05 ***\n   NUM_BUSSTOP_350m       1.068e+03  3.280e+02    3.257  0.00113 ** \n   NUM_PRISCH_1km        -3.147e+03  4.230e+02   -7.440 1.10e-13 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 81200 on 8665 degrees of freedom\n   Multiple R-squared: 0.7448\n   Adjusted R-squared: 0.7444 \n   F-statistic:  1945 on 13 and 8665 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 5.713833e+13\n   Sigma(hat): 81148.22\n   AIC:  220873.3\n   AICc:  220873.4\n   BIC:  212436.4\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 41 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                Min.     1st Qu.      Median     3rd Qu.\n   Intercept             -2.3660e+08  5.5548e+04  7.9470e+05  1.4047e+06\n   floor_area_sqm        -2.7165e+04  2.4820e+03  3.3634e+03  5.0877e+03\n   AGE                   -1.5274e+05 -9.6740e+03 -5.8949e+03 -4.3438e+03\n   PROX_CBD              -2.4511e+04 -6.0008e+01 -1.5627e+01  4.2870e+01\n   PROX_ELDERCARE        -1.8528e+04 -4.5689e+01  1.2803e+01  6.6996e+01\n   PROX_HAWKER           -1.7944e+03 -6.1980e+01 -7.7548e+00  4.9810e+01\n   PROX_MRT              -5.8208e+04 -1.1711e+02 -5.8026e+01  7.3466e+00\n   PROX_PARK             -1.7633e+04 -5.3525e+01 -1.0572e+01  3.6998e+01\n   PROX_MALL             -4.0560e+04 -1.0762e+02 -3.1907e+01  2.0826e+01\n   PROX_GOOD_PRISCH      -2.5069e+04 -7.5345e+01 -7.1341e+00  5.9971e+01\n   NUM_KINDERGARTEN_350m -3.8796e+05 -1.0918e+04 -2.3161e+03  3.2601e+03\n   NUM_CHILDCARE_350m    -1.2721e+05 -1.5090e+03  9.9073e+02  4.3129e+03\n   NUM_BUSSTOP_350m      -1.9160e+04 -1.8917e+03  3.4080e+02  2.7148e+03\n   NUM_PRISCH_1km        -5.2553e+05 -4.1897e+03  1.1592e+03  6.1345e+03\n                               Max.\n   Intercept             1.9840e+08\n   floor_area_sqm        7.6945e+04\n   AGE                   3.0462e+04\n   PROX_CBD              1.2541e+04\n   PROX_ELDERCARE        2.3545e+04\n   PROX_HAWKER           1.0862e+04\n   PROX_MRT              4.2064e+04\n   PROX_PARK             5.6745e+03\n   PROX_MALL             4.5927e+04\n   PROX_GOOD_PRISCH      2.8728e+04\n   NUM_KINDERGARTEN_350m 4.9847e+06\n   NUM_CHILDCARE_350m    5.5399e+04\n   NUM_BUSSTOP_350m      7.1306e+04\n   NUM_PRISCH_1km        3.2616e+06\n   ************************Diagnostic information*************************\n   Number of data points: 8679 \n   Effective number of parameters (2trace(S) - trace(S'S)): 1235.574 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 7443.426 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 208807 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 207547.2 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 206918.7 \n   Residual sum of squares: 1.100688e+13 \n   R-square value:  0.9508335 \n   Adjusted R-square value:  0.942671 \n\n   ***********************************************************************\n   Program stops at: 2025-11-16 18:59:01.845139 \n```\n\n\n:::\n:::\n\n\n\n**Model Performance Comparison**\n\n1.  **Multiple Linear Regression (Global Model):**\n\n-   R² = 0.745\n\n-   AIC = 220,873\n\n2.  **Geographically Weighted Regression (Local Model):**\n\n-   R² = 0.951\n\n-   AIC = 207,547\n\n-   Optimal bandwidth: 41 neighbors\n\n**Improvement**:\n\nThe GWR model demonstrates substantial improvement over the global regression model, with R² increasing from 0.745 to 0.951 (+27.6%) and AIC decreasing by 13,326 points. This confirms significant spatial heterogeneity in HDB pricing mechanisms across Singapore, validating the need for spatially adaptive modeling.\n\n#### 13.1.3 **Visualising GWR Output**\n\nIn addition to regression residuals, the output feature class table includes fields for observed and predicted y values, condition number (cond), Local R2, residuals, and explanatory variable coefficients and standard errors:\n\n-   Condition Number: this diagnostic evaluates local collinearity. In the presence of strong local collinearity, results become unstable. Results associated with condition numbers larger than 30, may be unreliable.\n\n-   Local R2: these values range between 0.0 and 1.0 and indicate how well the local regression model fits observed y values. Very low values indicate the local model is performing poorly. Mapping the Local R2 values to see where GWR predicts well and where it predicts poorly may provide clues about important variables that may be missing from the regression model.\n\n-   Predicted: these are the estimated (or fitted) y values 3. computed by GWR.\n\n-   Residuals: to obtain the residual values, the fitted y values are subtracted from the observed y values. Standardized residuals have a mean of zero and a standard deviation of 1. A cold-to-hot rendered map of standardized residuals can be produce by using these values.\n\n-   Coefficient Standard Error: these values measure the reliability of each coefficient estimate. Confidence in those estimates are higher when standard errors are small in relation to the actual coefficient values. Large standard errors may indicate problems with local collinearity.\n\nThey are all stored in a SpatialPointsDataFrame or SpatialPolygonsDataFrame object integrated with fit.points, GWR coefficient estimates, y value, predicted values, coefficient standard errors and t-values in its “data” slot in an object called **SDF** of the output list.\n\n#### **13.1.4 Converting SDF into *sf* data.frame**\n\nTo visualise the fields in **SDF**, we need to first covert it into **sf** data.frame by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale.sf.adaptive <-\n  st_as_sf(gwr.adaptive$SDF) %>%\n  st_transform(crs=3414)\n```\n:::\n\n\n\nNext, `glimpse()` is used to display the content of ***HDBresale.sf.adaptive*** sf data frame.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(HDBresale.sf.adaptive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,679\nColumns: 49\n$ Intercept                <dbl> 646462.3, 596967.4, 646462.3, 1053571.1, 5969…\n$ floor_area_sqm           <dbl> 6288.798, 6312.476, 6288.798, 4977.858, 6312.…\n$ AGE                      <dbl> -11040.405, -9863.030, -11040.405, -9603.110,…\n$ PROX_CBD                 <dbl> -16.57333, -15.30330, -16.57333, -54.43442, -…\n$ PROX_ELDERCARE           <dbl> 24.23300, 40.13160, 24.23300, 61.71857, 40.13…\n$ PROX_HAWKER              <dbl> 23.483137, 2.283975, 23.483137, 24.523041, 2.…\n$ PROX_MRT                 <dbl> -16.743900, 7.346596, -16.743900, -26.641848,…\n$ PROX_PARK                <dbl> -44.9461131, -0.2782228, -44.9461131, -14.454…\n$ PROX_MALL                <dbl> -24.531243, -41.995371, -24.531243, 4.636736,…\n$ PROX_GOOD_PRISCH         <dbl> -26.61269, -26.63483, -26.61269, 21.93356, -2…\n$ NUM_KINDERGARTEN_350m    <dbl> -6790.7635, 221.4027, -6790.7635, -7320.7343,…\n$ NUM_CHILDCARE_350m       <dbl> 6344.3138, -3384.0445, 6344.3138, 961.6900, -…\n$ NUM_BUSSTOP_350m         <dbl> 6243.7006, 4240.3676, 6243.7006, -178.0258, 4…\n$ NUM_PRISCH_1km           <dbl> 2942.288, 7207.758, 2942.288, 3982.114, 7207.…\n$ y                        <dbl> 582000, 865000, 530000, 560000, 1038000, 5420…\n$ yhat                     <dbl> 588889.5, 913971.3, 588889.5, 565509.1, 92659…\n$ residual                 <dbl> -6889.486, -48971.257, -58889.486, -5509.078,…\n$ CV_Score                 <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ Stud_residual            <dbl> -0.18683766, -1.32042309, -1.59703834, -0.154…\n$ Intercept_SE             <dbl> 78856.57, 187053.37, 78856.57, 113161.84, 187…\n$ floor_area_sqm_SE        <dbl> 534.1438, 905.2493, 534.1438, 742.9723, 905.2…\n$ AGE_SE                   <dbl> 215.0936, 324.2352, 215.0936, 266.0645, 324.2…\n$ PROX_CBD_SE              <dbl> 7.273546, 18.849748, 7.273546, 10.921737, 18.…\n$ PROX_ELDERCARE_SE        <dbl> 13.99653, 27.80615, 13.99653, 19.37172, 27.80…\n$ PROX_HAWKER_SE           <dbl> 27.56241, 41.50247, 27.56241, 31.05549, 41.50…\n$ PROX_MRT_SE              <dbl> 26.76180, 34.47313, 26.76180, 21.71573, 34.47…\n$ PROX_PARK_SE             <dbl> 23.86578, 43.35742, 23.86578, 29.03234, 43.35…\n$ PROX_MALL_SE             <dbl> 22.09114, 29.25795, 22.09114, 21.51292, 29.25…\n$ PROX_GOOD_PRISCH_SE      <dbl> 11.69923, 23.38491, 11.69923, 16.33888, 23.38…\n$ NUM_KINDERGARTEN_350m_SE <dbl> 4350.414, 5663.054, 4350.414, 4084.900, 5663.…\n$ NUM_CHILDCARE_350m_SE    <dbl> 3418.413, 5049.762, 3418.413, 3126.176, 5049.…\n$ NUM_BUSSTOP_350m_SE      <dbl> 1652.221, 2414.869, 1652.221, 2032.367, 2414.…\n$ NUM_PRISCH_1km_SE        <dbl> 3461.811, 5170.667, 3461.811, 3396.960, 5170.…\n$ Intercept_TV             <dbl> 8.197950, 3.191428, 8.197950, 9.310304, 3.191…\n$ floor_area_sqm_TV        <dbl> 11.773605, 6.973190, 11.773605, 6.699923, 6.9…\n$ AGE_TV                   <dbl> -51.32837, -30.41937, -51.32837, -36.09317, -…\n$ PROX_CBD_TV              <dbl> -2.278576, -0.811857, -2.278576, -4.984044, -…\n$ PROX_ELDERCARE_TV        <dbl> 1.731357, 1.443263, 1.731357, 3.186014, 1.443…\n$ PROX_HAWKER_TV           <dbl> 0.85199864, 0.05503226, 0.85199864, 0.7896523…\n$ PROX_MRT_TV              <dbl> -0.6256643, 0.2131108, -0.6256643, -1.2268454…\n$ PROX_PARK_TV             <dbl> -1.883286635, -0.006416961, -1.883286635, -0.…\n$ PROX_MALL_TV             <dbl> -1.1104562, -1.4353492, -1.1104562, 0.2155327…\n$ PROX_GOOD_PRISCH_TV      <dbl> -2.2747382, -1.1389752, -2.2747382, 1.3424152…\n$ NUM_KINDERGARTEN_350m_TV <dbl> -1.56094660, 0.03909598, -1.56094660, -1.7921…\n$ NUM_CHILDCARE_350m_TV    <dbl> 1.8559237, -0.6701394, 1.8559237, 0.3076251, …\n$ NUM_BUSSTOP_350m_TV      <dbl> 3.77897418, 1.75594123, 3.77897418, -0.087595…\n$ NUM_PRISCH_1km_TV        <dbl> 0.8499274, 1.3939706, 0.8499274, 1.1722581, 1…\n$ Local_R2                 <dbl> 0.9358836, 0.9360192, 0.9358836, 0.9174594, 0…\n$ geometry                 <POINT [m]> POINT (30036.29 38360.76), POINT (29283…\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(gwr.adaptive$SDF$yhat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 399292  564868  632455  672391  727520 1393697 \n```\n\n\n:::\n:::\n\n\n\nThe GWR model predicts HDB prices ranging from \\$399k to \\$1.39M (mean: \\$672k). Compared to actual prices (\\$338k-\\$1.06M), the model tends to overpredict at the upper end, with the maximum predicted value exceeding the actual maximum by approximately \\$330k. This suggests the model may be overestimating prices for premium units, indicating potential areas for model refinement.\n\n#### **13.1.5 Visualising local R2**\n\nThe Local R² map reveals substantial spatial variation in model performance across Singapore.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(HDBresale.sf.adaptive$Local_R2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.0791  0.8590  0.9345  0.8684  0.9642  0.9881 \n```\n\n\n:::\n:::\n\n\n\nThe code chunks below is used to create an interactive point symbol map.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\ntm_shape(mpsz_svy21)+\n  tm_polygons(fill_alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(col = \"Local_R2\",\n          border.col = \"gray60\",\n          border.lwd = 1) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-74-1.png){width=672}\n:::\n:::\n\n\n\nThe Local R² map reveals that the GWR model performs well across Singapore, with most locations showing R² values exceeding 0.8, indicating strong local model fit throughout the study area.\n\n#### 13.1.6 **Visualising coefficient estimates**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(HDBresale.sf.adaptive$floor_area_sqm_SE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  143.9   591.0   894.3  2747.0  1716.5 96209.6 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(HDBresale.sf.adaptive$floor_area_sqm_TV)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n -2.905   1.885   3.872   4.388   5.982  39.303 \n```\n\n\n:::\n:::\n\n\n\nThe code chunks below is used to create an interactive point symbol map. If you want the interactive mode, change \"plot\" to \"view\".\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\nfloor_area_sqm_SE <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"floor_area_sqm_SE\",\n    palette = \"YlOrRd\",\n    style = \"quantile\",     \n    n = 5,\n    border.col = \"gray60\",\n    border.lwd = 0.5,\n    size = 0.5,\n    title = \"SE\") +\n  tm_view(set.zoom.limits = c(11,14))\n\nfloor_area_sqm_TV <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"floor_area_sqm_TV\",\n    palette = \"YlOrRd\",      \n    style = \"quantile\",       \n    n = 7,                    \n    border.col = \"gray60\",\n    border.lwd = 0.5,\n    size = 0.5,\n    title = \"t-value\")\n\ntmap_arrange(floor_area_sqm_SE, floor_area_sqm_TV, \n             asp = 1, ncol = 2, sync = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-76-1.png){width=672}\n:::\n:::\n\n\n\nFloor area sqm is more important in downtown areas, but its significance decreases further away from the downtown core.\n\n## 14. Spatial Variation in Coefficient Estimates\n\n### 14.1 Key Factors Influencing HDB Resale Prices\n\nThe global regression results (bottom table) reveal which factors significantly affect HDB prices across Singapore:\n\n![](images/clipboard-592210017.png){fig-align=\"center\" width=\"487\"}\n\n**Top 5 Most Influential Factors:**\n\n1.  **NUM_KINDERGARTEN_350m** (+9,054): Each kindergarten within 350m adds \\$9,054\n    -   Reflects strong family-oriented buyer demand\n2.  **AGE** (-6,864): Each year older reduces price by \\$6,864\n    -   Building depreciation is a major pricing factor\n3.  **floor_area_sqm** (+4,852): Each sqm adds \\$4,852\n    -   Space is highly valued across Singapore\n4.  **PROX_MRT** (-52): Each meter from MRT reduces \\$52\n    -   Transport accessibility matters significantly\n5.  **NUM_PRISCH_1km** (-3,147): More primary schools nearby reduces price\n    -   May reflect overcrowding or competition concerns\n\n**Other significant factors:** PROX_HAWKER (-31), PROX_CBD (-22), PROX_MALL (-15)\n\nAll factors are highly significant (p \\< 2e-16).\n\n### 14.2 Spatial Heterogeneity: Do These Effects Vary by Location?\n\nWhile these factors are important globally, the GWR coefficient summary reveals their influence varies dramatically across Singapore:\n\n![](images/clipboard-339446741.png){fig-align=\"center\" width=\"539\"}\n\n**Variables with Largest Spatial Variation:**\n\n1.  **NUM_KINDERGARTEN_350m** (Range: -387,960 to 4,984,700)\n    -   Highly valued in family estates, irrelevant or negative in areas with elderly residents or young professionals\n2.  **NUM_PRISCH_1km** (Range: -525,530 to 3,261,600)\n    -   Dramatic differences reflect varying education priorities and school quality perceptions across neighborhoods\n3.  **AGE** (Range: -152,740 to 30,462)\n    -   Stronger depreciation in mature estates; some newer developments show positive age effects (heritage value)\n4.  **PROX_MRT** (Range: -58,208 to 42,064)\n    -   Effects differ by car ownership rates and public transport dependency\n5.  **floor_area_sqm** (Range: -27,165 to 76,945)\n    -   Premium in dense urban areas; negative where maintenance costs outweigh space benefits\n\n**Key Insight:** The wide coefficient ranges confirm spatial non-stationarity, the same factor can have opposite effects in different locations. This validates the use of GWR over global regression.\n\n## 14.3 Spatial Distribution of Key Coefficients\n\n### 14.3.1 NUM_KINDERGARTEN_350m\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\nkindergarten_coef <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"NUM_KINDERGARTEN_350m\",\n    palette = \"YlOrRd\",\n    style = \"quantile\",\n    n = 6,\n    size = 0.2,\n    alpha = 0.7,\n    border.col = NA,\n    title = \"Coefficient\") +\n  tm_layout(\n    main.title = \"NUM_KINDERGARTEN_350m Coefficient\",\n    main.title.size = 1.2,\n    legend.position = c(\"right\", \"bottom\"), \n    legend.title.size = 0.8,\n    legend.text.size = 0.7,\n    legend.bg.color = \"white\",\n    legend.bg.alpha = 0.8,\n    frame = TRUE)\n\nkindergarten_coef\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-77-1.png){width=672}\n:::\n:::\n\n\n\nKindergarten density is most important in the northern and northeastern estates (dark red). Here, each new kindergarten adds more than \\$6,000 to the HDB prices. These new towns are designed with families in mind and are home to many young families. By contrast, central show lower coefficients (yellow).\n\n### 14.3.2 AGE\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\nage_coef <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"AGE\",\n    palette = \"YlOrRd\",\n    style = \"quantile\",\n    n = 6,\n    size = 0.2,\n    alpha = 0.7,\n    border.col = NA,\n    title = \"Coefficient\") +\n  tm_layout(\n    main.title = \"AGE Coefficient\",\n    main.title.size = 1.2,\n    legend.position = c(\"right\", \"bottom\"), \n    legend.title.size = 0.8,\n    legend.text.size = 0.7,\n    legend.bg.color = \"white\",\n    legend.bg.alpha = 0.8,\n    frame = TRUE)\n\nage_coef\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-78-1.png){width=672}\n:::\n:::\n\n\n\nThe effect of building depreciation is strongest in western and northern estates (dark red). In contrast, central and southeastern regions show weaker depreciation (yellow/light orange), suggesting that location advantages decrease age-related decline in these established neighborhoods.\n\n### 14.3.3 floor_area_sqm\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\narea_coef <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"floor_area_sqm\",\n    palette = \"YlOrRd\",\n    style = \"quantile\",\n    n = 6,\n    size = 0.2,\n    alpha = 0.7,\n    border.col = NA,\n    title = \"Coefficient\") +\n  tm_layout(\n    main.title = \"floor_area_sqm Coefficient\",\n    main.title.size = 1.2,\n    legend.position = c(\"right\", \"bottom\"), \n    legend.title.size = 0.8,\n    legend.text.size = 0.7,\n    legend.bg.color = \"white\",\n    legend.bg.alpha = 0.8,\n    frame = TRUE)\n\narea_coef\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-79-1.png){width=672}\n:::\n:::\n\n\n\nThe floor area coefficients are highest in central and eastern estates (dark red: up to \\$76,000 per sqm) and lowest in west-north regions (yellow: \\$2,000-3,000 per sqm).\n\n**Note**:\n\nThese differences in prices may show that people value space differently in different places, but they could also be affected by how houses are built. Town centres may have a wider range of house sizes, while new housing estates may have houses all built to the same plan. The differences in the coefficients need to be understood in relation to the local housing market.\n\n### 14.3.4 NUM_PRISCH_1km\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\nprisch_coef <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"NUM_PRISCH_1km\",\n    palette = \"YlOrRd\",\n    style = \"quantile\",\n    n = 6,\n    size = 0.2,\n    alpha = 0.7,\n    border.col = NA,\n    title = \"Coefficient\") +\n  tm_layout(\n    main.title = \"NUM_PRISCH_1km Coefficient\",\n    main.title.size = 1.2,\n    legend.position = c(\"right\", \"bottom\"), \n    legend.title.size = 0.8,\n    legend.text.size = 0.7,\n    legend.bg.color = \"white\",\n    legend.bg.alpha = 0.8,\n    frame = TRUE)\n\nprisch_coef\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-80-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\nprisch_coef <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"NUM_PRISCH_1km\",\n    palette = \"YlOrRd\",      \n    style = \"quantile\",\n    n = 6,\n    size = 0.2,\n    alpha = 0.7,\n    border.col = NA,\n    title = \"Coefficient\"\n  ) +\n  tm_layout(\n    main.title = \"NUM_PRISCH_1km Coefficient\",\n    main.title.size = 1.2,\n    legend.position = c(\"right\", \"bottom\"), \n    legend.title.size = 0.6,\n    legend.text.size = 0.5,\n    legend.bg.color = \"white\",\n    legend.bg.alpha = 0.8,\n    frame = TRUE\n  )\n\ngood_prisch_coef <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"PROX_GOOD_PRISCH\",\n    palette = \"-YlOrRd\",      \n    style = \"quantile\",\n    n = 6,\n    size = 0.2,\n    alpha = 0.7,\n    border.col = NA,\n    title = \"Coefficient\"\n  ) +\n  tm_layout(\n    main.title = \"PROX_GOOD_PRISCH Coefficient\",\n    main.title.size = 1.2,\n    legend.position = c(\"right\", \"bottom\"), \n    legend.title.size = 0.6,\n    legend.text.size = 0.5,\n    legend.bg.color = \"white\",\n    legend.bg.alpha = 0.8,\n    frame = TRUE\n  )\n\ntmap_arrange(prisch_coef, good_prisch_coef, \n             asp = 1, ncol = 2, sync = TRUE)\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-81-1.png){width=672}\n:::\n:::\n\n\n\n**Eastern market segments** (dark red on left, yellow on right) place premium value on educational diversity. Properties with multiple school options within 1km capture significantly higher prices, reflecting buyer demand for choice and accessibility. Elite school proximity adds minimal value in these areas—buyers optimize for resource abundance rather than institutional prestige.\n\n**Central and western markets** show opposite pricing dynamics (yellow-orange on left, dark red on right). High school density can depress values (likely due to overcrowding perceptions), while elite school access drives substantial price premiums. Properties near top-tier institutions command markups that justify premium positioning, demonstrating strong willingness-to-pay for educational brand value.\n\n**Note on Color Scheme:**\n\nThe color palettes are reversed between the two maps to ensure consistent interpretation:\n\n-   **NUM_PRISCH_1km** uses standard palette (red = high positive coefficients) because more schools = higher prices in these areas\n-   **PROX_GOOD_PRISCH** uses reversed palette (red = high negative coefficients) because shorter distance = higher prices in these areas\n\nThis ensures that **dark red consistently indicates high importance** across both maps, making spatial patterns directly comparable despite the different variable types (count vs. distance).\n\n### 14.3.5 PROX_MRT\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\nmrt_coef <- tm_shape(mpsz_svy21) +\n  tm_polygons(alpha = 0.1) +\ntm_shape(HDBresale.sf.adaptive) +  \n  tm_dots(\n    col = \"PROX_MRT\",\n    palette = \"-YlOrRd\",\n    style = \"quantile\",\n    n = 6,\n    size = 0.2,\n    alpha = 0.7,\n    border.col = NA,\n    title = \"Coefficient\") +\n  tm_layout(\n    main.title = \"PROX_MRT Coefficient\",\n    main.title.size = 1.2,\n    legend.position = c(\"right\", \"bottom\"), \n    legend.title.size = 0.8,\n    legend.text.size = 0.7,\n    legend.bg.color = \"white\",\n    legend.bg.alpha = 0.8,\n    frame = TRUE)\n\nmrt_coef\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise03_files/figure-html/unnamed-chunk-82-1.png){width=672}\n:::\n:::\n\n\n\n**Central and southeastern markets** (dark red: coefficients -\\$58,208 to -\\$159 per meter) show the strongest public transport dependency. MRT proximity commands substantial premiums in these mature, high-density areas where car-lite residents rely heavily on public transit. Properties within walking distance of stations capture significant accessibility value.\n\n**Northern and western regions** (yellow: minimal to positive coefficients) demonstrate limited MRT proximity effects. Higher car ownership rates in these developing estates mean buyers prioritize other amenities over station distance. Additionally, comprehensive MRT coverage in newer towns reduces the marginal value of being close to any single station when all properties have good access, proximity premium diminishes.\n\n## References\n\n### Data Sources\n\n**Singapore Government Open Data:**\n\n-   Data.gov.sg (2025). *HDB Resale Flat Prices*. Available at: <https://data.gov.sg/datasets/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/view>\n\n-   Data.gov.sg (2025). *Master Plan 2014 Subzone Boundary (Web)*. Available at: <https://data.gov.sg/datasets/d_d14da225fccf921049ab64238ff473d9/view>\n\n-   Data.gov.sg (2025). *General Information of Schools*. Available at: <https://data.gov.sg/datasets/d_688b934f82c1059ed0a6993d2a829089/view>\n\n-   Data.gov.sg (2025). *Eldercare Services*. Available at: <https://data.gov.sg/datasets/d_05279cf0148aadc5172ا462c28e0831ac/view>\n\n-   Data.gov.sg (2025). *Hawker Centres*. Available at: <https://data.gov.sg/datasets/d_4a086da0a5553be1d89383cd90d07ecd/view>\n\n-   Data.gov.sg (2025). *Parks*. Available at: <https://data.gov.sg/datasets/d_26071c850e144a8ba5160114c437d0c4/view>\n\n-   Data.gov.sg (2025). *Supermarkets*. Available at: <https://data.gov.sg/datasets/d_4a086da0a5553be1d89383cd90d07ecd/view>\n\n-   Data.gov.sg (2025). *CHAS Clinics*. Available at: <https://data.gov.sg/datasets/d_4762807ea792ffbc5dcf4d7d09290e5f/view>\n\n-   Data.gov.sg (2025). *Child Care Services*. Available at: <https://data.gov.sg/datasets/d_5835d718fbf67e2d45c914fc339e53d3/view>\n\n-   Data.gov.sg (2025). *Kindergartens*. Available at: <https://data.gov.sg/datasets/d_cc1c40bcf1b8fa9bef5ff6e1c7eb6afe/view>\n\n**LTA DataMall:**\n\n-   LTA DataMall (2025). *Train Station*. Available at: <https://datamall.lta.gov.sg/content/datamall/en/static-data.html>\n\n-   LTA DataMall (2025). *Bus Stops*. Available at: <https://datamall.lta.gov.sg/content/datamall/en/static-data.html>\n\n**Other Sources:**\n\n-   Wikipedia (2025). *List of Shopping Malls in Singapore*. Available at: <https://en.wikipedia.org/wiki/List_of_shopping_malls_in_Singapore>\n\n-   Local Salary Forum (2021). *Best Primary Schools 2021 by Popularity*. Available at: <https://www.salary.sg/2021/best-primary-schools-2021-by-popularity>\n\n-   OneMap API (2025). *Singapore Land Authority OneMap API*. Available at: <https://www.onemap.gov.sg/apidocs/>\n\n### R Packages\n\n-   Pebesma, E. (2018). Simple Features for R: Standardized Support for Spatial Vector Data. *The R Journal*, 10(1), 439-446. <https://cran.r-project.org/package=sf>\n\n-   Josiah Parry, Hadley Wickham (2023). sfdep: Spatial Dependence for Simple Features. <https://cran.r-project.org/package=sfdep>\n\n-   Gollini, I., Lu, B., Charlton, M., Brunsdon, C., & Harris, P. (2015). GWmodel: An R Package for Exploring Spatial Heterogeneity Using Geographically Weighted Models. *Journal of Statistical Software*, 63(17), 1-50. <https://cran.r-project.org/package=GWmodel>\n\n-   Tennekes, M. (2018). tmap: Thematic Maps in R. *Journal of Statistical Software*, 84(6), 1-39. <https://cran.r-project.org/package=tmap>\n\n-   Wickham, H., et al. (2019). Welcome to the tidyverse. *Journal of Open Source Software*, 4(43), 1686. <https://www.tidyverse.org/>\n\n-   Sjoberg, D. D., et al. (2021). Reproducible Summary Tables with the gtsummary Package. *The R Journal*, 13(1), 570-580. <https://cran.r-project.org/package=gtsummary>\n\n-   Lüdecke, D., et al. (2021). performance: An R Package for Assessment, Comparison and Testing of Statistical Models. *Journal of Open Source Software*, 6(60), 3139. <https://cran.r-project.org/package=performance>\n\n-   Wei, T. and Simko, V. (2021). corrplot: Visualization of a Correlation Matrix. <https://cran.r-project.org/package=corrplot>\n\n-   Kassambara, A. (2023). ggpubr: 'ggplot2' Based Publication Ready Plots. <https://cran.r-project.org/package=ggpubr>\n\n-   Neuwirth, E. (2022). RColorBrewer: ColorBrewer Palettes. <https://cran.r-project.org/package=RColorBrewer>\n\n-   Wickham, H. (2020). httr: Tools for Working with URLs and HTTP. <https://cran.r-project.org/package=httr>\n\n-   Ooms, J. (2014). The jsonlite Package: A Practical and Consistent Mapping Between JSON Data and R Objects. <https://cran.r-project.org/package=jsonlite>\n\n### Methodology References\n\n-   Fotheringham, A. S., Brunsdon, C., & Charlton, M. (2002). *Geographically Weighted Regression: The Analysis of Spatially Varying Relationships*. John Wiley & Sons.\n\n-   Tobler, W. R. (1970). A Computer Movie Simulating Urban Growth in the Detroit Region. *Economic Geography*, 46(sup1), 234-240.\n\n-   Anselin, L. (1995). Local Indicators of Spatial Association—LISA. *Geographical Analysis*, 27(2), 93-115.\n\n-   Prof.KAM <https://isss626-ay2025-26aug.netlify.app>\n",
    "supporting": [
      "Take-Home_Exercise03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}