project:
  type: website
  
execute:
  freeze: auto

website:
  title: "🐢ISSS626-Geospatial Analytics and Applications"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Exercise01.html"
          - text: "Hands-on Exercise 1-2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Exercise02.html"
          - text: "Hands-on Exercise 2-1"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Exercise04.html"
          - text: "Hands-on Exercise 2-2"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Exercise05.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Exercise06.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Exercise08.html"
          - text: "Hands-on Exercise 5-1"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Exercise09.html"
          - text: "Hands-on Exercise 5-2"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Exercise10.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex12/Hands-on_Exercise12.html"
          - text: "Hands-on Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex13/Hands-on_Exercise13.html"
          - text: "Hands-on Exercise 8"
            href: "Hands-on_Ex/Hands-on_Ex14/Hands-on_Exercise14.html"
          - text: "Hands-on Exercise 9"
            href: "Hands-on_Ex/Hands-on_Ex15/Hands-on_Exercise15.html"
          
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 3a"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03a.html"
          - text: "In-class Exercise 3b"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03b.html"
          - text: "In-class Exercise 04"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 05"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "In-class Exercise 06"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "In-class Exercise 07"
            href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
          - text: "In-class Exercise 08"
            href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
            
      - text: "Take-Home Exercise"
        menu:
          - text: "Take-Home Exercise 01"
            href: "Take-Home_Exercises/Take-Home_Exercise01/Take-Home_Exercise01.html"
          - text: "Take-Home Exercise 02"
            href: "Take-Home_Exercises/Take-Home_Exercise02/Take-Home_Exercise02.html"
           
          

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

