[build]
command = """
  QV=1.5.57
  mkdir -p /opt/buildhome/.qbin &&
  curl -L -o /opt/buildhome/.qbin/quarto.tgz \
    https://github.com/quarto-dev/quarto-cli/releases/download/v${QV}/quarto-${QV}-linux-amd64.tar.gz &&
  tar -xzf /opt/buildhome/.qbin/quarto.tgz -C /opt/buildhome/.qbin &&
  export PATH="/opt/buildhome/.qbin/quarto-${QV}/bin:$PATH" &&
  quarto --version &&
  quarto render
"""
publish = "_site"
