{
  "hash": "ab6957987859ed079ea2eb3cff6b806a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on_Exercise08: Spatial Weights and Applications\"\nauthor: \"BingBing\"\ndate: \"September 18, 2025\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n\n## **8.1 Overview**\n\nIn this hands-on exercise, you’ll learn how to compute spatial weights in R. By the end, you will be able to import geospatial data with the **sf** package, load CSV files with **readr**, perform relational joins using **dplyr**, construct spatial weight matrices with **spdep**, and compute spatially lagged variables using **spdep**.\n\n## **8.2 The Study Area and Data**\n\nTwo data sets will be used in this hands-on exercise, they are:\n\n-   Hunan county boundary layer. This is a geospatial data set in ESRI shapefile format.\n\n-   *Hunan_2012.csv*: This csv file contains selected Hunan’s local development indicators in 2012.\n\n### **8.2.1 Getting Started**\n\nBefore we get started, we need to ensure that **spdep**, **sf**, **tmap** and **tidyverse** packages of R are currently installed in your R.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse, knitr,DT)\n```\n:::\n\n\n\n## **8.3 Getting the Data Into R Environment**\n\nIn this section, you will learn how to bring a geospatial data and its associated attribute table into R environment. The geospatial data is in ESRI shapefile format and the attribute table is in csv fomat.\n\n### **8.3.1 Import shapefile into r environment**\n\nThe code chunk below uses [*st_read()*](https://r-spatial.github.io/sf/reference/st_read.html) of **sf** package to import Hunan shapefile into R. The imported shapefile will be **simple features** Object of **sf**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", \n                 layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Hands-on_Ex/Hands-on_Ex08/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n### **8.3.2 Import csv file into r environment**\n\nNext, we will import *Hunan_2012.csv* into R by using *read_csv()* of **readr** package. The output is R dataframe class.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n:::\n\n\n\n### **8.3.3 Performing relational join**\n\nThe code chunk below will be used to update the attribute table of *hunan*’s SpatialPolygonsDataFrame with the attribute fields of *hunan2012* dataframe. This is performed by using *left_join()* of **dplyr** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan,hunan2012) %>%\n  select(1:4, 7, 15)\n```\n:::\n\n\n\n## **8.4 Visualising Regional Development Indicator**\n\nNow, we are going to prepare a basemap and a choropleth map showing the distribution of GDPPC 2012 by using *qtm()* of **tmap** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbasemap <- tm_shape(hunan) +\n  tm_polygons() +\n  tm_text(\"NAME_3\", size=0.3)\n\ngdppc <- qtm(hunan, \"GDPPC\") +\n  tm_layout(\n    legend.position = c(\"left\", \"bottom\"))\ntmap_arrange(basemap, gdppc, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n## **8.5 Computing Contiguity Spatial Weights**\n\nThis section covers building contiguity-based spatial weights with `spdep::poly2nb()`. The function constructs a neighbor list by identifying polygons that touch. The `queen` argument controls the rule: `queen = TRUE` (the default) treats any shared point—edge or corner—as a neighbor (Queen contiguity), while `queen = FALSE` restricts neighbors to shared edges only (Rook contiguity). If you omit `queen`, the function returns first-order Queen neighbors.\n\n### **8.5.1 Computing (QUEEN) contiguity based neighbours**\n\nThe code chunk below is used to compute Queen contiguity weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, queen=TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n\nThe summary report above shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one heighbours.\n\nFor each polygon in our polygon object, *wm_q* lists all neighboring polygons. For example, to see the neighbors for the first polygon in the object, type:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  2  3  4 57 85\n```\n\n\n:::\n:::\n\n\n\nPolygon 1 has 5 neighbors. The numbers represent the polygon IDs as stored in hunan SpatialPolygonsDataFrame class.\n\nWe can retrive the county name of Polygon ID=1 by using the code chunk below:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan$County[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Anxiang\"\n```\n\n\n:::\n:::\n\n\n\nThe output reveals that Polygon ID=1 is Anxiang county.\n\nTo reveal the county names of the five neighboring polygons, the code chunk will be used:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan$NAME_3[c(2,3,4,57,85)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Hanshou\" \"Jinshi\"  \"Li\"      \"Nan\"     \"Taoyuan\"\n```\n\n\n:::\n:::\n\n\n\nWe can retrieve the GDPPC of these five countries by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb1 <- wm_q[[1]]\nnb1 <- hunan$GDPPC[nb1]\nnb1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 20981 34592 24473 21311 22879\n```\n\n\n:::\n:::\n\n\n\nThe printed output above shows that the GDPPC of the five nearest neighbours based on Queen’s method are 20981, 34592, 24473, 21311 and 22879 respectively.\n\nYou can display the complete weight matrix by using *str()*.\n\n\n\n\n\n\n\n### **8.5.2 Creating (ROOK) contiguity based neighbours**\n\nThe code chunk below is used to compute Rook contiguity weight matrix.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_r <- poly2nb(hunan, queen=FALSE)\nsummary(wm_r)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 440 \nPercentage nonzero weights: 5.681818 \nAverage number of links: 5 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 10 \n 2  2 12 20 21 14 11  3  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 10 links\n```\n\n\n:::\n:::\n\n\n\nThe summary report above shows that there are 88 area units in Hunan. The most connect area unit has 10 neighbours. There are two area units with only one heighbours.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!exists(\"deg\")) { wm_r <- spdep::poly2nb(hunan, queen = FALSE); deg <- spdep::card(wm_r) }\n\n#Fig 1: Distribution bar chart\ntb <- table(deg)\nbp <- barplot(tb,\n  ylim = c(0, max(tb) * 1.15),\n  col = \"#8DB9CA\", border = \"gray30\",\n  main = \"Distribution of neighbor counts\",\n  xlab = \"Neighbors per region\", ylab = \"Number of regions\"\n)\ntext(bp, as.numeric(tb), labels = as.numeric(tb), pos = 3, cex = 0.9)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#Fig 2: Map colored by neighbors\nhunan$neighbors <- deg\nplot(hunan[\"neighbors\"], main = \"Neighbors per region (Rook)\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#Fig 3: Top / Bottom regions\nlab <- if (\"NAME_3\" %in% names(hunan)) hunan$NAME_3 else seq_along(deg)\no   <- order(deg)\nsel <- c(tail(o, 12), head(o, 12)) \n\nop <- par(no.readonly = TRUE)\npar(mar = c(4, 8, 3, 1), lheight = 1.25)  \ndotchart(deg[sel],\n  labels = lab[sel],\n  main   = \"Top / Bottom by neighbors\",\n  xlab   = \"Neighbors\", cex = 0.85, pch = 21)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-13-3.png){width=672}\n:::\n\n```{.r .cell-code}\npar(op)\n```\n:::\n\n\n\n### **8.5.3 Visualising contiguity weights**\n\nA connectivity graph takes a point and displays a line to each neighboring point. We are working with polygons at the moment, so we will need to get points in order to make our connectivity graphs. The most typically method for this will be polygon centroids. We will calculate these in the sf package before moving onto the graphs. Getting Latitude and Longitude of Polygon Centroids\n\nWe will need points to associate with each polygon before we can make our connectivity graph. It will be a little more complicated than just running st_centroid on the sf object: us.bound. We need the coordinates in a separate data frame for this to work. To do this we will use a mapping function. The mapping function applies a given function to each element of a vector and returns a vector of the same length. Our input vector will be the geometry column of us.bound. Our function will be st_centroid. We will be using map_dbl variation of map from the purrr package. For more documentation, check out map documentation\n\nTo get our longitude values we map the st_centroid function over the geometry column of us.bound and access the longitude value through double bracket notation \\[\\[\\]\\] and 1. This allows us to get only the longitude, which is the first value in each centroid.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlongitude <- map_dbl(hunan$geometry, ~st_centroid(.x)[[1]])\n```\n:::\n\n\n\nWe do the same for latitude with one key difference. We access the second value per each centroid with \\[\\[2\\]\\].\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlatitude <- map_dbl(hunan$geometry, ~st_centroid(.x)[[2]])\n```\n:::\n\n\n\nNow that we have latitude and longitude, we use cbind to put longitude and latitude into the same object.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- cbind(longitude, latitude)\n```\n:::\n\n\n\nWe check the first few observations to see if things are formatted correctly.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(coords)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     longitude latitude\n[1,]  112.1531 29.44362\n[2,]  112.0372 28.86489\n[3,]  111.8917 29.47107\n[4,]  111.7031 29.74499\n[5,]  111.6138 29.49258\n[6,]  111.0341 29.79863\n```\n\n\n:::\n:::\n\n\n\n#### 8.5.3.1 Plotting Queen contiguity based neighbours map\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hunan$geometry, border=\"lightgrey\")\nplot(wm_q, coords, pch = 19, cex = 1, add = TRUE, col= \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-18-1.png){width=1440}\n:::\n:::\n\n\n\n#### 8.5.3.2 Plotting Rook contiguity based neighbours map\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hunan$geometry, border=\"lightgrey\")\nplot(wm_r, coords, pch = 19, cex = 1, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-19-1.png){width=1440}\n:::\n:::\n\n\n\n#### 8.5.3.3 Plotting both Queen and Rook contiguity based neighbours maps\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2))\nplot(hunan$geometry, border=\"lightgrey\", main=\"Queen Contiguity\")\nplot(wm_q, coords, pch = 19, cex = 0.3, add = TRUE, col= \"red\")\nplot(hunan$geometry, border=\"lightgrey\", main=\"Rook Contiguity\")\nplot(wm_r, coords, pch = 19, cex = 0.3, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n## **8.6 Computing distance based neighbours**\n\nIn this section, you will learn how to derive distance-based weight matrices by using [*dnearneigh()*](https://r-spatial.github.io/spdep/reference/dnearneigh.html) of **spdep** package.\n\nThe function identifies neighbours of region points by Euclidean distance with a distance band with lower d1= and upper d2= bounds controlled by the bounds= argument. If unprojected coordinates are used and either specified in the coordinates object x or with x as a two column matrix and longlat=TRUE, great circle distances in **km** will be calculated assuming the WGS84 reference ellipsoid.\n\n### **8.6.1 Determine the cut-off distance**\n\nFirstly, we need to determine the upper limit for distance band by using the steps below:\n\n-   Return a matrix with the indices of points belonging to the set of the k nearest neighbours of each other by using [*knearneigh()*](https://r-spatial.github.io/spdep/reference/knearneigh.html) of **spdep**.\n\n-   Convert the knn object returned by *knearneigh()* into a neighbours list of class nb with a list of integer vectors containing neighbour region number ids by using [*knn2nb()*](https://r-spatial.github.io/spdep/reference/knn2nb.html).\n\n-   Return the length of neighbour relationship edges by using [*nbdists()*](https://r-spatial.github.io/spdep/reference/nbdists.html) of **spdep**. The function returns in the units of the coordinates if the coordinates are projected, in km otherwise.\n\n-   Remove the list structure of the returned object by using [**unlist()**](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/unlist).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#coords <- coordinates(hunan)\nk1 <- knn2nb(knearneigh(coords))\nk1dists <- unlist(nbdists(k1, coords, longlat = TRUE))\nsummary(k1dists)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  24.79   32.57   38.01   39.07   44.52   61.79 \n```\n\n\n:::\n:::\n\n\n\nThe summary report shows that the largest first nearest neighbour distance is 61.79 km, so using this as the upper threshold gives certainty that all units will have at least one neighbour.\n\n### **8.6.2 Computing fixed distance weight matrix**\n\nNow, we will compute the distance weight matrix by using *dnearneigh()* as shown in the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_d62 <- dnearneigh(coords, 0, 62, longlat = TRUE)\nwm_d62\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 324 \nPercentage nonzero weights: 4.183884 \nAverage number of links: 3.681818 \n```\n\n\n:::\n:::\n\n\n\n**Quiz:** What is the meaning of “Average number of links: 3.681818” shown above?\\\n**Answer:** “Average number of links: 3.681818” means that, each region has on average 3.68 neighbors within 62 km.\n\nNext, we will use *str()* to display the content of wm_d62 weight matrix.\n\n\n\n\n\n\n\nAnother way to display the structure of the weight matrix is to combine [*table()*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/table) and [*card()*](https://r-spatial.github.io/spdep/reference/card.html) of spdep.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_comp <- n.comp.nb(wm_d62)\nn_comp$nc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(n_comp$comp.id)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 1 \n88 \n```\n\n\n:::\n:::\n\n\n\n#### 8.6.2.1 Plotting fixed distance weight matrix\n\nNext, we will plot the distance weight matrix by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hunan$geometry, border=\"lightgrey\")\nplot(wm_d62, coords, add=TRUE)\nplot(k1, coords, add=TRUE, col=\"red\", length=0.08)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-27-1.png){width=1440}\n:::\n:::\n\n\n\nThe red lines show the links of 1st nearest neighbours and the black lines show the links of neighbours within the cut-off distance of 62km.\n\nAlternatively, we can plot both of them next to each other by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1,2))\nplot(hunan$geometry, border=\"lightgrey\", main=\"1st nearest neighbours\")\nplot(k1, coords, add=TRUE, col=\"red\", length=0.08)\nplot(hunan$geometry, border=\"lightgrey\", main=\"Distance link\")\nplot(wm_d62, coords, add=TRUE, pch = 19, cex = 0.6)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n:::\n\n\n\n### **8.6.3 Computing adaptive distance weight matrix**\n\nOne of the characteristics of fixed distance weight matrix is that more densely settled areas (usually the urban areas) tend to have more neighbours and the less densely settled areas (usually the rural counties) tend to have lesser neighbours. Having many neighbours smoothes the neighbour relationship across more neighbours.\n\nIt is possible to control the numbers of neighbours directly using k-nearest neighbours, either accepting asymmetric neighbours or imposing symmetry as shown in the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn6 <- knn2nb(knearneigh(coords, k=6))\nknn6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 528 \nPercentage nonzero weights: 6.818182 \nAverage number of links: 6 \nNon-symmetric neighbours list\n```\n\n\n:::\n:::\n\n\n\nSimilarly, we can display the content of the matrix by using *str()*.\n\n\n\n\n\n\n\nNotice that each county has six neighbours, no less no more!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnm <- if (\"NAME_3\" %in% names(hunan)) as.character(hunan$NAME_3) else as.character(seq_len(nrow(hunan)))\ndeg <- spdep::card(knn6)\nedges <- do.call(rbind, lapply(seq_along(knn6), function(i) {\n  if (length(knn6[[i]]) == 0) return(NULL)\n  cbind(from = i, to = knn6[[i]])\n}))\nedges <- as.data.frame(edges)\nedges$from_name <- nm[edges$from]\nedges$to_name   <- nm[edges$to]\nneighbor_tbl <- aggregate(to_name ~ from_name, data = edges, FUN = function(v) paste(sort(unique(v)), collapse = \", \"))\nneighbor_tbl$neighbors_n <- deg[match(neighbor_tbl$from_name, nm)]\nneighbor_tbl <- neighbor_tbl[order(-neighbor_tbl$neighbors_n, neighbor_tbl$from_name), ]\nnames(neighbor_tbl) <- c(\"county\", \"neighbors\", \"n_neighbors\")\n\nhead(neighbor_tbl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     county                                                    neighbors\n1     Anhua Lengshuijiang, Lianyuan, Taojiang, Taoyuan, Xinhua, Yuanling\n2     Anren           Chaling, Hengdong, Leiyang, Yanling, Yongxing, You\n3   Anxiang                     Hanshou, Huarong, Jinshi, Li, Linli, Nan\n4   Baojing      Fenghuang, Guzhang, Huayuan, Jishou, Longshan, Yongshun\n5   Chaling             Anren, Hengdong, Leiyang, Yanling, Yongxing, You\n6 Changning           Guiyang, Hengnan, Leiyang, Qidong, Qiyang, Xintian\n  n_neighbors\n1           6\n2           6\n3           6\n4           6\n5           6\n6           6\n```\n\n\n:::\n\n```{.r .cell-code}\nif (requireNamespace(\"DT\", quietly = TRUE)) {\n  DT::datatable(neighbor_tbl, rownames = FALSE,\n                options = list(pageLength = 12, dom = \"tip\"),\n                caption = \"Each county and its neighbors\")}\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-d44c5e4c0b37a24e2403\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d44c5e4c0b37a24e2403\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"caption\":\"<caption>Each county and its neighbors<\\/caption>\",\"data\":[[\"Anhua\",\"Anren\",\"Anxiang\",\"Baojing\",\"Chaling\",\"Changning\",\"Changsha\",\"Chengbu\",\"Chenxi\",\"Cili\",\"Dao\",\"Dongan\",\"Dongkou\",\"Fenghuang\",\"Guidong\",\"Guiyang\",\"Guzhang\",\"Hanshou\",\"Hengdong\",\"Hengnan\",\"Hengshan\",\"Hengyang\",\"Hongjiang\",\"Huarong\",\"Huayuan\",\"Huitong\",\"Jiahe\",\"Jianghua\",\"Jiangyong\",\"Jingzhou\",\"Jinshi\",\"Jishou\",\"Lanshan\",\"Leiyang\",\"Lengshuijiang\",\"Li\",\"Lianyuan\",\"Liling\",\"Linli\",\"Linwu\",\"Linxiang\",\"Liuyang\",\"Longhui\",\"Longshan\",\"Luxi\",\"Mayang\",\"Miluo\",\"Nan\",\"Ningxiang\",\"Ningyuan\",\"Pingjiang\",\"Qidong\",\"Qiyang\",\"Rucheng\",\"Sangzhi\",\"Shaodong\",\"Shaoshan\",\"Shaoyang\",\"Shimen\",\"Shuangfeng\",\"Shuangpai\",\"Suining\",\"Taojiang\",\"Taoyuan\",\"Tongdao\",\"Wangcheng\",\"Wugang\",\"Xiangtan\",\"Xiangxiang\",\"Xiangyin\",\"Xinhua\",\"Xinhuang\",\"Xinning\",\"Xinshao\",\"Xintian\",\"Xupu\",\"Yanling\",\"Yizhang\",\"Yongshun\",\"Yongxing\",\"You\",\"Yuanjiang\",\"Yuanling\",\"Yueyang\",\"Zhijiang\",\"Zhongfang\",\"Zhuzhou\",\"Zixing\"],[\"Lengshuijiang, Lianyuan, Taojiang, Taoyuan, Xinhua, Yuanling\",\"Chaling, Hengdong, Leiyang, Yanling, Yongxing, You\",\"Hanshou, Huarong, Jinshi, Li, Linli, Nan\",\"Fenghuang, Guzhang, Huayuan, Jishou, Longshan, Yongshun\",\"Anren, Hengdong, Leiyang, Yanling, Yongxing, You\",\"Guiyang, Hengnan, Leiyang, Qidong, Qiyang, Xintian\",\"Liling, Liuyang, Miluo, Wangcheng, Xiangyin, Zhuzhou\",\"Huitong, Jingzhou, Suining, Tongdao, Wugang, Xinning\",\"Hongjiang, Jishou, Luxi, Mayang, Xupu, Zhongfang\",\"Li, Linli, Sangzhi, Shimen, Taoyuan, Yuanling\",\"Jianghua, Jiangyong, Lanshan, Ningyuan, Shuangpai, Xintian\",\"Qidong, Qiyang, Shaoyang, Shuangpai, Wugang, Xinning\",\"Hongjiang, Longhui, Suining, Wugang, Xinning, Zhongfang\",\"Baojing, Huayuan, Jishou, Luxi, Mayang, Zhijiang\",\"Anren, Chaling, Rucheng, Yanling, Yongxing, Zixing\",\"Jiahe, Leiyang, Linwu, Xintian, Yizhang, Yongxing\",\"Baojing, Huayuan, Jishou, Luxi, Yongshun, Yuanling\",\"Anxiang, Jinshi, Nan, Taojiang, Taoyuan, Yuanjiang\",\"Anren, Hengnan, Hengshan, Hengyang, You, Zhuzhou\",\"Changning, Hengdong, Hengshan, Hengyang, Leiyang, Qidong\",\"Hengdong, Hengnan, Hengyang, Shuangfeng, Xiangtan, Zhuzhou\",\"Hengdong, Hengnan, Hengshan, Qidong, Shaodong, Shuangfeng\",\"Dongkou, Huitong, Mayang, Suining, Zhijiang, Zhongfang\",\"Anxiang, Jinshi, Nan, Xiangyin, Yuanjiang, Yueyang\",\"Baojing, Fenghuang, Guzhang, Jishou, Luxi, Mayang\",\"Hongjiang, Jingzhou, Suining, Tongdao, Zhijiang, Zhongfang\",\"Guiyang, Lanshan, Linwu, Ningyuan, Xintian, Yizhang\",\"Dao, Jiahe, Jiangyong, Lanshan, Linwu, Ningyuan\",\"Dao, Jianghua, Lanshan, Ningyuan, Shuangpai, Xintian\",\"Chengbu, Hongjiang, Huitong, Suining, Tongdao, Xinhuang\",\"Anxiang, Hanshou, Li, Linli, Nan, Taoyuan\",\"Baojing, Fenghuang, Guzhang, Huayuan, Luxi, Mayang\",\"Dao, Jiahe, Jianghua, Linwu, Ningyuan, Xintian\",\"Anren, Changning, Guiyang, Hengdong, Hengnan, Yongxing\",\"Anhua, Lianyuan, Longhui, Shaodong, Xinhua, Xinshao\",\"Anxiang, Cili, Jinshi, Linli, Shimen, Taoyuan\",\"Lengshuijiang, Shaodong, Shuangfeng, Xiangxiang, Xinhua, Xinshao\",\"Changsha, Hengdong, Liuyang, Xiangtan, You, Zhuzhou\",\"Anxiang, Cili, Jinshi, Li, Shimen, Taoyuan\",\"Guiyang, Jiahe, Lanshan, Ningyuan, Xintian, Yizhang\",\"Huarong, Miluo, Pingjiang, Xiangyin, Yuanjiang, Yueyang\",\"Changsha, Liling, Miluo, Pingjiang, Wangcheng, Zhuzhou\",\"Dongkou, Shaoyang, Wugang, Xinhua, Xinshao, Xupu\",\"Baojing, Guzhang, Huayuan, Jishou, Sangzhi, Yongshun\",\"Chenxi, Fenghuang, Guzhang, Huayuan, Jishou, Mayang\",\"Chenxi, Fenghuang, Jishou, Luxi, Zhijiang, Zhongfang\",\"Changsha, Pingjiang, Wangcheng, Xiangyin, Yuanjiang, Yueyang\",\"Anxiang, Hanshou, Huarong, Jinshi, Xiangyin, Yuanjiang\",\"Lianyuan, Shaoshan, Taojiang, Wangcheng, Xiangtan, Xiangxiang\",\"Dao, Jiahe, Lanshan, Linwu, Shuangpai, Xintian\",\"Changsha, Linxiang, Liuyang, Miluo, Xiangyin, Yueyang\",\"Changning, Hengnan, Hengyang, Qiyang, Shaodong, Shaoyang\",\"Changning, Dongan, Ningyuan, Qidong, Shuangpai, Xintian\",\"Guidong, Guiyang, Yanling, Yizhang, Yongxing, Zixing\",\"Cili, Guzhang, Longshan, Shimen, Yongshun, Yuanling\",\"Hengyang, Lianyuan, Qidong, Shaoyang, Shuangfeng, Xinshao\",\"Ningxiang, Shuangfeng, Taojiang, Wangcheng, Xiangtan, Xiangxiang\",\"Dongan, Longhui, Shaodong, Wugang, Xinning, Xinshao\",\"Cili, Jinshi, Li, Linli, Sangzhi, Taoyuan\",\"Hengshan, Hengyang, Lianyuan, Shaodong, Shaoshan, Xiangxiang\",\"Dao, Dongan, Jiahe, Ningyuan, Qiyang, Xintian\",\"Chengbu, Dongkou, Hongjiang, Huitong, Jingzhou, Wugang\",\"Hanshou, Ningxiang, Shaoshan, Wangcheng, Xiangyin, Yuanjiang\",\"Anhua, Cili, Hanshou, Jinshi, Li, Linli\",\"Chengbu, Hongjiang, Huitong, Jingzhou, Suining, Wugang\",\"Changsha, Miluo, Ningxiang, Shaoshan, Xiangtan, Xiangyin\",\"Chengbu, Dongkou, Longhui, Shaoyang, Suining, Xinning\",\"Hengshan, Ningxiang, Shaoshan, Wangcheng, Xiangxiang, Zhuzhou\",\"Hengshan, Lianyuan, Ningxiang, Shaoshan, Shuangfeng, Xiangtan\",\"Changsha, Miluo, Nan, Taojiang, Wangcheng, Yuanjiang\",\"Anhua, Lengshuijiang, Lianyuan, Longhui, Xinshao, Xupu\",\"Fenghuang, Hongjiang, Huitong, Jingzhou, Mayang, Zhijiang\",\"Chengbu, Dongan, Dongkou, Shaoyang, Suining, Wugang\",\"Lengshuijiang, Lianyuan, Longhui, Shaodong, Shaoyang, Xinhua\",\"Changning, Guiyang, Jiahe, Lanshan, Ningyuan, Shuangpai\",\"Chenxi, Dongkou, Longhui, Luxi, Xinhua, Zhongfang\",\"Anren, Chaling, Guidong, Rucheng, Yongxing, Zixing\",\"Guiyang, Jiahe, Lanshan, Linwu, Rucheng, Zixing\",\"Baojing, Guzhang, Jishou, Longshan, Sangzhi, Yuanling\",\"Anren, Guidong, Guiyang, Leiyang, Yanling, Zixing\",\"Anren, Chaling, Hengdong, Hengshan, Liling, Zhuzhou\",\"Hanshou, Huarong, Miluo, Nan, Taojiang, Xiangyin\",\"Anhua, Chenxi, Guzhang, Luxi, Xupu, Yongshun\",\"Huarong, Linxiang, Miluo, Pingjiang, Xiangyin, Yuanjiang\",\"Fenghuang, Hongjiang, Huitong, Mayang, Xinhuang, Zhongfang\",\"Chenxi, Hongjiang, Luxi, Mayang, Xupu, Zhijiang\",\"Changsha, Hengdong, Hengshan, Liling, Xiangtan, You\",\"Anren, Guidong, Guiyang, Rucheng, Yanling, Yongxing\"],[6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>county<\\/th>\\n      <th>neighbors<\\/th>\\n      <th>n_neighbors<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":12,\"dom\":\"tip\",\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":2},{\"name\":\"county\",\"targets\":0},{\"name\":\"neighbors\",\"targets\":1},{\"name\":\"n_neighbors\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[10,12,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### 8.6.3.1 Plotting distance based neighbours\n\nWe can plot the weight matrix using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hunan$geometry, border=\"lightgrey\")\nplot(knn6, coords, pch = 19, cex = 0.6, add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-32-1.png){width=1440}\n:::\n:::\n\n\n\n## **8.7 Weights based on IDW**\n\nIn this section, you will learn how to derive a spatial weight matrix based on Inversed Distance method.\n\nFirst, we will compute the distances between areas by using [*nbdists()*](https://r-spatial.github.io/spdep/reference/nbdists.html) of **spdep**.\n\n\n\n\n\n\n\n## **8.8 Row-standardised Weights Matrix**\n\nNext, we need to assign weights to each neighboring polygon. In our case, each neighboring polygon will be assigned equal weight (style=“W”). This is accomplished by assigning the fraction 1/(#ofneighbors) to each neighboring county then summing the weighted income values. While this is the most intuitive way to summaries the neighbors’ values it has one drawback in that polygons along the edges of the study area will base their lagged values on fewer polygons thus potentially over- or under-estimating the true nature of the spatial autocorrelation in the data. For this example, we’ll stick with the style=“W” option for simplicity’s sake but note that other more robust options are available, notably style=“B”.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, style=\"W\", zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\n\nThe zero.policy=TRUE option allows for lists of non-neighbors. This should be used with caution since the user may not be aware of missing neighbors in their dataset however, a zero.policy of FALSE would return an error.\n\nTo see the weight of the first polygon’s eight neighbors type:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q$weights[10]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125\n```\n\n\n:::\n:::\n\n\n\nEach neighbor is assigned a 0.125 of the total weight. This means that when R computes the average neighboring income values, each neighbor’s income will be multiplied by 0.125 before being tallied.\n\nUsing the same method, we can also derive a row standardised distance weight matrix by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_ids <- nb2listw(wm_q, glist=ids, style=\"B\", zero.policy=TRUE)\nrswm_ids\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: B \nWeights constants summary:\n   n   nn       S0        S1     S2\nB 88 7744 8.786867 0.3776535 3.8137\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_ids$weights[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 0.01535405 0.03916350 0.01820896 0.02807922 0.01145113\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(unlist(rswm_ids$weights))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n0.008218 0.015088 0.018739 0.019614 0.022823 0.040338 \n```\n\n\n:::\n:::\n\n\n\n## **8.9 Application of Spatial Weight Matrix**\n\nIn this section, you will learn how to create four different spatial lagged variables, they are:\n\n-   spatial lag with row-standardized weights,\n\n-   spatial lag as a sum of neighbouring values,\n\n-   spatial window average, and\n\n-   spatial window sum.\n\n### **8.9.1 Spatial lag with row-standardized weights**\n\nFinally, we’ll compute the average neighbor GDPPC value for each polygon. These values are often referred to as **spatially lagged values**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGDPPC.lag <- lag.listw(rswm_q, hunan$GDPPC)\nGDPPC.lag\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 24847.20 22724.80 24143.25 27737.50 27270.25 21248.80 43747.00 33582.71\n [9] 45651.17 32027.62 32671.00 20810.00 25711.50 30672.33 33457.75 31689.20\n[17] 20269.00 23901.60 25126.17 21903.43 22718.60 25918.80 20307.00 20023.80\n[25] 16576.80 18667.00 14394.67 19848.80 15516.33 20518.00 17572.00 15200.12\n[33] 18413.80 14419.33 24094.50 22019.83 12923.50 14756.00 13869.80 12296.67\n[41] 15775.17 14382.86 11566.33 13199.50 23412.00 39541.00 36186.60 16559.60\n[49] 20772.50 19471.20 19827.33 15466.80 12925.67 18577.17 14943.00 24913.00\n[57] 25093.00 24428.80 17003.00 21143.75 20435.00 17131.33 24569.75 23835.50\n[65] 26360.00 47383.40 55157.75 37058.00 21546.67 23348.67 42323.67 28938.60\n[73] 25880.80 47345.67 18711.33 29087.29 20748.29 35933.71 15439.71 29787.50\n[81] 18145.00 21617.00 29203.89 41363.67 22259.09 44939.56 16902.00 16930.00\n```\n\n\n:::\n:::\n\n\n\nRecalled in the previous section, we retrieved the GDPPC of these five countries by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb1 <- wm_q[[1]]\nnb1 <- hunan$GDPPC[nb1]\nlag_rowstd <- mean(nb1)\ncat(\"Neighbors' values:\", paste(nb1, collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbors' values: 20981, 34592, 24473, 21311, 22879 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Count of neighbors:\", length(nb1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCount of neighbors: 5 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Sum of neighbors:\", sum(nb1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSum of neighbors: 124236 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Spatial lag (row-standardized) = average of neighbors:\",\n    round(lag_rowstd, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial lag (row-standardized) = average of neighbors: 24847.2 \n```\n\n\n:::\n:::\n\n\n\n> **Question:** Can you see the meaning of Spatial lag with row-standardized weights now?\n>\n> **Answer:** With row-standardized weights, spatial lag = the average of a region’s neighbors’ values.\n\nWe can append the spatially lag GDPPC values onto hunan sf data frame by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlag.list <- list(hunan$NAME_3, lag.listw(rswm_q, hunan$GDPPC))\nlag.res <- as.data.frame(lag.list)\ncolnames(lag.res) <- c(\"NAME_3\", \"lag GDPPC\")\nhunan <- left_join(hunan,lag.res)\n```\n:::\n\n\n\nThe following table shows the average neighboring income values (stored in the Inc.lag object) for each county.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 8 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 110.4922 ymin: 28.61762 xmax: 112.3013 ymax: 30.12812\nGeodetic CRS:  WGS 84\n   NAME_2  ID_3  NAME_3   ENGTYPE_3  County GDPPC neighbors lag GDPPC\n1 Changde 21098 Anxiang      County Anxiang 23667         4  24847.20\n2 Changde 21100 Hanshou      County Hanshou 20981         4  22724.80\n3 Changde 21101  Jinshi County City  Jinshi 34592         4  24143.25\n4 Changde 21102      Li      County      Li 24473         4  27737.50\n5 Changde 21103   Linli      County   Linli 25554         4  27270.25\n6 Changde 21104  Shimen      County  Shimen 27137         5  21248.80\n                        geometry\n1 POLYGON ((112.0625 29.75523...\n2 POLYGON ((112.2288 29.11684...\n3 POLYGON ((111.8927 29.6013,...\n4 POLYGON ((111.3731 29.94649...\n5 POLYGON ((111.6324 29.76288...\n6 POLYGON ((110.8825 30.11675...\n```\n\n\n:::\n:::\n\n\n\nNext, we will plot both the GDPPC and spatial lag GDPPC for comparison using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngdppc <- qtm(hunan, \"GDPPC\")\nlag_gdppc <- qtm(hunan, \"lag GDPPC\")\ntmap_arrange(gdppc, lag_gdppc, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n\n### **8.9.2 Spatial lag as a sum of neighboring values**\n\nWe can calculate spatial lag as a sum of neighboring values by assigning binary weights. This requires us to go back to our neighbors list, then apply a function that will assign binary weights, then we use glist = in the nb2listw function to explicitly assign these weights.\n\nWe start by applying a function that will assign a value of 1 per each neighbor. This is done with lapply, which we have been using to manipulate the neighbors structure throughout the past notebooks. Basically it applies a function across each value in the neighbors structure.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_weights <- lapply(wm_q, function(x) 0*x + 1)\nb_weights2 <- nb2listw(wm_q, \n                       glist = b_weights, \n                       style = \"B\")\nb_weights2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: B \nWeights constants summary:\n   n   nn  S0  S1    S2\nB 88 7744 448 896 10224\n```\n\n\n:::\n:::\n\n\n\nWith the proper weights assigned, we can use lag.listw to compute a lag variable from our weight and GDPPC.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlag_sum <- list(hunan$NAME_3, lag.listw(b_weights2, hunan$GDPPC))\nlag.res <- as.data.frame(lag_sum)\ncolnames(lag.res) <- c(\"NAME_3\", \"lag_sum GDPPC\")\n```\n:::\n\n\n\nFirst, let us examine the result by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlag_sum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] \"Anxiang\"       \"Hanshou\"       \"Jinshi\"        \"Li\"           \n [5] \"Linli\"         \"Shimen\"        \"Liuyang\"       \"Ningxiang\"    \n [9] \"Wangcheng\"     \"Anren\"         \"Guidong\"       \"Jiahe\"        \n[13] \"Linwu\"         \"Rucheng\"       \"Yizhang\"       \"Yongxing\"     \n[17] \"Zixing\"        \"Changning\"     \"Hengdong\"      \"Hengnan\"      \n[21] \"Hengshan\"      \"Leiyang\"       \"Qidong\"        \"Chenxi\"       \n[25] \"Zhongfang\"     \"Huitong\"       \"Jingzhou\"      \"Mayang\"       \n[29] \"Tongdao\"       \"Xinhuang\"      \"Xupu\"          \"Yuanling\"     \n[33] \"Zhijiang\"      \"Lengshuijiang\" \"Shuangfeng\"    \"Xinhua\"       \n[37] \"Chengbu\"       \"Dongan\"        \"Dongkou\"       \"Longhui\"      \n[41] \"Shaodong\"      \"Suining\"       \"Wugang\"        \"Xinning\"      \n[45] \"Xinshao\"       \"Shaoshan\"      \"Xiangxiang\"    \"Baojing\"      \n[49] \"Fenghuang\"     \"Guzhang\"       \"Huayuan\"       \"Jishou\"       \n[53] \"Longshan\"      \"Luxi\"          \"Yongshun\"      \"Anhua\"        \n[57] \"Nan\"           \"Yuanjiang\"     \"Jianghua\"      \"Lanshan\"      \n[61] \"Ningyuan\"      \"Shuangpai\"     \"Xintian\"       \"Huarong\"      \n[65] \"Linxiang\"      \"Miluo\"         \"Pingjiang\"     \"Xiangyin\"     \n[69] \"Cili\"          \"Chaling\"       \"Liling\"        \"Yanling\"      \n[73] \"You\"           \"Zhuzhou\"       \"Sangzhi\"       \"Yueyang\"      \n[77] \"Qiyang\"        \"Taojiang\"      \"Shaoyang\"      \"Lianyuan\"     \n[81] \"Hongjiang\"     \"Hengyang\"      \"Guiyang\"       \"Changsha\"     \n[85] \"Taoyuan\"       \"Xiangtan\"      \"Dao\"           \"Jiangyong\"    \n\n[[2]]\n [1] 124236 113624  96573 110950 109081 106244 174988 235079 273907 256221\n[11]  98013 104050 102846  92017 133831 158446 141883 119508 150757 153324\n[21] 113593 129594 142149 100119  82884  74668  43184  99244  46549  20518\n[31] 140576 121601  92069  43258 144567 132119  51694  59024  69349  73780\n[41]  94651 100680  69398  52798 140472 118623 180933  82798  83090  97356\n[51]  59482  77334  38777 111463  74715 174391 150558 122144  68012  84575\n[61] 143045  51394  98279  47671  26360 236917 220631 185290  64640  70046\n[71] 126971 144693 129404 284074 112268 203611 145238 251536 108078 238300\n[81] 108870 108085 262835 248182 244850 404456  67608  33860\n```\n\n\n:::\n:::\n\n\n\n> **Question:** Can you understand the meaning of Spatial lag as a sum of neighboring values now?\n>\n> **Answer:** spatial lag = the sum of all neighbors’ values.\n\nNext, we will append the *lag_sum GDPPC* field into `hunan` sf data frame by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan, lag.res)\n```\n:::\n\n\n\nNow, We can plot both the *GDPPC* and *Spatial Lag Sum GDPPC* for comparison using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngdppc <- qtm(hunan, \"GDPPC\")\nlag_sum_gdppc <- qtm(hunan, \"lag_sum GDPPC\")\ntmap_arrange(gdppc, lag_sum_gdppc, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n\n### **8.9.3 Spatial window average**\n\nThe spatial window average uses row-standardized weights and includes the diagonal element. To do this in R, we need to go back to the neighbors structure and add the diagonal element before assigning weights.\n\nTo add the diagonal element to the neighbour list, we just need to use *include.self()* from **spdep**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_qs <- include.self(wm_q)\n```\n:::\n\n\n\nNotice that the Number of nonzero links, Percentage nonzero weights and Average number of links are 536, 6.921488 and 6.090909 respectively as compared to wm_q of 448, 5.785124 and 5.090909\n\nLet us take a good look at the neighbour list of area \\[1\\] by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_qs[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1  2  3  4 57 85\n```\n\n\n:::\n:::\n\n\n\nNotice that now \\[1\\] has six neighbours instead of five.\n\nNow we obtain weights with *nb2listw()*\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_qs <- nb2listw(wm_qs)\nwm_qs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 536 \nPercentage nonzero weights: 6.921488 \nAverage number of links: 6.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 30.90265 357.5308\n```\n\n\n:::\n:::\n\n\n\nAgain, we use *nb2listw()* and *glist()* to explicitly assign weight values.\n\nLastly, we just need to create the lag variable from our weight structure and GDPPC variable.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlag_w_avg_gpdpc <- lag.listw(wm_qs, \n                             hunan$GDPPC)\nlag_w_avg_gpdpc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 24650.50 22434.17 26233.00 27084.60 26927.00 22230.17 47621.20 37160.12\n [9] 49224.71 29886.89 26627.50 22690.17 25366.40 25825.75 30329.00 32682.83\n[17] 25948.62 23987.67 25463.14 21904.38 23127.50 25949.83 20018.75 19524.17\n[25] 18955.00 17800.40 15883.00 18831.33 14832.50 17965.00 17159.89 16199.44\n[33] 18764.50 26878.75 23188.86 20788.14 12365.20 15985.00 13764.83 11907.43\n[41] 17128.14 14593.62 11644.29 12706.00 21712.29 43548.25 35049.00 16226.83\n[49] 19294.40 18156.00 19954.75 18145.17 12132.75 18419.29 14050.83 23619.75\n[57] 24552.71 24733.67 16762.60 20932.60 19467.75 18334.00 22541.00 26028.00\n[65] 29128.50 46569.00 47576.60 36545.50 20838.50 22531.00 42115.50 27619.00\n[73] 27611.33 44523.29 18127.43 28746.38 20734.50 33880.62 14716.38 28516.22\n[81] 18086.14 21244.50 29568.80 48119.71 22310.75 43151.60 17133.40 17009.33\n```\n\n\n:::\n:::\n\n\n\nNext, we will convert the lag variable listw object into a data.frame by using *as.data.frame()*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlag.list.wm_qs <- list(hunan$NAME_3, lag.listw(wm_qs, hunan$GDPPC))\nlag_wm_qs.res <- as.data.frame(lag.list.wm_qs)\ncolnames(lag_wm_qs.res) <- c(\"NAME_3\", \"lag_window_avg GDPPC\")\n```\n:::\n\n\n\nNote: The third command line on the code chunk above renames the field names of *lag_wm_q1.res* object into *NAME_3* and *lag_window_avg GDPPC* respectively.\n\nNext, the code chunk below will be used to append *lag_window_avg GDPPC* values onto *hunan* sf data.frame by using *left_join()* of **dplyr** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan, lag_wm_qs.res)\n```\n:::\n\n\n\nTo compare the values of lag GDPPC and Spatial window average, `kable()` of Knitr package is used to prepare a table using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan |>\n  sf::st_drop_geometry() |>\n  dplyr::select(\n    County,\n    `lag GDPPC`,\n    `lag_window_avg GDPPC`\n  ) |>\n  dplyr::rename(\n    `Lag GDPPC` = `lag GDPPC`,\n    `Window Avg GDPPC` = `lag_window_avg GDPPC`\n  ) |>\n  DT::datatable(\n    rownames = FALSE,\n    filter = \"top\",                     \n    options = list(\n      pageLength = 10,                 \n      dom = \"ftip\",                    \n      autoWidth = TRUE\n    )\n  ) |>\n  DT::formatRound(columns = c(\"Lag GDPPC\", \"Window Avg GDPPC\"), digits = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-f0b88140c9c79f07af4c\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-f0b88140c9c79f07af4c\">{\"x\":{\"filter\":\"top\",\"vertical\":false,\"filterHTML\":\"<tr>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"11566.3333333333\\\" data-max=\\\"55157.75\\\" data-scale=\\\"11\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"11644.2857142857\\\" data-max=\\\"49224.7142857143\\\" data-scale=\\\"11\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n<\\/tr>\",\"data\":[[\"Anxiang\",\"Hanshou\",\"Jinshi\",\"Li\",\"Linli\",\"Shimen\",\"Liuyang\",\"Ningxiang\",\"Wangcheng\",\"Anren\",\"Guidong\",\"Jiahe\",\"Linwu\",\"Rucheng\",\"Yizhang\",\"Yongxing\",\"Zixing\",\"Changning\",\"Hengdong\",\"Hengnan\",\"Hengshan\",\"Leiyang\",\"Qidong\",\"Chenxi\",\"Zhongfang\",\"Huitong\",\"Jingzhou\",\"Mayang\",\"Tongdao\",\"Xinhuang\",\"Xupu\",\"Yuanling\",\"Zhijiang\",\"Lengshuijiang\",\"Shuangfeng\",\"Xinhua\",\"Chengbu\",\"Dongan\",\"Dongkou\",\"Longhui\",\"Shaodong\",\"Suining\",\"Wugang\",\"Xinning\",\"Xinshao\",\"Shaoshan\",\"Xiangxiang\",\"Baojing\",\"Fenghuang\",\"Guzhang\",\"Huayuan\",\"Jishou\",\"Longshan\",\"Luxi\",\"Yongshun\",\"Anhua\",\"Nan\",\"Yuanjiang\",\"Jianghua\",\"Lanshan\",\"Ningyuan\",\"Shuangpai\",\"Xintian\",\"Huarong\",\"Linxiang\",\"Miluo\",\"Pingjiang\",\"Xiangyin\",\"Cili\",\"Chaling\",\"Liling\",\"Yanling\",\"You\",\"Zhuzhou\",\"Sangzhi\",\"Yueyang\",\"Qiyang\",\"Taojiang\",\"Shaoyang\",\"Lianyuan\",\"Hongjiang\",\"Hengyang\",\"Guiyang\",\"Changsha\",\"Taoyuan\",\"Xiangtan\",\"Dao\",\"Jiangyong\"],[24847.2,22724.8,24143.25,27737.5,27270.25,21248.8,43747,33582.71428571428,45651.16666666666,32027.625,32671,20810,25711.5,30672.33333333333,33457.75,31689.2,20269,23901.6,25126.16666666666,21903.42857142857,22718.6,25918.8,20307,20023.8,16576.8,18667,14394.66666666666,19848.8,15516.33333333333,20518,17572,15200.125,18413.8,14419.33333333333,24094.5,22019.83333333334,12923.5,14756,13869.8,12296.66666666667,15775.16666666666,14382.85714285714,11566.33333333333,13199.5,23412,39541,36186.60000000001,16559.6,20772.5,19471.2,19827.33333333333,15466.8,12925.66666666667,18577.16666666666,14943,24913,25093,24428.8,17003,21143.75,20435,17131.33333333333,24569.75,23835.5,26360,47383.40000000001,55157.75,37058.00000000001,21546.66666666666,23348.66666666666,42323.66666666666,28938.6,25880.8,47345.66666666666,18711.33333333333,29087.28571428571,20748.28571428572,35933.71428571428,15439.71428571428,29787.5,18145,21617,29203.88888888888,41363.66666666666,22259.09090909091,44939.55555555555,16902,16930],[24650.5,22434.16666666667,26233,27084.6,26927,22230.16666666666,47621.2,37160.125,49224.71428571428,29886.88888888889,26627.5,22690.16666666666,25366.4,25825.75,30329,32682.83333333333,25948.625,23987.66666666666,25463.14285714286,21904.375,23127.5,25949.83333333333,20018.75,19524.16666666666,18955,17800.4,15883,18831.33333333333,14832.5,17965,17159.88888888889,16199.44444444444,18764.5,26878.75,23188.85714285714,20788.14285714285,12365.2,15985,13764.83333333333,11907.42857142857,17128.14285714286,14593.625,11644.28571428571,12706,21712.28571428571,43548.25,35049,16226.83333333333,19294.4,18156,19954.75,18145.16666666666,12132.75,18419.28571428571,14050.83333333333,23619.75,24552.71428571429,24733.66666666666,16762.6,20932.60000000001,19467.75,18334,22541,26028,29128.5,46569,47576.60000000001,36545.5,20838.5,22531,42115.5,27619,27611.33333333333,44523.28571428571,18127.42857142857,28746.375,20734.5,33880.625,14716.375,28516.22222222222,18086.14285714286,21244.5,29568.8,48119.71428571428,22310.75,43151.6,17133.4,17009.33333333333]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>County<\\/th>\\n      <th>Lag GDPPC<\\/th>\\n      <th>Window Avg GDPPC<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":10,\"dom\":\"ftip\",\"autoWidth\":true,\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2]},{\"name\":\"County\",\"targets\":0},{\"name\":\"Lag GDPPC\",\"targets\":1},{\"name\":\"Window Avg GDPPC\",\"targets\":2}],\"order\":[],\"orderClasses\":false,\"orderCellsTop\":true}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\nLastly, *qtm()* of **tmap** package is used to plot the lag_gdppc and w_ave_gdppc maps next to each other for quick comparison.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_avg_gdppc <- qtm(hunan, \"lag_window_avg GDPPC\")\ntmap_arrange(lag_gdppc, w_avg_gdppc, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n\nNote: For more effective comparison, it is advicible to use the core tmap mapping functions.\n\n### **8.9.4 Spatial window sum**\n\nThe spatial window sum is the counter part of the window average, but without using row-standardized weights.\n\nTo add the diagonal element to the neighbour list, we just need to use *include.self()* from **spdep**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_qs <- include.self(wm_q)\nwm_qs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 536 \nPercentage nonzero weights: 6.921488 \nAverage number of links: 6.090909 \n```\n\n\n:::\n:::\n\n\n\nNext, we will assign binary weights to the neighbour structure that includes the diagonal element.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_weights <- lapply(wm_qs, function(x) 0*x + 1)\nb_weights[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[1] 1 1 1 1 1 1\n```\n\n\n:::\n:::\n\n\n\nNotice that now \\[1\\] has six neighbours instead of five.\n\nAgain, we use *nb2listw()* and *glist()* to explicitly assign weight values.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb_weights2 <- nb2listw(wm_qs, \n                       glist = b_weights, \n                       style = \"B\")\nb_weights2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 536 \nPercentage nonzero weights: 6.921488 \nAverage number of links: 6.090909 \n\nWeights style: B \nWeights constants summary:\n   n   nn  S0   S1    S2\nB 88 7744 536 1072 14160\n```\n\n\n:::\n:::\n\n\n\nWith our new weight structure, we can compute the lag variable with *lag.listw()*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_sum_gdppc <- list(hunan$NAME_3, lag.listw(b_weights2, hunan$GDPPC))\nw_sum_gdppc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n [1] \"Anxiang\"       \"Hanshou\"       \"Jinshi\"        \"Li\"           \n [5] \"Linli\"         \"Shimen\"        \"Liuyang\"       \"Ningxiang\"    \n [9] \"Wangcheng\"     \"Anren\"         \"Guidong\"       \"Jiahe\"        \n[13] \"Linwu\"         \"Rucheng\"       \"Yizhang\"       \"Yongxing\"     \n[17] \"Zixing\"        \"Changning\"     \"Hengdong\"      \"Hengnan\"      \n[21] \"Hengshan\"      \"Leiyang\"       \"Qidong\"        \"Chenxi\"       \n[25] \"Zhongfang\"     \"Huitong\"       \"Jingzhou\"      \"Mayang\"       \n[29] \"Tongdao\"       \"Xinhuang\"      \"Xupu\"          \"Yuanling\"     \n[33] \"Zhijiang\"      \"Lengshuijiang\" \"Shuangfeng\"    \"Xinhua\"       \n[37] \"Chengbu\"       \"Dongan\"        \"Dongkou\"       \"Longhui\"      \n[41] \"Shaodong\"      \"Suining\"       \"Wugang\"        \"Xinning\"      \n[45] \"Xinshao\"       \"Shaoshan\"      \"Xiangxiang\"    \"Baojing\"      \n[49] \"Fenghuang\"     \"Guzhang\"       \"Huayuan\"       \"Jishou\"       \n[53] \"Longshan\"      \"Luxi\"          \"Yongshun\"      \"Anhua\"        \n[57] \"Nan\"           \"Yuanjiang\"     \"Jianghua\"      \"Lanshan\"      \n[61] \"Ningyuan\"      \"Shuangpai\"     \"Xintian\"       \"Huarong\"      \n[65] \"Linxiang\"      \"Miluo\"         \"Pingjiang\"     \"Xiangyin\"     \n[69] \"Cili\"          \"Chaling\"       \"Liling\"        \"Yanling\"      \n[73] \"You\"           \"Zhuzhou\"       \"Sangzhi\"       \"Yueyang\"      \n[77] \"Qiyang\"        \"Taojiang\"      \"Shaoyang\"      \"Lianyuan\"     \n[81] \"Hongjiang\"     \"Hengyang\"      \"Guiyang\"       \"Changsha\"     \n[85] \"Taoyuan\"       \"Xiangtan\"      \"Dao\"           \"Jiangyong\"    \n\n[[2]]\n [1] 147903 134605 131165 135423 134635 133381 238106 297281 344573 268982\n[11] 106510 136141 126832 103303 151645 196097 207589 143926 178242 175235\n[21] 138765 155699 160150 117145 113730  89002  63532 112988  59330  35930\n[31] 154439 145795 112587 107515 162322 145517  61826  79925  82589  83352\n[41] 119897 116749  81510  63530 151986 174193 210294  97361  96472 108936\n[51]  79819 108871  48531 128935  84305 188958 171869 148402  83813 104663\n[61] 155742  73336 112705  78084  58257 279414 237883 219273  83354  90124\n[71] 168462 165714 165668 311663 126892 229971 165876 271045 117731 256646\n[81] 126603 127467 295688 336838 267729 431516  85667  51028\n```\n\n\n:::\n:::\n\n\n\nNext, we will convert the lag variable listw object into a data.frame by using *as.data.frame()*.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_sum_gdppc.res <- as.data.frame(w_sum_gdppc)\ncolnames(w_sum_gdppc.res) <- c(\"NAME_3\", \"w_sum GDPPC\")\n```\n:::\n\n\n\nNote: The second command line on the code chunk above renames the field names of *w_sum_gdppc.res*object into *NAME_3* and *w_sum GDPPC* respectively.\n\nNext, the code chunk below will be used to append *w_sum GDPPC* values onto *hunan* sf data.frame by using *left_join()* of **dplyr** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan, w_sum_gdppc.res)\n```\n:::\n\n\n\nTo compare the values of lag GDPPC and Spatial window average, `kable()` of Knitr package is used to prepare a table using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan |>\n  sf::st_drop_geometry() |>\n  dplyr::select(County, `lag_sum GDPPC`, `w_sum GDPPC`) |>\n  dplyr::rename(\n    `Lag sum GDPPC` = `lag_sum GDPPC`,\n    `W sum GDPPC`   = `w_sum GDPPC`\n  ) |>\n  DT::datatable(\n    rownames = FALSE,\n    filter = \"top\",                 \n    options = list(pageLength = 10, autoWidth = TRUE, dom = \"ftip\")  \n  ) |>\n  DT::formatRound(c(\"Lag sum GDPPC\", \"W sum GDPPC\"), digits = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-da0966127f14d5464e45\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-da0966127f14d5464e45\">{\"x\":{\"filter\":\"top\",\"vertical\":false,\"filterHTML\":\"<tr>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"20518\\\" data-max=\\\"404456\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"35930\\\" data-max=\\\"431516\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n<\\/tr>\",\"data\":[[\"Anxiang\",\"Hanshou\",\"Jinshi\",\"Li\",\"Linli\",\"Shimen\",\"Liuyang\",\"Ningxiang\",\"Wangcheng\",\"Anren\",\"Guidong\",\"Jiahe\",\"Linwu\",\"Rucheng\",\"Yizhang\",\"Yongxing\",\"Zixing\",\"Changning\",\"Hengdong\",\"Hengnan\",\"Hengshan\",\"Leiyang\",\"Qidong\",\"Chenxi\",\"Zhongfang\",\"Huitong\",\"Jingzhou\",\"Mayang\",\"Tongdao\",\"Xinhuang\",\"Xupu\",\"Yuanling\",\"Zhijiang\",\"Lengshuijiang\",\"Shuangfeng\",\"Xinhua\",\"Chengbu\",\"Dongan\",\"Dongkou\",\"Longhui\",\"Shaodong\",\"Suining\",\"Wugang\",\"Xinning\",\"Xinshao\",\"Shaoshan\",\"Xiangxiang\",\"Baojing\",\"Fenghuang\",\"Guzhang\",\"Huayuan\",\"Jishou\",\"Longshan\",\"Luxi\",\"Yongshun\",\"Anhua\",\"Nan\",\"Yuanjiang\",\"Jianghua\",\"Lanshan\",\"Ningyuan\",\"Shuangpai\",\"Xintian\",\"Huarong\",\"Linxiang\",\"Miluo\",\"Pingjiang\",\"Xiangyin\",\"Cili\",\"Chaling\",\"Liling\",\"Yanling\",\"You\",\"Zhuzhou\",\"Sangzhi\",\"Yueyang\",\"Qiyang\",\"Taojiang\",\"Shaoyang\",\"Lianyuan\",\"Hongjiang\",\"Hengyang\",\"Guiyang\",\"Changsha\",\"Taoyuan\",\"Xiangtan\",\"Dao\",\"Jiangyong\"],[124236,113624,96573,110950,109081,106244,174988,235079,273907,256221,98013,104050,102846,92017,133831,158446,141883,119508,150757,153324,113593,129594,142149,100119,82884,74668,43184,99244,46549,20518,140576,121601,92069,43258,144567,132119,51694,59024,69349,73780,94651,100680,69398,52798,140472,118623,180933,82798,83090,97356,59482,77334,38777,111463,74715,174391,150558,122144,68012,84575,143045,51394,98279,47671,26360,236917,220631,185290,64640,70046,126971,144693,129404,284074,112268,203611,145238,251536,108078,238300,108870,108085,262835,248182,244850,404456,67608,33860],[147903,134605,131165,135423,134635,133381,238106,297281,344573,268982,106510,136141,126832,103303,151645,196097,207589,143926,178242,175235,138765,155699,160150,117145,113730,89002,63532,112988,59330,35930,154439,145795,112587,107515,162322,145517,61826,79925,82589,83352,119897,116749,81510,63530,151986,174193,210294,97361,96472,108936,79819,108871,48531,128935,84305,188958,171869,148402,83813,104663,155742,73336,112705,78084,58257,279414,237883,219273,83354,90124,168462,165714,165668,311663,126892,229971,165876,271045,117731,256646,126603,127467,295688,336838,267729,431516,85667,51028]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>County<\\/th>\\n      <th>Lag sum GDPPC<\\/th>\\n      <th>W sum GDPPC<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":10,\"autoWidth\":true,\"dom\":\"ftip\",\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatRound(data, 2, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2]},{\"name\":\"County\",\"targets\":0},{\"name\":\"Lag sum GDPPC\",\"targets\":1},{\"name\":\"W sum GDPPC\",\"targets\":2}],\"order\":[],\"orderClasses\":false,\"orderCellsTop\":true}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\nLastly, *qtm()* of **tmap** package is used to plot the lag_sum GDPPC and w_sum_gdppc maps next to each other for quick comparison.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_sum_gdppc <- qtm(hunan, \"w_sum GDPPC\")\ntmap_arrange(lag_sum_gdppc, w_sum_gdppc, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex08_files/figure-html/unnamed-chunk-64-1.png){width=672}\n:::\n:::\n\n\n\n## **8.10 References**\n\n-   [Creating Neighbours using sf objects](https://cran.r-project.org/web/packages/spdep/vignettes/nb_sf.html)\n\n-   [Spatial Weights and Applications](https://r4gdsa.netlify.app/chap08)\n",
    "supporting": [
      "Hands-on_Ex08_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/nouislider-7.0.10/jquery.nouislider.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/nouislider-7.0.10/jquery.nouislider.min.js\"></script>\n<link href=\"../../site_libs/selectize-0.12.0/selectize.bootstrap3.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/selectize-0.12.0/selectize.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}