{
  "hash": "2d099065a21a457d1c37c6b48e9b5690",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on_Exercise 09: Global Measures of Spatial Autocorrelation\"\nauthor: \"BingBing\"\ndate: \"September 18, 2025\"\ndate-modified: \"last-modified\"\n\n---\n\n\n\n## **9.1 Overview**\n\nThis section teaches how to compute **Global Measures of Spatial Autocorrelation (GMSA)** with **spdep**: import geospatial data with **sf**, read CSVs with **readr**, join tables with **dplyr**, compute and interpret global spatial autocorrelation, and produce a **Moran scatterplot** and **spatial correlogram** with statistically sound explanations.\n\n## **9.2 Getting Started**\n\nAim: test whether development is evenly distributed across the province; if not, check for spatial clustering and identify where clusters occur.\n\n### 9.2.1 The analytical question\n\n-   Policy context: local governments seek equitable spatial development.\n\n-   Task: use spatial statistics to assess evenness.\n\n-   If uneven → ask: (1) Is there spatial clustering? (2) Where are the clusters?\n\n-   Case variable: GDP per capita (Hunan Province, PRC).\n\n### 9.2.2 The Study Area and Data\n\nStudy area: Hunan Province at the county level.\n\nDatasets:\n\n1.  County administrative boundary shapefile.\n\n2.  Hunan_2012.csv with selected development indicators (year 2012).\n\n### 9.2.3 Setting the Analytical Tools\n\nRequired R packages:\n\n-   sf — import/handle geospatial data\n\n-   tidyverse — wrangle attribute data\n\n-   spdep — spatial weights; global/local spatial autocorrelation\n\n-   tmap — cartographic-quality choropleth maps\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, spdep, tmap, tidyverse)\ncat(\">>> current_input: \", knitr::current_input(), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n>>> current_input:  Hands-on_Exercise09.rmarkdown \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\">>> getwd:          \", getwd(), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n>>> getwd:           /Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Hands-on_Ex/Hands-on_Ex09 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\">>> exists Hunan.shp (data/geospatial)? \",\n    file.exists(\"data/geospatial/Hunan.shp\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n>>> exists Hunan.shp (data/geospatial)?  TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\">>> exists wrong path (Hands-on_Ex09/data/geospatial)? \",\n    dir.exists(\"Hands-on_Ex09/data/geospatial\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n>>> exists wrong path (Hands-on_Ex09/data/geospatial)?  FALSE \n```\n\n\n:::\n:::\n\n\n\n## **9.3 Getting the Data Into R Environment**\n\nIn this section, we will learn how to bring a geospatial data and its associated attribute table into R environment. The geospatial data is in ESRI shapefile format and the attribute table is in csv fomat.\n\n### **9.3.1 Import shapefile into r environment**\n\nThe code chunk below uses [`st_read()`](https://r-spatial.github.io/sf/reference/st_read.html) of **sf** package to import Hunan shapefile into R. The imported shapefile will be **simple features** Object of **sf**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", \n                 layer = \"Hunan\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Hands-on_Ex/Hands-on_Ex09/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n\n### **9.3.2 Import csv file into r environment**\n\nNext, we will import *Hunan_2012.csv* into R by using [`read_csv()`](https://readr.tidyverse.org/reference/read_delim.html) of **readr**package. The output is R data frame class.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 88 Columns: 29\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (2): County, City\ndbl (27): avg_wage, deposite, FAI, Gov_Rev, Gov_Exp, GDP, GDPPC, GIO, Loan, ...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n### **9.3.3 Performing relational join**\n\nThe code chunk below will be used to update the attribute table of *hunan*’s SpatialPolygonsDataFrame with the attribute fields of *hunan2012* dataframe. This is performed by using [`left_join()`](https://dplyr.tidyverse.org/reference/mutate-joins.html) of **dplyr** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan,hunan2012) %>%\n  select(1:4, 7, 15)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(County)`\n```\n\n\n:::\n:::\n\n\n\n### **9.3.4 Visualising Regional Development Indicator**\n\nNow, we are going to prepare a basemap and a choropleth map showing the distribution of GDPPC 2012 by using `qtm()` of **tmap** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Equal interval classification\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[tm_borders()] Argument `fiil_alpha` unknown.\n[v3->v4] `tm_layout()`: use `tm_title()` instead of `tm_layout(main.title = )`\n```\n\n\n:::\n\n```{.r .cell-code}\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5)) +\n  tm_borders(fiil_alpha = 0.5) + \n  tm_layout(legend.position = c(\"left\", \"bottom\"), \n            main.title = \"Quantile classification\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[tm_borders()] Argument `fiil_alpha` unknown.\n[v3->v4] `tm_layout()`: use `tm_title()` instead of `tm_layout(main.title = )`\n```\n\n\n:::\n\n```{.r .cell-code}\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Exercise09_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n## **9.4 Global Measures of Spatial Autocorrelation**\n\nThis section teaches how to compute global spatial autocorrelation and how to test the null of spatial complete randomness, i.e., whether the observed pattern shows any overall spatial structure or is indistinguishable from random.\n\n### **9.4.1 Computing Contiguity Spatial Weights**\n\nBefore calculating those global statistics, you must build a spatial weights object that encodes which geographic units (counties) are neighbors. Using `spdep::poly2nb()` on polygon boundaries creates a contiguity neighbors list; by default `queen = TRUE`, so units sharing an edge or a corner are treated as neighbors (Queen criterion). Unless you set `queen = FALSE` (Rook), the function returns first-order Queen neighbors, which are then used to form the Queen contiguity weight matrix for subsequent global autocorrelation analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- poly2nb(hunan, \n                queen=TRUE)\nsummary(wm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \nLink number distribution:\n\n 1  2  3  4  5  6  7  8  9 11 \n 2  2 12 16 24 14 11  4  2  1 \n2 least connected regions:\n30 65 with 1 link\n1 most connected region:\n85 with 11 links\n```\n\n\n:::\n:::\n\n\n\nThe summary report above shows that there are 88 area units in Hunan. The most connected area unit has 11 neighbours. There are two area units with only one neighbours.\n\n### **9.4.2 Row-standardised weights matrix**\n\nIn this step, each county’s neighbors are given equal, row-standardised weights (style = “W”), meaning Assign a weight of 1/degree to every neighbor, making the spatial lag the mean of neighboring values. This is intuitive and comparable across units, but it can bias results near the study boundary because edge counties average over fewer neighbors, potentially distorting the apparent strength of autocorrelation. We proceed with style = “W” for simplicity, while noting that alternatives such as style = “B” (binary, unstandardised) may be more robust in some applications.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrswm_q <- nb2listw(wm_q, \n                   style=\"W\", \n                   zero.policy = TRUE)\nrswm_q\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCharacteristics of weights list object:\nNeighbour list object:\nNumber of regions: 88 \nNumber of nonzero links: 448 \nPercentage nonzero weights: 5.785124 \nAverage number of links: 5.090909 \n\nWeights style: W \nWeights constants summary:\n   n   nn S0       S1       S2\nW 88 7744 88 37.86334 365.9147\n```\n\n\n:::\n:::\n\n\n\n\\\n💡 **What can we learn from the code chunk above?**\n\n**Input type:** nb2listw() requires an object of class nb (neighbors list) as its input.\n\n**Key arguments:**\n\n-   style – controls how links become weights.\n\n-   \"B\": binary (1 for neighbor, 0 otherwise).\n\n-   \"W\": row-standardized (each row sums to 1; spatial lag = neighbor mean).\n\n-   \"C\": globally standardized (all weights sum to n).\n\n-   \"U\": \"C\" divided by each unit’s neighbor count (rows sum to 1).\n\n-   \"minmax\": rescale weights to \\[0, 1\\].\n\n-   \"S\": Tiefelsdorf variance-stabilizing scheme (weights sum to n).\n\n-   zero.policy – handling units with no neighbors.\n\n**Zero-neighbor handling (zero.policy = TRUE):**\n\n-   Inserts zero-length weight vectors for isolates.\n\n-   The spatially lagged value for such units becomes 0 (sum of products with a zero row).\n\n-   This may or may not be substantively appropriate—use with care.\n\n## **9.5 Global Measures of Spatial Autocorrelation: Moran’s I**\n\nIn this section, you will learn how to perform Moran’s I statistics testing by using [`moran.test()`](https://r-spatial.github.io/spdep/reference/moran.test.html) of **spdep**.\n\n### **9.5.1 Maron’s I test**\n\nThe code chunk below performs Moran’s I statistical testing using [`moran.test()`](https://r-spatial.github.io/spdep/reference/moran.test.html)of **spdep**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran.test(hunan$GDPPC, \n           listw=rswm_q, \n           zero.policy = TRUE, \n           na.action=na.omit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: rswm_q    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\n\n\n**💡 Conclusion:**\\\n\nMoran’s I = **0.301** (expected ≈ **−0.011**), Z = **4.74**, **p = 1.10×10⁻⁶** (one-sided, greater). We **reject spatial complete randomness** and conclude there is **significant positive global spatial autocorrelation** in GDP per capita across Hunan counties—neighboring counties have more similar values than expected by chance (i.e., clustering of high–high and low–low areas).\n\n### **9.5.2 Computing Monte Carlo Moran’s I**\n\nThe code chunk below performs permutation test for Moran’s I statistic by using [`moran.mc()`](https://r-spatial.github.io/spdep/reference/moran.mc.html) of **spdep**. A total of 1000 simulation will be performed.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm= moran.mc(hunan$GDPPC, \n                listw=rswm_q, \n                nsim=999, \n                zero.policy = TRUE, \n                na.action=na.omit)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\n**💡 Conclusion:**\\\n\nPermutation test (999 sims) gives Moran’s I ≈ **0.3008**, **p = 0.001** (one-sided, greater; observed rank = 1000/1000). We **reject spatial complete randomness** and conclude **strong, positive global spatial autocorrelation** in GDP per capita—neighboring counties are more similar than expected by chance (i.e., clustering of high–high and low–low values).\n\n### **9.5.3 Visualising Monte Carlo Moran’s I**\n\nIt is always a good practice for us the examine the simulated Moran’s I test statistics in greater detail. This can be achieved by plotting the distribution of the statistical values as a histogram by using the code chunk below.\n\nIn the code chunk below [`hist()`](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/hist) and [`abline()`](https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/abline) of R Graphics are used.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.01504572\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.004371574\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n-0.18339 -0.06168 -0.02125 -0.01505  0.02611  0.27593 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, \n     freq=TRUE, \n     breaks=20, \n     xlab=\"Simulated Moran's I\")\nabline(v=0, \n       col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_Exercise09_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n**💡 Conclusion:**\n\nThe 999 permuted Moran’s I values are roughly bell-shaped and centered near **−0.015** (var ≈ **0.00437**). **Moran’s I ≈ 0.3008** lies far in the **extreme right tail**—beyond virtually all simulated values—so the permutation p-value is ≈ **0.001**. We reject spatial complete randomness and conclude **strong positive global spatial autocorrelation** in GDP per capita.\n\nIf plot the values by using ggplot2 package :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# packages\nlibrary(ggplot2,dplyr)\n\n# convert to a data frame\nsim_df <- tibble(I_sim = bperm$res[1:999])         \nI_obs  <- as.numeric(bperm$statistic)              \nI_mean <- mean(sim_df$I_sim)                      \n\n# histogram with reference lines\nggplot(sim_df, aes(x = I_sim)) +\n  geom_histogram(bins = 30, fill = \"grey70\", color = \"grey30\") +\n  geom_vline(xintercept = 0, linewidth = 0.8, color = \"red\") +\n  geom_vline(xintercept = I_mean, linetype = \"dashed\") +\n  geom_vline(xintercept = I_obs, linewidth = 1) +\n  labs(\n    title = \"bperm$res\",\n    x = \"Simulated Moran's I\",\n    y = \"Frequency\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Hands-on_Exercise09_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n## **9.6 Global Measures of Spatial Autocorrelation: Geary’s C**\n\nIn this section, you will learn how to perform Geary’s C statistics testing by using appropriate functions of **spdep** package.\n\n### **9.6.1 Geary’s C test**\n\nThe code chunk below performs Geary’s C test for spatial autocorrelation by using [`geary.test()`](https://r-spatial.github.io/spdep/reference/geary.test.html) of **spdep**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary.test(hunan$GDPPC, listw=rswm_q)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: rswm_q   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n:::\n\n\n\n**💡 Conclusion (Geary’s C):**\\\n\nGeary’s C = **0.6907** (expected **1.0**), Z = **3.61**, **p ≈ 0.00015**. Because **C \\< 1** and is highly significant, we reject spatial complete randomness and conclude there is **significant positive global spatial autocorrelation** in GDP per capita—neighboring counties are more similar than expected by chance.\n\n### **9.6.2 Computing Monte Carlo Geary’s C**\n\nThe code chunk below performs permutation test for Geary’s C statistic by using [`geary.mc()`](https://r-spatial.github.io/spdep/reference/geary.mc.html) of **spdep**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nbperm=geary.mc(hunan$GDPPC, \n               listw=rswm_q, \n               nsim=999)\nbperm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: rswm_q  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\n**💡 Conclusion (Geary’s C, permutation test):**\\\n\nGeary’s C = **0.6907** with **p = 0.001** (999 simulations; observed rank = 1/1000). Since **C \\< 1** and is highly significant, we reject spatial complete randomness and conclude there is **significant positive global spatial autocorrelation** in GDP per capita—neighboring counties are more similar than expected by chance.\n\n### **9.6.3 Visualising the Monte Carlo Geary’s C**\n\nNext, we will plot a histogram to reveal the distribution of the simulated values by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.004402\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.007436493\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(bperm$res[1:999])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.7142  0.9502  1.0052  1.0044  1.0595  1.2722 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(bperm$res, freq=TRUE, breaks=20, xlab=\"Simulated Geary c\")\nabline(v=1, col=\"red\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_Exercise09_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n**💡 Statistical observation:**\\\n\nThe permutation (null) distribution of **Geary’s C** from 999 simulations is centered at about **1.00** (mean ≈ **1.004**, median ≈ **1.005**, var ≈ **0.00744**, IQR ≈ **0.95–1.06**), as shown by the histogram with the red line at 1. Because your observed **C = 0.6907** lies far in the **left tail** of this distribution, it implies a very small p-value (≈0.001) and thus **significant positive global spatial autocorrelation**—neighboring counties have more similar GDP per capita than expected under spatial randomness.\n\n## **9.7 Spatial Correlogram**\n\nA spatial correlogram plots a spatial autocorrelation index (typically Moran’s *I* or Geary’s *C*) against increasing distance (lags) to reveal how similarity between locations changes with separation. Though not as foundational as variograms, correlograms are powerful exploratory graphics and can be even more informative for describing global-to-local correlation patterns in data or model residuals.\n\n### **9.7.1 Moran’s I correlogram**\n\nIn the code chunk below, [`sp.correlogram()`](https://r-spatial.github.io/spdep/reference/sp.correlogram.html) of **spdep** package is used to compute a 6-lag spatial correlogram of GDPPC. The global spatial autocorrelation used in Moran’s I. The **plot()** of base Graph is then used to plot the output.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMI_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"I\", \n                          style=\"W\")\nplot(MI_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Exercise09_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\nBy plotting the output might not allow us to provide complete interpretation. This is because not all autocorrelation values are statistically significant. Hence, it is important for us to examine the full analysis report by printing out the analysis results as in the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(MI_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351       2.189e-06 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505       2.029e-06 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496        0.040400 *  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107        0.226015    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134       5.984e-05 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164        0.008886 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n**💡 Conclusion (Moran’s I correlogram):**\\\n\nSpatial dependence is **strongly positive at short distances** and then decays, turns insignificant, and finally becomes **significantly negative at larger lags**. Specifically, Moran’s I is positive and significant at lags 1–3 (≈0.301, 0.206, 0.067), not significant at lag 4 (≈0.030), and **negative and significant** at lags 5–6 (≈−0.153, −0.119). This pattern indicates clustering of similar GDPPC among nearby counties, weakening with distance, and a tendency toward dissimilarity at broader separations.\n\n### **9.7.2 Compute Geary’s C correlogram and plot**\n\nIn the code chunk below, `sp.correlogram()` of **spdep** package is used to compute a 6-lag spatial correlogram of GDPPC. The global spatial autocorrelation used in Geary’s C. The **plot()** of base Graph is then used to plot the output.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGC_corr <- sp.correlogram(wm_q, \n                          hunan$GDPPC, \n                          order=6, \n                          method=\"C\", \n                          style=\"W\")\nplot(GC_corr)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Exercise09_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n\nWe will print out the analysis report by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(GC_corr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Geary's C\n        estimate expectation  variance standard deviate Pr(I) two sided    \n1 (88) 0.6907223   1.0000000 0.0073364          -3.6108       0.0003052 ***\n2 (88) 0.7630197   1.0000000 0.0049126          -3.3811       0.0007220 ***\n3 (88) 0.9397299   1.0000000 0.0049005          -0.8610       0.3892612    \n4 (88) 1.0098462   1.0000000 0.0039631           0.1564       0.8757128    \n5 (88) 1.2008204   1.0000000 0.0035568           3.3673       0.0007592 ***\n6 (88) 1.0773386   1.0000000 0.0058042           1.0151       0.3100407    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n💡 **Observation (Geary’s C correlogram):**\\\n\nAt short distances there is **significant positive spatial autocorrelation** (C \\< 1) at **lags 1–2** . The effect **dissipates** and becomes **non-significant** at **lags 3–4**. At **lag 5**, C rises **above 1** and is **significantly \\> 1**, indicating **negative spatial autocorrelation** (dissimilarity) at broader separations; **lag 6** is not significant.\n",
    "supporting": [
      "Hands-on_Exercise09_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}