{
  "hash": "568b1dd353afad9975ad708af2a0d897",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 02\"\nauthor: \"BingBing\"\ndate: \"2025-10-15\"\nformat: html\nexecute:\n  warning: false\n  message: false\n  freeze: true\n---\n\n\n\n## 1. Introduction\n\nBuses stitch a city together. Every weekday morning, streams of commuters converge on workplaces and schools. In the evenings and at weekends, however, people disperse to shop, visit friends and family, or relax. Thanks to smartcard ticketing and GPS enabled fleets, we now have detailed records of these everyday movements, showing not only where people travel, but also when these patterns surge, fade or shift across neighborhoods. In practice, however, such rich data are often flattened into static maps or single summary numbers, which can obscure important local differences and conceal changes as they unfold. This study looks beyond the averages. Using bus origin–destination passenger volumes from the LTA DataMall, we address two fundamental yet practical questions:\n\n1.  How do bus mobility patterns differ across neighborhoods?\n\n2.  What emerging patterns are taking shape, that could help planners to anticipate commuting demand and design more responsive services and policies?\n\nThe study's aim is to turn raw movement traces into grounded insights and highlight where targeted capacity adjustments could improve everyday journeys, where persistent gaps may require structural solutions and where time-bound surges necessitate flexible interventions. In short, our aim is to provide a clear neighborhood level view of how bus demand actually behaves, and to use emerging models for detecting urban mobility to help planners predict commuting demand and design more responsive public transport services and policies.\n\n## 2. Loading the R package\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf,sfdep,tmap,tidyverse,plotly,Kendall,knitr,lubridate,dplyr,sf,tidyr,spdep,ggplot2,scales)\n```\n:::\n\n\n\n## 3. Data Preparation\n\n### 3.1 Import data\n\n-   **Master Plan 2019 Subzone boundaries:**\n\nThe Master Plan 2019 Subzone Boundary dataset is from URA Master Plan 2019 Subzone Boundary (KML/Shape). We reproject all geospatial layers to Singapore’s projected CRS **SVY21 / EPSG:3414**, so that distances and areas are expressed in **metres** and are therefore appropriate for density, contiguity, and LMSA computations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = read_rds(\"data/mpsz_sf.rds\")\n```\n:::\n\n\n\n-   **Bus Stop Location:**\n\nFrom LTA Bus Stop locations (CSV/GeoJSON) with WGS 84 latitude/longitude.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBusStop = st_read(dsn = \"data/geospatial/LTADataMall/\", \n                  layer = \"BusStop\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BusStop' from data source \n  `/Users/geloliu/Gelo-BingBing/ISSS626-GAA-main/Take-Home_Exercises/Take-Home_Exercise02/data/geospatial/LTADATAMALL' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5172 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48285.52 ymax: 52983.82\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n-   **Odbus Data:**\n\nLTA DataMall “Passenger Volume by Origin Destination Bus Stops” (2025.07 - 2025.09).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodbus <- read_csv(\"data/aspatial/origin_destination_bus_2025Q3_merged.csv\")\n```\n:::\n\n\n\n### 3.2 Data review and processing\n\n-   **mpsz**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 332\nColumns: 3\n$ Name        <chr> \"kml_1\", \"kml_2\", \"kml_3\", \"kml_4\", \"kml_5\", \"kml_6\", \"kml…\n$ Description <chr> \"<center><table><tr><th colspan='2' align='center'><em>Att…\n$ geometry    <MULTIPOLYGON [m]> MULTIPOLYGON (((25910.34 29..., MULTIPOLYGON …\n```\n\n\n:::\n:::\n\n\n\n-   **Bus Stop**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(BusStop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 5,172\nColumns: 3\n$ BUS_STOP_N <chr> \"65059\", \"16171\", \"61101\", \"01239\", \"17269\", \"11291\", \"1153…\n$ LOC_DESC   <chr> \"ST ANNE'S CH\", \"YUSOF ISHAK HSE\", \"BLK 120\", \"SULTAN PLAZA…\n$ geometry   <POINT [m]> POINT (35565.66 41659.52), POINT (21439.91 31253.63),…\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(BusStop,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 21439.91 ymin: 31253.63 xmax: 35565.66 ymax: 41659.52\nProjected CRS: SVY21 / Singapore TM\n  BUS_STOP_N        LOC_DESC                  geometry\n1      65059    ST ANNE'S CH POINT (35565.66 41659.52)\n2      16171 YUSOF ISHAK HSE POINT (21439.91 31253.63)\n3      61101         BLK 120 POINT (31381.06 35313.49)\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Total records:\", nrow(BusStop), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal records: 5172 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Unique BUS_STOP_N:\", n_distinct(BusStop$BUS_STOP_N), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnique BUS_STOP_N: 5154 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Missing BUS_STOP_N:\", sum(is.na(BusStop$BUS_STOP_N)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing BUS_STOP_N: 1 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"BUS_STOP_N type:\", class(BusStop$BUS_STOP_N), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBUS_STOP_N type: character \n```\n\n\n:::\n:::\n\n\n\nBefore joining with trips, we audited the key to prevent mismatches. Total record has **5,172** rows, but only **5,154** **unique** `BUS_STOP_N`, so some codes were duplicates. Let's list the duplicated codes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndup_bus_stop_n <- BusStop %>%\n  st_drop_geometry() %>%\n  count(BUS_STOP_N, sort = TRUE) %>%\n  filter(n > 1)\n\nhead(dup_bus_stop_n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  BUS_STOP_N n\n1      09047 2\n2      11009 2\n3      22501 2\n4      43709 2\n5      47201 2\n6      50261 2\n```\n\n\n:::\n:::\n\n\n\nWhen I search those `BUS_STOP_N` ,only have one record,these duplicates are most likely repeated records. Therefore, we keep one record per code, standardize `BUS_STOP_N` to 5-digit and remove messy rows.\n\n![](images/clipboard-3978213661.jpeg){fig-align=\"center\" width=\"241\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBusStop <- BusStop %>%\n  mutate(orig = as.character(BUS_STOP_N),LOC_DESC = na_if(LOC_DESC, \"\")) %>%\n  filter(!(str_detect(orig, \"[A-Za-z]\") & (is.na(LOC_DESC) | LOC_DESC == \"000\"))) %>%\n  mutate(BUS_STOP_N = str_pad(str_extract(orig, \"\\\\d+\"), 5, pad = \"0\")) %>%\n  filter(str_detect(BUS_STOP_N, \"^\\\\d{5}$\")) %>%\n  distinct(BUS_STOP_N, .keep_all = TRUE) %>%\n  select(-orig)\n\ncat(\"After cleaning:\", nrow(BusStop), \"records\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAfter cleaning: 5151 records\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"All codes are 5-digit:\", all(nchar(BusStop$BUS_STOP_N) == 5), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAll codes are 5-digit: TRUE \n```\n\n\n:::\n:::\n\n\n\n-   **Odbus:**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanyNA(odbus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\ndplyr::glimpse(odbus) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 17,306,071\nColumns: 7\n$ YEAR_MONTH          <chr> \"2025-07\", \"2025-07\", \"2025-07\", \"2025-07\", \"2025-…\n$ DAY_TYPE            <chr> \"WEEKDAY\", \"WEEKENDS/HOLIDAY\", \"WEEKENDS/HOLIDAY\",…\n$ TIME_PER_HOUR       <dbl> 6, 16, 8, 18, 15, 18, 12, 21, 16, 11, 5, 9, 15, 0,…\n$ PT_TYPE             <chr> \"BUS\", \"BUS\", \"BUS\", \"BUS\", \"BUS\", \"BUS\", \"BUS\", \"…\n$ ORIGIN_PT_CODE      <dbl> 71081, 52231, 9212, 9059, 84619, 20179, 80141, 224…\n$ DESTINATION_PT_CODE <dbl> 1139, 62131, 50229, 42061, 7211, 20261, 62139, 283…\n$ TOTAL_TRIPS         <dbl> 3, 18, 24, 2, 1, 4, 1, 1, 9, 6, 176, 2, 106, 2, 5,…\n```\n\n\n:::\n:::\n\n\n\nWe can see that there are no missing values now. For later work reliable, we’ll check the code of `ORIGIN_PT_CODE`and `DESTINATION_PT_CODE` and standardize avoid messy.\n\n## 5. Data Classification and Aggregation\n\n### 5.1 Time Period Classification\n\nWe use **DAY_TYPE** to separate weekdays from weekends/holidays, and **TIME_PER_HOUR** to define the time windows for the subsequent analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodbus_classified <- odbus %>%\n  mutate(\n    TIME_PERIOD = case_when(\n      DAY_TYPE == \"WEEKDAY\" & TIME_PER_HOUR %in% 6:9  ~ \"Weekday_Morning\",\n      DAY_TYPE == \"WEEKDAY\" & TIME_PER_HOUR %in% 17:20 ~ \"Weekday_Afternoon\",\n      DAY_TYPE %in% c(\"WEEKENDS/HOLIDAY\") & TIME_PER_HOUR %in% 11:20 ~ \"Weekend_Holiday\",\n      TRUE ~ \"Other\")) %>%\n  filter(TIME_PERIOD != \"Other\") %>%\n  mutate(\n    ORIGIN_PT_CODE = str_pad(str_extract(as.character(ORIGIN_PT_CODE), \"\\\\d+\"), 5, pad = \"0\"),\n    DESTINATION_PT_CODE = str_pad(str_extract(as.character(DESTINATION_PT_CODE), \"\\\\d+\"), 5, pad = \"0\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nall(stringr::str_detect(odbus_classified$ORIGIN_PT_CODE, \"^\\\\d{5}$\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nall(stringr::str_detect(odbus_classified$DESTINATION_PT_CODE, \"^\\\\d{5}$\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(odbus_classified$TIME_PERIOD, odbus_classified$YEAR_MONTH)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   \n                    2025-07 2025-08 2025-09\n  Weekday_Afternoon  802000  790727  785700\n  Weekday_Morning    685552  675735  682226\n  Weekend_Holiday   1421371 1540652 1430964\n```\n\n\n:::\n:::\n\n\n\n### 5.2 Aggregating by Origin\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_origin <- odbus_classified %>%\n  group_by(ORIGIN_PT_CODE, YEAR_MONTH, TIME_PERIOD) %>%\n  summarise(TOTAL_TRIPS = sum(TOTAL_TRIPS, na.rm = TRUE), .groups = 'drop') %>%\n  rename(BUS_STOP_CODE = ORIGIN_PT_CODE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(trips_origin$TOTAL_TRIPS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      1     534    1862    4609    4717  534459 \n```\n\n\n:::\n:::\n\n\n\n## 6. Creating Hexagonal Grid (375m)\n\n### **6.1 Creating the Grid**\n\nWe first generate a 375m equal area hexagonal grid in SVY21, clip it to the mainland boundary, and assign `HEX_ID`. This grid aggregates origin trips and supports subsequent LMSA/EHSA analyses.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_sg <- st_make_grid(mpsz, cellsize = 750,what = \"polygons\",square = FALSE) %>%\n  st_sf() %>%\n  mutate(HEX_ID = sprintf(\"H%04d\", row_number()))\n```\n:::\n\n\n\nChecking the hexagon layer visually:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nland_sg <- st_union(mpsz)\nhex_main <- st_intersection(hexagon_sg, land_sg)\ntm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"black\", lwd = 0.6) +\ntm_shape(hex_main) +\n  tm_borders(col = \"black\", lwd = 0.3) +\ntm_title(\"Hexagonal Grid (375m) — Singapore Mainland\") +\ntm_layout(frame = TRUE, bg.color = \"white\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n### 6.2 Filtering to Relevant Hexagons\n\nKeep only hexagons that intersect at least one bus stop for visualizing.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBusStop_sg <- st_join(BusStop, mpsz, join = st_within, left = FALSE)\nhexagon_with_stops <- hexagon_sg[\n  lengths(st_intersects(hexagon_sg, BusStop_sg)) > 0, ]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Bus stops in mainland:\", nrow(BusStop_sg), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBus stops in mainland: 5146 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Hexagons with stops:\", nrow(hexagon_with_stops), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHexagons with stops: 834 \n```\n\n\n:::\n:::\n\n\n\n### **6.3 Visualizing the hexagon layer**\n\nQuick check: plot the hexagon over the mainland and drop the bus stops on top.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nland_sg <- st_union(mpsz)\ntm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"black\", lwd = 0.6) +\ntm_shape(hexagon_with_stops) +\n  tm_borders(col = \"black\", lwd = 0.3) +\ntm_shape(BusStop_sg) +\n  tm_dots(fill = \"black\", size = 0.03, alpha = 0.5) +\n  tm_layout(\n    main.title = \"Hexagonal Grid (375m) with Bus Stops\",\n    frame = TRUE) +\n  tm_compass(type = \"8star\", size = 2) +\n  tm_scale_bar()\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n```\n:::\n\n\n\n## 7. Aggregating Trips to Hexagons\n\n### 7.1 Spatial Join\n\nAssign bus stops to hexagons.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBusStop_hex <- st_join(BusStop_sg, hexagon_with_stops %>% select(HEX_ID), \n                       join = st_within) %>% group_by(BUS_STOP_N) %>% slice(1) %>% ungroup()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Bus stops assigned to hexagons:\", nrow(BusStop_hex), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBus stops assigned to hexagons: 5146 \n```\n\n\n:::\n:::\n\n\n\n### 7.2 Join Trips with Hexagons\n\nMatch origin-trip records to those hexagon ID via Bus Stop code.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_hex <- trips_origin %>%\n  left_join(\n    BusStop_hex %>% st_drop_geometry() %>% select(BUS_STOP_N, HEX_ID),\n    by = c(\"BUS_STOP_CODE\" = \"BUS_STOP_N\")) %>%\n  filter(!is.na(HEX_ID))\n\ncat(\"Trip records matched:\", nrow(trips_hex), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTrip records matched: 44716 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Match rate:\", sprintf(\"%.1f%%\\n\", nrow(trips_hex)/nrow(trips_origin)*100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMatch rate: 97.1%\n```\n\n\n:::\n:::\n\n\n\n### 7.3 Aggregate to Hexagon Level\n\nAggregate origin trips by **HEX_ID × month × period** to get `TOTAL_TRIPS` per hex.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_hex_agg <- trips_hex %>%\n  group_by(HEX_ID, YEAR_MONTH, TIME_PERIOD) %>%\n  summarise(TOTAL_TRIPS = sum(TOTAL_TRIPS, na.rm = TRUE), .groups = 'drop')\n\nhead(trips_hex_agg, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   HEX_ID YEAR_MONTH TIME_PERIOD       TOTAL_TRIPS\n   <chr>  <chr>      <chr>                   <dbl>\n 1 H0118  2025-07    Weekday_Afternoon        1138\n 2 H0118  2025-07    Weekday_Morning           395\n 3 H0118  2025-07    Weekend_Holiday           886\n 4 H0118  2025-08    Weekday_Afternoon        1111\n 5 H0118  2025-08    Weekday_Morning           374\n 6 H0118  2025-08    Weekend_Holiday          1299\n 7 H0118  2025-09    Weekday_Afternoon        1142\n 8 H0118  2025-09    Weekday_Morning           503\n 9 H0118  2025-09    Weekend_Holiday          1133\n10 H0146  2025-07    Weekday_Afternoon          62\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(trips_hex_agg$TOTAL_TRIPS)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      2    2471   13164   28027   35548  551828 \n```\n\n\n:::\n:::\n\n\n\n## 8. Exploratory Data Analysis\n\n### 8.1 Distribution by Time Period\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_table <- trips_hex_agg %>%\n  group_by(YEAR_MONTH, TIME_PERIOD) %>%\n  summarise(\n    Mean = mean(TOTAL_TRIPS),\n    Median = median(TOTAL_TRIPS),\n    SD = sd(TOTAL_TRIPS),\n    Min = min(TOTAL_TRIPS),\n    Max = max(TOTAL_TRIPS),\n    .groups = 'drop'\n  )\n\nkable(summary_table, digits = 1)\n```\n\n::: {.cell-output-display}\n\n\n|YEAR_MONTH |TIME_PERIOD       |    Mean|  Median|      SD| Min|    Max|\n|:----------|:-----------------|-------:|-------:|-------:|---:|------:|\n|2025-07    |Weekday_Afternoon | 32705.2| 16249.5| 55481.7|   8| 551828|\n|2025-07    |Weekday_Morning   | 33477.8| 15703.0| 45522.5|   4| 390677|\n|2025-07    |Weekend_Holiday   | 20052.4|  8770.0| 32734.9|  11| 280003|\n|2025-08    |Weekday_Afternoon | 30145.1| 14872.0| 50531.7|  30| 512125|\n|2025-08    |Weekday_Morning   | 30740.9| 14933.5| 41769.3|   2| 385342|\n|2025-08    |Weekend_Holiday   | 25178.7| 11742.5| 40890.7|  13| 366420|\n|2025-09    |Weekday_Afternoon | 29691.8| 14319.0| 50291.2|  10| 520246|\n|2025-09    |Weekday_Morning   | 30629.3| 15542.5| 41491.2|   3| 391985|\n|2025-09    |Weekend_Holiday   | 19807.9|  8935.5| 32254.9|  10| 285365|\n\n\n:::\n:::\n\n\n\n### 8.2 **EDA using statistical graphics**\n\nWe can plot the distribution of the variables by using appropriate Exploratory Data Analysis (EDA) as shown in the code chunk below. Histogram is useful to identify the overall distribution of the data values (i.e. left skew, right skew or normal distribution)\n\n-   **Distribution**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trips_hex_agg, aes(x = TOTAL_TRIPS, fill = TIME_PERIOD)) +\n  geom_histogram(bins = 50, alpha = 0.7) +\n  facet_grid(TIME_PERIOD ~ YEAR_MONTH, scales = \"free_y\") +\n  scale_x_continuous(labels = scales::comma) +  \n  theme_minimal() +\n  labs(\n    title = \"Distribution of Bus Trips by Time Period\",\n    x = \"Total Trips per Hexagon\",\n    y = \"Frequency\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\nMost hexes have low–moderate trips, with a **few very busy cells** pushing a long right tail, this pattern holds in all three months. **Weekday peaks \\> weekend peaks**, and the **PM peak shows the heaviest tail**, meaning a small set of corridors dominates after work. The month to month shape barely changes, suggesting **stable commuter structure**.\n\n-   **Comparing Time-Window Distributions (log10)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trips_hex_agg, aes(x = TOTAL_TRIPS, fill = TIME_PERIOD)) +\n  geom_histogram(bins = 50, alpha = 0.7) +\n  facet_grid(TIME_PERIOD ~ YEAR_MONTH, scales = \"free_y\") +\n  scale_x_log10(labels = scales::comma,breaks = c(10, 100, 1000, 10000, 100000)) +\n  theme_minimal() +\n  labs(\n    title = \"Distribution of Bus Trips by Time Period (Log Scale)\",\n    x = \"Total Trips per Hexagon (log 10 scale)\",\n    y = \"Frequency\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\nPlotted hexagon level totals on a **log10** axis, faceted by **time period × month**. The log scale tames the heavy right tail, so distributions are comparable across periods for later mapping/LMSA.\n\n-   **Trip Distribution by Time Period and Month (Boxplots)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(trips_hex_agg, aes(x = TIME_PERIOD, y = TOTAL_TRIPS, fill = TIME_PERIOD)) +\n  geom_boxplot(color = \"black\") +\n  facet_wrap(~YEAR_MONTH) +\n  theme_minimal() +\n  labs(\n    title = \"Trip Distribution by Time Period and Month\",\n    x = \"Time Period\",\n    y = \"Total Trips per Hexagon\") +\n  theme(legend.position = \"none\",axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-28-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Log scale version (recommended for skewed data)\nggplot(trips_hex_agg, aes(x = TIME_PERIOD, y = TOTAL_TRIPS, fill = TIME_PERIOD)) +\n  geom_boxplot(color = \"black\") +\n  facet_wrap(~YEAR_MONTH) +\n  scale_y_log10(labels = scales::comma) +\n  theme_minimal() +\n  labs(\n    title = \"Trip Distribution by Time Period and Month (Log Scale)\",\n    x = \"Time Period\",\n    y = \"Total Trips per Hexagon (log10)\") +\n  theme(legend.position = \"none\",axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-28-2.png){width=672}\n:::\n:::\n\n\n\nAfter work corridors carry the heaviest and most volatile demand, so evening-peak capacity, headways, and dwell-time management should be the first priority.\n\n### 8.3 **EDA using choropleth map**\n\n-   **Analytical Hexagon**\n\nHexagons reduce sampling bias due to edge effects of the grid shape, this is related to the low perimeter to area ratio of the shape of the hexagon. A circle has the lowest ratio but cannot tessellate to form a continuous grid. Hexagons are the most circular-shaped polygon that can tessellate to form an evenly spaced grid.\n\n![](images/clipboard-1934948502.png){fig-align=\"center\" width=\"97\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhex_totals <- trips_hex_agg %>%\n  dplyr::group_by(HEX_ID, TIME_PERIOD) %>%\n  dplyr::summarise(Total_Trips = sum(TOTAL_TRIPS), .groups = 'drop')\n\nhex_trips_sf <- hexagon_with_stops %>%\n  dplyr::left_join(hex_totals, by = \"HEX_ID\") %>%\n  dplyr::mutate(Total_Trips = tidyr::replace_na(Total_Trips, 0))\n\nland_sg <- sf::st_union(mpsz)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\nall_vals <- hex_trips_sf$Total_Trips\nbrks <- classInt::classIntervals(all_vals[all_vals > 0], n = 6, style = \"jenks\")$brks\nbrks[1] <- 0\n\nmake_map <- function(period, title){\n  tm_shape(land_sg) +\n  tm_polygons(fill = \"grey95\", col = \"grey70\") +\n  tm_shape(hex_trips_sf %>% filter(TIME_PERIOD == period)) +\n  tm_fill(\n      \"Total_Trips\",\n      style   = \"fixed\",   \n      breaks  = brks,\n      n       = length(brks)-1,\n      palette = \"YlOrRd\",\n      alpha   = 0.90,\n      title   = \"Total Trips\") +\n  tm_borders(col = \"grey40\", lwd = 0.1) +\n  tm_layout(\n      main.title     = title,\n      legend.outside = TRUE,\n      bg.color       = \"white\") +\n  tm_compass(type = \"8star\", position = c(\"right\",\"bottom\")) +\n  tm_scale_bar(position = c(\"right\",\"bottom\"))}\n\nmorning_map   <- make_map(\"Weekday_Morning\",   \"Weekday Morning Peak (6-9 AM)\")\nafternoon_map <- make_map(\"Weekday_Afternoon\", \"Weekday Afternoon Peak (5-8 PM)\")\nweekend_map   <- make_map(\"Weekend_Holiday\",   \"Weekend/Holiday (11 AM-8 PM)\")\n\nmorning_map\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n\n```{.r .cell-code}\nafternoon_map\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-30-2.png){width=672}\n:::\n\n```{.r .cell-code}\nweekend_map\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-30-3.png){width=672}\n:::\n:::\n\n\n\n**Weekday morning** shows strong origin clusters along the main commuter belts linking residential towns to employment centres. High value hexagons form continuous corridors with sharp drop offs at the edges. In the **weekday evening**, the pattern broadens and intensifies—more hexagons step up one or two classes, and high cells extend further along the same corridors, consistent with heavier after-work flows. **Weekend/holiday** volumes are clearly lower and more scattered, with pockets around retail and leisure areas but weaker corridor continuity.\n\n## 9. **Local Measures of Spatial Autocorrelation**\n\n### **9.1 Computing local Moran’s I and mapping**\n\nWe will use hex_trips_sf which already has aggregated trips across 3 months\n\n1.  **Weekday morning peak（6am to 9am）**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(hex_trips_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,466\nColumns: 4\n$ HEX_ID      <chr> \"H0118\", \"H0118\", \"H0118\", \"H0146\", \"H0146\", \"H0146\", \"H01…\n$ TIME_PERIOD <chr> \"Weekday_Afternoon\", \"Weekday_Morning\", \"Weekend_Holiday\",…\n$ Total_Trips <dbl> 3391, 1272, 3318, 181, 105, 165, 841, 296, 437, 869, 347, …\n$ geometry    <POLYGON [m]> POLYGON ((3792.538 27656.57..., POLYGON ((3792.538…\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(unique(hex_trips_sf$TIME_PERIOD))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Weekday_Afternoon\" \"Weekday_Morning\"   \"Weekend_Holiday\"  \n[4] NA                 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(hex_trips_sf$Total_Trips)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n      0    7236   38851   83740  106914 1584199 \n```\n\n\n:::\n:::\n\n\n\n-   **Prepare the data and calculate the spatial weights**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_morning <- hex_trips_sf %>%\n  filter(TIME_PERIOD == \"Weekday_Morning\") %>%\n  filter(!is.na(TIME_PERIOD))\n\nwm_morning <- wm_morning %>%\n  mutate(\n    nb = st_contiguity(geometry),\n    wt = st_weights(nb, style = \"W\", allow_zero = TRUE),  # Allow zero neighbors!\n    .before = 1)\n```\n:::\n\n\n\n-   **Compute Local Moran's I**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb_lengths <- sapply(wm_morning$nb, length)\nwm_morning_clean <- wm_morning[nb_lengths > 0, ]\nnb_morning <- poly2nb(wm_morning_clean, queen = TRUE)\nwt_morning <- nb2listw(nb_morning, style = \"W\", zero.policy = TRUE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nmoran_morning <- localmoran_perm(\n  wm_morning_clean$Total_Trips,\n  wt_morning,\n  nsim = 99,\n  alternative = \"two.sided\",\n  zero.policy = TRUE)\n\nwm_morning_clean <- wm_morning_clean %>%\n  mutate(\n    ii = moran_morning[, \"Ii\"],\n    e_ii = moran_morning[, \"E.Ii\"],\n    var_ii = moran_morning[, \"Var.Ii\"],\n    z_ii = moran_morning[, \"Z.Ii\"],\n    p_ii_sim = moran_morning[, \"Pr(z != E(Ii))\"])\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsig_count <- sum(wm_morning_clean$p_ii_sim < 0.05, na.rm = TRUE)\ncat(\"\\nSignificant locations (p < 0.05):\", sig_count, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSignificant locations (p < 0.05): 101 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Percentage:\", sprintf(\"%.1f%%\\n\", sig_count / nrow(wm_morning_clean) * 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage: 12.4%\n```\n\n\n:::\n:::\n\n\n\n-   **Create LISA Classification for Local Moran's I**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_morning_clean <- wm_morning_clean %>%\n  mutate(\n    trips_lag = lag.listw(wt_morning, Total_Trips),\n    moran_category = case_when(\n      p_ii_sim >= 0.05 ~ \"Not significant\",\n      p_ii_sim < 0.05 & ii > 0 & Total_Trips >= mean(Total_Trips) & \n        trips_lag >= mean(trips_lag) ~ \"High-High\",\n      p_ii_sim < 0.05 & ii > 0 & Total_Trips < mean(Total_Trips) & \n        trips_lag < mean(trips_lag) ~ \"Low-Low\",\n      p_ii_sim < 0.05 & ii < 0 & Total_Trips >= mean(Total_Trips) & \n        trips_lag < mean(trips_lag) ~ \"High-Low\",\n      p_ii_sim < 0.05 & ii < 0 & Total_Trips < mean(Total_Trips) & \n        trips_lag >= mean(trips_lag) ~ \"Low-High\",\n      TRUE ~ \"Not significant\"))\n\ncat(\"\\nLISA Categories:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLISA Categories:\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(table(wm_morning_clean$moran_category))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      High-High        Low-High         Low-Low Not significant \n             82              18               1             715 \n```\n\n\n:::\n:::\n\n\n\n-   **Visualizing Local Moran's I - Weekday Morning**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\n# Map 1: Local Moran's I values - MORNING\nmoran_map_morning <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_morning_clean) +\n  tm_fill(\n    \"ii\",\n    style = \"jenks\",\n    n = 8,\n    palette = \"-RdBu\",\n    midpoint = 0,\n    title = \"Local Moran's I\") +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Local Moran's I of Total_trips- Weekday Morning Peak (6-9 AM)\", \n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 2: p-values - MORNING\npvalue_map_morning <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_morning_clean) +\n  tm_fill(\n    \"p_ii_sim\",\n    breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n    palette = \"-Reds\",\n    title = \"p-value\",\n    labels = c(\"< 0.001\", \"0.001-0.01\", \"0.01-0.05\", \"0.05-0.1\", \"> 0.1\")\n  ) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"p-values of Local Moran's I of Total_trips - Weekday Morning\",  \n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 3: LISA clusters - MORNING\nlisa_map_morning <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_morning_clean %>% filter(moran_category != \"Not significant\")) +\n  tm_fill(\n    \"moran_category\",\n    palette = c(\"High-High\" = \"#d7191c\",\n                \"Low-Low\" = \"#2c7bb6\",\n                \"Low-High\" = \"#fdae61\",\n                \"High-Low\" = \"#abd9e9\"),\n    title = \"LISA Category\") +\n  tm_borders(col = \"black\", lwd = 0.5) +\n  tm_layout(\n    main.title = \"Significant locations - Weekday Morning Peak\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Display maps\nmoran_map_morning\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n\n```{.r .cell-code}\npvalue_map_morning\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-37-2.png){width=672}\n:::\n\n```{.r .cell-code}\nlisa_map_morning\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-37-3.png){width=672}\n:::\n:::\n\n\n\nIn the weekday morning peak, significant **high–high clusters** are anchored in **outer residential towns** (north, north-east, east and west), not the city centre, clear evidence that the strongest origins are suburban feeders sending commuters inward.\n\n**Repeat those step for the other two time period:**\n\n2.  **Weekday afternoon peak(5pm to 8pm)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_afternoon <- hex_trips_sf %>%\n  filter(TIME_PERIOD == \"Weekday_Afternoon\") %>%\n  filter(!is.na(TIME_PERIOD))\n\nwm_afternoon <- wm_afternoon %>%\n  mutate(\n    nb = st_contiguity(geometry),\n    wt = st_weights(nb, style = \"W\", allow_zero = TRUE),\n    .before = 1)\n\nnb_lengths_aft <- sapply(wm_afternoon$nb, length)\nwm_afternoon_clean <- wm_afternoon[nb_lengths_aft > 0, ]\nnb_afternoon <- poly2nb(wm_afternoon_clean, queen = TRUE)\nwt_afternoon <- nb2listw(nb_afternoon, style = \"W\", zero.policy = TRUE)\n\nset.seed(1234)\nmoran_afternoon <- localmoran_perm(\n  wm_afternoon_clean$Total_Trips,\n  wt_afternoon,\n  nsim = 99,\n  alternative = \"two.sided\",\n  zero.policy = TRUE)\n\nwm_afternoon_clean <- wm_afternoon_clean %>%\n  mutate(\n    ii = moran_afternoon[, \"Ii\"],\n    e_ii = moran_afternoon[, \"E.Ii\"],\n    var_ii = moran_afternoon[, \"Var.Ii\"],\n    z_ii = moran_afternoon[, \"Z.Ii\"],\n    p_ii_sim = moran_afternoon[, \"Pr(z != E(Ii))\"])\n\nwm_afternoon_clean <- wm_afternoon_clean %>%\n  mutate(\n    trips_lag = lag.listw(wt_afternoon, Total_Trips),\n    moran_category = case_when(\n      p_ii_sim >= 0.05 ~ \"Not significant\",\n      p_ii_sim < 0.05 & ii > 0 & Total_Trips >= mean(Total_Trips) & \n        trips_lag >= mean(trips_lag) ~ \"High-High\",\n      p_ii_sim < 0.05 & ii > 0 & Total_Trips < mean(Total_Trips) & \n        trips_lag < mean(trips_lag) ~ \"Low-Low\",\n      p_ii_sim < 0.05 & ii < 0 & Total_Trips >= mean(Total_Trips) & \n        trips_lag < mean(trips_lag) ~ \"High-Low\",\n      p_ii_sim < 0.05 & ii < 0 & Total_Trips < mean(Total_Trips) & \n        trips_lag >= mean(trips_lag) ~ \"Low-High\",\n      TRUE ~ \"Not significant\"))\n\ntmap_mode(\"plot\")\nwm_afternoon_clean <- wm_afternoon_clean %>%\n  mutate(\n    z_trips = scale(Total_Trips)[,1],\n    z_trips_lag = scale(trips_lag)[,1])\n\n# Map 1: Local Moran's I values\nmoran_map_afternoon <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_afternoon_clean) +\n  tm_fill(\n    \"ii\",\n    style = \"jenks\",\n    n = 8,\n    palette = \"-RdBu\",\n    midpoint = 0,\n    title = \"Local Moran's I\") +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Local Moran's I of Total_trips - Weekday Afternoon Peak (5-8 PM)\", \n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 2: p-values\npvalue_map_afternoon <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_afternoon_clean) +\n  tm_fill(\n    \"p_ii_sim\",\n    breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n    palette = \"-Reds\",\n    title = \"p-value\",\n    labels = c(\"< 0.001\", \"0.001-0.01\", \"0.01-0.05\", \"0.05-0.1\", \"> 0.1\")) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"p-values of Local Moran's I of Total_trips- Weekday Afternoon\",  \n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 3: LISA clusters\nlisa_map_afternoon <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_afternoon_clean %>% filter(moran_category != \"Not significant\")) +\n  tm_fill(\n    \"moran_category\",\n    palette = c(\"High-High\" = \"#d7191c\",\n                \"Low-Low\" = \"#2c7bb6\",\n                \"Low-High\" = \"#fdae61\",\n                \"High-Low\" = \"#abd9e9\"),\n    title = \"LISA Category\") +\n  tm_borders(col = \"black\", lwd = 0.5) +\n  tm_layout(\n    main.title = \"Significant locations - Weekday Afternoon Peak\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\nmoran_map_afternoon\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n\n```{.r .cell-code}\npvalue_map_afternoon\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-38-2.png){width=672}\n:::\n\n```{.r .cell-code}\nlisa_map_afternoon\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-38-3.png){width=672}\n:::\n:::\n\n\n\nEvening trips concentrate into multiple small, well-defined cores, and the rings of low–high cells trace the edges where demand drops off sharply. These are natural places to check capacity, headways and interchange crowding in the evening peak, and to plan first for corridors where several high–high rosettes line up.\n\n3.  **Weekend/holiday(11am to 8pm)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_weekend <- hex_trips_sf %>%\n  filter(TIME_PERIOD == \"Weekend_Holiday\") %>%\n  filter(!is.na(TIME_PERIOD))\n\nwm_weekend <- wm_weekend %>%\n  mutate(\n    nb = st_contiguity(geometry),\n    wt = st_weights(nb, style = \"W\", allow_zero = TRUE),\n    .before = 1)\n\nnb_lengths_wkd <- sapply(wm_weekend$nb, length)\nwm_weekend_clean <- wm_weekend[nb_lengths_wkd > 0, ]\nnb_weekend <- poly2nb(wm_weekend_clean, queen = TRUE)\nwt_weekend <- nb2listw(nb_weekend, style = \"W\", zero.policy = TRUE)\n\nset.seed(1234)\nmoran_weekend <- localmoran_perm(\n  wm_weekend_clean$Total_Trips,\n  wt_weekend,\n  nsim = 99,\n  alternative = \"two.sided\",\n  zero.policy = TRUE)\n\nwm_weekend_clean <- wm_weekend_clean %>%\n  mutate(\n    ii = moran_weekend[, \"Ii\"],\n    e_ii = moran_weekend[, \"E.Ii\"],\n    var_ii = moran_weekend[, \"Var.Ii\"],\n    z_ii = moran_weekend[, \"Z.Ii\"],\n    p_ii_sim = moran_weekend[, \"Pr(z != E(Ii))\"])\n\nwm_weekend_clean <- wm_weekend_clean %>%\n  mutate(\n    trips_lag = lag.listw(wt_weekend, Total_Trips),\n    moran_category = case_when(\n      p_ii_sim >= 0.05 ~ \"Not significant\",\n      p_ii_sim < 0.05 & ii > 0 & Total_Trips >= mean(Total_Trips) & \n        trips_lag >= mean(trips_lag) ~ \"High-High\",\n      p_ii_sim < 0.05 & ii > 0 & Total_Trips < mean(Total_Trips) & \n        trips_lag < mean(trips_lag) ~ \"Low-Low\",\n      p_ii_sim < 0.05 & ii < 0 & Total_Trips >= mean(Total_Trips) & \n        trips_lag < mean(trips_lag) ~ \"High-Low\",\n      p_ii_sim < 0.05 & ii < 0 & Total_Trips < mean(Total_Trips) & \n        trips_lag >= mean(trips_lag) ~ \"Low-High\",\n      TRUE ~ \"Not significant\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\n# Map 1: Local Moran's I values\nmoran_map_weekend <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_weekend_clean) +\n  tm_fill(\n    \"ii\",\n    style = \"jenks\",\n    n = 8,\n    palette = \"-RdBu\",\n    midpoint = 0,\n    title = \"Local Moran's I\") +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Local Moran's I of Total_trips - Weekend/Holiday (11 AM-8 PM)\", \n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 2: p-values\npvalue_map_weekend <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_weekend_clean) +\n  tm_fill(\n    \"p_ii_sim\",\n    breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n    palette = \"-Reds\",\n    title = \"p-value\",\n    labels = c(\"< 0.001\", \"0.001-0.01\", \"0.01-0.05\", \"0.05-0.1\", \"> 0.1\")) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"p-values of Local Moran's I of Total_trips - Weekend/Holiday\",  \n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 3: LISA clusters\nlisa_map_weekend <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(wm_weekend_clean %>% filter(moran_category != \"Not significant\")) +\n  tm_fill(\n    \"moran_category\",\n    palette = c(\"High-High\" = \"#d7191c\",\n                \"Low-Low\" = \"#2c7bb6\",\n                \"Low-High\" = \"#fdae61\",\n                \"High-Low\" = \"#abd9e9\"),\n    title = \"LISA Category\") +\n  tm_borders(col = \"black\", lwd = 0.5) +\n  tm_layout(\n    main.title = \"Significant Locations - Weekend/Holiday\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\nmoran_map_weekend\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n\n```{.r .cell-code}\npvalue_map_weekend\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-40-2.png){width=672}\n:::\n\n```{.r .cell-code}\nlisa_map_weekend\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-40-3.png){width=672}\n:::\n:::\n\n\n\nOn weekends and holidays, significant **high–high clusters** break away from commuter corridors and appear as **scattered leisure/shopping hubs** across the island, with weaker corridor continuity—demand concentrates around destination areas rather than along travel-to-work routes.\n\n### **9. 2 Preparing and Visualising LISA Map**\n\nVisualizing LISA involves creating maps that highlight significant spatial patterns, such as hot spots (high values clustered together) and cold spots (low values clustered together), as well as identifying spatial outliers. Common methods include choropleth maps showing LISA values, Moran scatterplots which depict local spatial autocorrelation for individual locations, and hot spot analysis maps.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_morning_clean <- wm_morning_clean %>%\n  mutate(\n    z_trips = scale(Total_Trips)[,1],\n    z_trips_lag = scale(trips_lag)[,1])\n\nwm_afternoon_clean <- wm_afternoon_clean %>%\n  mutate(\n    z_trips = scale(Total_Trips)[,1],\n    z_trips_lag = scale(trips_lag)[,1])\n\nwm_weekend_clean <- wm_weekend_clean %>%\n  mutate(\n    z_trips = scale(Total_Trips)[,1],\n    z_trips_lag = scale(trips_lag)[,1])\n\n# Moran Scatterplot - Weekday Morning\nmoran_scatter_morning <- ggplot(wm_morning_clean, \n                                aes(x = z_trips, y = z_trips_lag)) +\n  geom_point(aes(color = moran_category), size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"black\", linewidth = 1) +\n  geom_hline(yintercept = mean(wm_morning_clean$z_trips_lag), \n             linetype = \"dashed\", lty = 2) +\n  geom_vline(xintercept = mean(wm_morning_clean$z_trips), \n             linetype = \"dashed\", lty = 2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\",\n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\",\n               \"High-Low\" = \"pink\",\n               \"Not significant\" = \"grey80\"),\n    name = \"LISA Quadrants\") +\n  labs(\n    title = \"Moran Scatterplot with LISA Quadrants - Weekday Morning\",\n    x = \"Standardised Bus Trips\",\n    y = \"Standardised Spatial Lag of Bus Trips\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 12, face = \"bold\"),\n    legend.position = \"right\")\n\n# Moran Scatterplot - Weekday Afternoon\nmoran_scatter_afternoon <- ggplot(wm_afternoon_clean, \n                                  aes(x = z_trips, y = z_trips_lag)) +\n  geom_point(aes(color = moran_category), size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"black\", linewidth = 1) +\n  geom_hline(yintercept = mean(wm_afternoon_clean$z_trips_lag), \n             linetype = \"dashed\", lty = 2) +\n  geom_vline(xintercept = mean(wm_afternoon_clean$z_trips), \n             linetype = \"dashed\", lty = 2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\",\n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\",\n               \"High-Low\" = \"pink\",\n               \"Not significant\" = \"grey80\"),\n    name = \"LISA Quadrants\") +\n  labs(\n    title = \"Moran Scatterplot with LISA Quadrants - Weekday Afternoon\",\n    x = \"Standardised Bus Trips\",\n    y = \"Standardised Spatial Lag of Bus Trips\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 12, face = \"bold\"),\n    legend.position = \"right\")\n\n# Moran Scatterplot - Weekend/Holiday\nmoran_scatter_weekend <- ggplot(wm_weekend_clean, \n                                aes(x = z_trips, y = z_trips_lag)) +\n  geom_point(aes(color = moran_category), size = 2) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"black\", linewidth = 1) +\n  geom_hline(yintercept = mean(wm_weekend_clean$z_trips_lag), \n             linetype = \"dashed\", lty = 2) +\n  geom_vline(xintercept = mean(wm_weekend_clean$z_trips), \n             linetype = \"dashed\", lty = 2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\",\n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\",\n               \"High-Low\" = \"pink\",\n               \"Not significant\" = \"grey80\"),\n    name = \"LISA Quadrants\") +\n  labs(\n    title = \"Moran Scatterplot with LISA Quadrants - Weekend/Holiday\",\n    x = \"Standardised Bus Trips\",\n    y = \"Standardised Spatial Lag of Bus Trips\") +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5, size = 12, face = \"bold\"),\n    legend.position = \"right\")\n\nmoran_scatter_morning\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmoran_scatter_afternoon\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-41-2.png){width=672}\n:::\n\n```{.r .cell-code}\nmoran_scatter_weekend\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-41-3.png){width=672}\n:::\n:::\n\n\n\n-   **Weekday Morning**\n\nWeekday morning exhibits the strongest spatial autocorrelation, with the most extensive and dense High-High clusters (red), indicating that bus demand is highly concentrated in specific areas during peak commute hours. These areas likely represent major employment centers and transit hubs. Low-High clusters (light blue) are scattered in lower-value regions, representing low-usage locations adjacent to high-demand areas, possibly residential peripheries. One Low-Low point (dark blue) appears, revealing an isolated low-demand area. The overall pattern reflects clear job-housing separation and commute-oriented travel characteristics, with the tightest alignment to the global Moran's I trend line.\n\n-   **Weekday Afternoon**\n\nWeekday afternoon shows a more dispersed spatial clustering pattern compared to morning, with High-High clusters still significant but spread across a wider range of standardized values. This suggests more diverse trip destinations in the afternoon, including not only workplaces but also shopping, leisure, and other activities. Low-High clusters are relatively reduced, indicating lower spatial heterogeneity. The overall scatter distribution is looser than morning, suggesting that off-peak period bus demand is more spatially uniform, though connections between high-demand areas remain strong. This pattern reflects the multi-purpose nature of afternoon travel beyond commuting.\n\n-   **Weekend/Holiday**\n\nWeekend and holiday periods display the weakest spatial autocorrelation, with High-High clusters being most compact and concentrated in lower value ranges. This reflects fundamental differences between recreational and commute travel patterns: without concentrated commuting demand, overall ridership decreases and spatial distribution becomes more uniform. Low-High clusters are fewer, indicating less contrast between high and low demand areas compared to weekdays. The overall pattern shows that weekend bus services face more dispersed demand, potentially requiring different service strategies and route planning to accommodate recreational travel characteristics rather than structured commuting flows.\n\n## **10. Hot Spots and Cold Spots Analysis (HCSA)**\n\nHot spots and cold spots analysis is a technique used in spatial statistics to identify statistically significant clusters of high values (hot spots) and low values (cold spots) of a geographically referenced attribute. These analyses help visualize and understand spatial patterns, revealing areas where data points are clustered more densely than would be expected by random chance.\n\n### 10.1 Compute Local Gi\\* (Hot Spot and Cold Spot Analysis)\n\nLocal Gi\\* (pronounced “G-i-star”) is a Getis-Ord statistic used in spatial analysis to identify statistically significant hot spots and cold spots of high or low attribute values within a dataset. It measures the spatial clustering of values by comparing the total value within a specified neighborhood to the global total, producing a Z-score and p-value for each location to determine the likelihood that the observed pattern is not due to random chance.\n\n1.  **Weekday Morning:**\n\n-   **Preparing and Visualising HCSA Map**\n\nStarted by selecting the relevant data (`HEX_ID`, `Total_Trips`, `geometry`) from the `wm_morning` dataset to create `gi_morning`. This formed the foundation for your spatial autocorrelation analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngi_morning <- wm_morning %>%\n  select(HEX_ID, Total_Trips, geometry) %>%  \n  mutate(\n    nb = include_self(st_contiguity(geometry)), \n    wt = st_weights(nb, style = \"W\", allow_zero = TRUE),\n    .before = 1)\n\nnb_lengths_gi <- sapply(gi_morning$nb, length)\ncat(\"Hexagons with zero neighbors:\", sum(nb_lengths_gi == 0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHexagons with zero neighbors: 0 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Total hexagons for Gi*:\", nrow(gi_morning), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal hexagons for Gi*: 816 \n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(1234)\ngi_morning <- gi_morning %>%\n  mutate(\n    gi_star = local_gstar_perm(\n      Total_Trips, \n      nb, \n      wt, \n      nsim = 99),\n    .before = 1) %>%\n  unnest(gi_star)\n\ngi_morning <- gi_morning %>%\n  mutate(\n    gi_category = case_when(\n      p_sim < 0.05 & gi_star > 0 ~ \"Hot spot\",\n      p_sim < 0.05 & gi_star < 0 ~ \"Cold spot\",\n      TRUE ~ \"Not significant\"))\n\ncat(\"Percentage significant:\",sprintf(\"%.1f%%\\n\", sum(gi_morning$p_sim < 0.05) / nrow(gi_morning) * 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage significant: 18.6%\n```\n\n\n:::\n:::\n\n\n\n-   **Computing Local Gi Statistics\\***\n\nPerformed a Local Getis-Ord Gi\\* analysis using local_gstar_perm() with:\n\n-   Total_Trips as the variable of interest\n\n-   999 permutations (nsim = 999) for statistical significance testing\n\n-   Row-standardized weights from your spatial weights matrix\n\nThis identified hot spots (high values surrounded by high values) and cold spots (low values surrounded by low values).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\n# Map 1: Gi* values\ngistar_map_morning <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_morning) +\n  tm_fill(\n    \"gi_star\",\n    style = \"pretty\",\n    n = 8,\n    palette = \"-RdBu\",\n    midpoint = 0,\n    title = \"Gi* Statistic\") +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Local Gi* Values - Weekday Morning Peak\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 2: p-values\npvalue_gistar_map_morning <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_morning) +\n  tm_fill(\n    \"p_sim\",\n    breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n    palette = \"-Reds\",\n    title = \"p-value\",\n    labels = c(\"< 0.001\", \"0.001-0.01\", \"0.01-0.05\", \"0.05-0.1\", \"> 0.1\")) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"p-values of Local Gi* - Weekday Morning\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 3: Hot spots and Cold spots (significant only)\nhotspot_map_morning <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_morning %>% filter(gi_category != \"Not significant\")) +\n  tm_fill(\n    \"gi_category\",\n    palette = c(\"Hot spot\" = \"#d7191c\",\n                \"Cold spot\" = \"#2c7bb6\"),\n    title = \"Gi* Category\"\n  ) +\n  tm_borders(col = \"black\", lwd = 0.5) +\n  tm_layout(\n    main.title = \"Hot Spots and Cold Spots - Weekday Morning Peak\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n\ngistar_map_morning\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n\n```{.r .cell-code}\npvalue_gistar_map_morning\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-43-2.png){width=672}\n:::\n\n```{.r .cell-code}\nhotspot_map_morning\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-43-3.png){width=672}\n:::\n:::\n\n\n\n**Map 1: Local Gi\\* Values**\n\nThis map displays the intensity of spatial clustering using a diverging color scheme. *Dark red/maroon hexagons (Gi 5.0-6.0)*\\* represent the strongest hot spots with extremely high bus ridership surrounded by similarly high-ridership areas. These appear concentrated in several distinct clusters across Singapore, particularly in the **central and western regions**. The **blue hexagons** indicate cold spots where low ridership areas are surrounded by other low-ridership locations, primarily along the **western and northern peripheries**. The gradient reveals not just binary hot/cold spots but the **varying intensity** of spatial autocorrelation.\n\n**Map 2: P-values of Local Gi\\***\n\nThis map shows the statistical significance of the clustering patterns. **Dark red areas (p \\< 0.001)** indicate the most statistically robust hot spots where we can be highly confident the clustering is not due to random chance. Notable is the **extensive coverage** of statistically significant areas (p \\< 0.05), particularly in the **western region** which shows a large, continuous cluster of highly significant results. The **central and eastern portions** also display scattered but significant hot spots. This suggests that morning peak bus ridership exhibits strong, statistically valid spatial clustering patterns across much of Singapore.\n\n**Map 3: Hot Spots and Cold Spots**\n\nThis categorical map clearly delineates the final classification. **Red hexagons (hot spots)** are scattered throughout but form notable clusters in the **central business district area, western residential zones, and northeastern regions**. **Blue hexagons (cold spots)** dominate the **far western coast** forming a large, continuous cluster, likely representing areas with limited bus services or lower population density. Interestingly, cold spots also appear in the **north** and are scattered elsewhere. The spatial distribution reveals that morning commute patterns create distinct zones of high and low bus usage, with hot spots likely corresponding to major employment centers and residential transit hubs, while cold spots may represent industrial areas, parks, or regions with alternative transport preferences.\n\n2.  **Weekday Afternoon:**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngi_afternoon <- wm_afternoon %>%\n  select(HEX_ID, Total_Trips, geometry) %>%  \n  mutate(\n    nb = include_self(st_contiguity(geometry)), \n    wt = st_weights(nb, style = \"W\", allow_zero = TRUE),\n    .before = 1)\n\nset.seed(1234)\ngi_afternoon <- gi_afternoon %>%\n  mutate(\n    gi_star = local_gstar_perm(Total_Trips, nb, wt, nsim = 99),\n    .before = 1) %>%\n  unnest(gi_star)\n\ngi_afternoon <- gi_afternoon %>%\n  mutate(\n    gi_category = case_when(\n      p_sim < 0.05 & gi_star > 0 ~ \"Hot spot\",\n      p_sim < 0.05 & gi_star < 0 ~ \"Cold spot\",\n      TRUE ~ \"Not significant\"))\n\ncat(\"Afternoon - Percentage significant:\", \n    sprintf(\"%.1f%%\\n\", sum(gi_afternoon$p_sim < 0.05) / nrow(gi_afternoon) * 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAfternoon - Percentage significant: 13.1%\n```\n\n\n:::\n:::\n\n\n\nThe analysis revealed that **only 13.1% of hexagons** show statistically significant clustering in the afternoon, which is notably lower than typical morning peak patterns.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\n# Map 1: Gi* values\ngistar_map_afternoon <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_afternoon) +\n  tm_fill(\n    \"gi_star\",\n    style = \"pretty\",\n    n = 8,\n    palette = \"-RdBu\",\n    midpoint = 0,\n    title = \"Gi* Statistic\") +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Local Gi* Values - Weekday Afternoon Peak\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 2: p-values\npvalue_gistar_map_afternoon <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_afternoon) +\n  tm_fill(\n    \"p_sim\",\n    breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n    palette = \"-Reds\",\n    title = \"p-value\",\n    labels = c(\"< 0.001\", \"0.001-0.01\", \"0.01-0.05\", \"0.05-0.1\", \"> 0.1\")) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"p-values of Local Gi* - Weekday Afternoon\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 3: Hot spots and Cold spots\nhotspot_map_afternoon <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_afternoon %>% filter(gi_category != \"Not significant\")) +\n  tm_fill(\n    \"gi_category\",\n    palette = c(\"Hot spot\" = \"#d7191c\",\n                \"Cold spot\" = \"#2c7bb6\"),\n    title = \"Gi* Category\") +\n  tm_borders(col = \"black\", lwd = 0.5) +\n  tm_layout(\n    main.title = \"Hot Spots and Cold Spots - Weekday Afternoon Peak\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n\ngistar_map_afternoon\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-45-1.png){width=672}\n:::\n\n```{.r .cell-code}\npvalue_gistar_map_afternoon\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-45-2.png){width=672}\n:::\n\n```{.r .cell-code}\nhotspot_map_afternoon\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-45-3.png){width=672}\n:::\n:::\n\n\n\n**Map 1: Local Gi\\* Values - Weekday Afternoon Peak**\n\nThis map displays the intensity of spatial clustering using a diverging color scheme. *Dark red/maroon hexagons (Gi* 5.0-6.0)\\* represent the strongest hot spots with extremely high bus ridership surrounded by similarly high-ridership areas. These appear concentrated in several distinct clusters across Singapore, particularly in the **central and western regions**. The **blue hexagons** indicate cold spots where low ridership areas are surrounded by other low-ridership locations, primarily along the **western and northern peripheries**. The gradient reveals not just binary hot/cold spots but the **varying intensity** of spatial autocorrelation.\n\n**Map 2: P-values of Local Gi\\* - Weekday Afternoon**\n\nStatistical significance is **considerably weaker** in the afternoon. While the **western coastal region** still shows strong significance (p \\< 0.001), most other areas display only moderate significance (0.01-0.05 range) or are non-significant. The **central and eastern regions** have scattered significant clusters but lack the extensive, continuous significant areas seen in morning. This lower overall significance (13.1%) confirms that afternoon bus ridership exhibits **weaker spatial clustering** than morning commute patterns, reflecting more dispersed, multi-purpose travel rather than concentrated work commutes.\n\n**Map 3: Hot Spots and Cold Spots - Weekday Afternoon Peak**\n\nThe categorical map reveals a stark shift from morning patterns. **Cold spots (blue)** dramatically outnumber hot spots, with the **western coastal area** forming the largest continuous cold spot cluster. Hot spots (red) are **sparse and scattered**, appearing as small isolated clusters in the **north, northeast, and eastern regions**, plus a few in central areas. This distribution suggests that afternoon travel is more **spatially fragmented**, with fewer concentrated activity nodes. The predominance of cold spots indicates that many areas experience relatively low afternoon ridership compared to their neighbors, possibly due to people already being at their destinations or using alternative transport modes for non-commute trips.\n\n3.  Weekend/Holiday:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngi_weekend <- wm_weekend %>%\n  select(HEX_ID, Total_Trips, geometry) %>%  \n  mutate(\n    nb = include_self(st_contiguity(geometry)), \n    wt = st_weights(nb, style = \"W\", allow_zero = TRUE),\n    .before = 1)\n\nset.seed(1234)\ngi_weekend <- gi_weekend %>%\n  mutate(\n    gi_star = local_gstar_perm(Total_Trips, nb, wt, nsim = 99),\n    .before = 1) %>%\n  unnest(gi_star)\n\ngi_weekend <- gi_weekend %>%\n  mutate(\n    gi_category = case_when(\n      p_sim < 0.05 & gi_star > 0 ~ \"Hot spot\",\n      p_sim < 0.05 & gi_star < 0 ~ \"Cold spot\",\n      TRUE ~ \"Not significant\"))\n\ncat(\"Weekend - Percentage significant:\", \n    sprintf(\"%.1f%%\\n\", sum(gi_weekend$p_sim < 0.05) / nrow(gi_weekend) * 100))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWeekend - Percentage significant: 16.1%\n```\n\n\n:::\n:::\n\n\n\nUsing the same Local Gi\\* methodology with 999 permutations and p \\< 0.05 significance threshold, the weekend/holiday analysis reveals that **16.1% of hexagons** show statistically significant clustering—slightly higher than weekday afternoon (13.1%) but substantially lower than weekday morning, indicating moderate spatial structure in recreational travel patterns.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode(\"plot\")\n\n# Map 1: Gi* values\ngistar_map_weekend <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_weekend) +\n  tm_fill(\n    \"gi_star\",\n    style = \"pretty\",\n    n = 8,\n    palette = \"-RdBu\",\n    midpoint = 0,\n    title = \"Gi* Statistic\") +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Local Gi* Values - Weekend/Holiday\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 2: p-values\npvalue_gistar_map_weekend <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_weekend) +\n  tm_fill(\n    \"p_sim\",\n    breaks = c(0, 0.001, 0.01, 0.05, 0.1, 1),\n    palette = \"-Reds\",\n    title = \"p-value\",\n    labels = c(\"< 0.001\", \"0.001-0.01\", \"0.01-0.05\", \"0.05-0.1\", \"> 0.1\")\n  ) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"p-values of Local Gi* - Weekend/Holiday\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\"\n  ) +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Map 3: Hot spots and Cold spots\nhotspot_map_weekend <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(gi_weekend %>% filter(gi_category != \"Not significant\")) +\n  tm_fill(\n    \"gi_category\",\n    palette = c(\"Hot spot\" = \"#d7191c\",\n                \"Cold spot\" = \"#2c7bb6\"),\n    title = \"Gi* Category\"\n  ) +\n  tm_borders(col = \"black\", lwd = 0.5) +\n  tm_layout(\n    main.title = \"Hot Spots and Cold Spots - Weekend/Holiday\",\n    main.title.size = 0.9,\n    legend.outside = TRUE,\n    frame = TRUE,\n    bg.color = \"grey98\"\n  ) +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scale_bar(position = c(\"right\", \"bottom\"))\n\n# Display maps\ngistar_map_weekend\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n\n```{.r .cell-code}\npvalue_gistar_map_weekend\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-47-2.png){width=672}\n:::\n\n```{.r .cell-code}\nhotspot_map_weekend\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-47-3.png){width=672}\n:::\n:::\n\n\n\n**Map 1: Local Gi\\* Values - Weekend/Holiday**\n\nWeekend patterns show **distinctive clustering characteristics** that differ from weekday patterns. Dark red hot spots (Gi\\* 4.0-6.0) are concentrated in **central areas, a prominent southern cluster, and scattered locations in the east and northeast**, likely representing shopping districts, recreational areas, and tourist attractions. The **large southern hot spot** is particularly notable, suggesting a major leisure destination. Blue cold spots extensively cover the **western coastal region and appear more distributed in northern areas**, indicating lower weekend bus usage. The overall pattern shows **more balanced mixing** of hot and cold areas compared to the stark commute-driven patterns of weekday morning.\n\n**Map 2: P-values of Local Gi\\* - Weekend/Holiday**\n\nStatistical significance displays a **different spatial distribution** than weekdays. The **western coastal region** maintains very high significance (p \\< 0.001), confirming it as a consistently low-ridership area across all time periods. However, weekend patterns show **more scattered but robust significant clusters** (p \\< 0.05) throughout central, eastern, and northeastern regions, with moderate significance (0.01-0.05) spread across many areas. The 16.1% significance rate—higher than afternoon but lower than morning—suggests that weekend travel, while less concentrated than commuting, still exhibits **clear spatial structure** around recreational and retail destinations, creating identifiable but more dispersed activity nodes.\n\n**Map 3: Hot Spots and Cold Spots - Weekend/Holiday**\n\nThe categorical map reveals a **fundamentally different spatial logic** from weekday patterns. Cold spots (blue) dominate the **western region** forming the largest continuous cluster, similar to other periods, but also appear **scattered throughout the north and northeastern areas**. Hot spots (red) are **more evenly distributed** across the island, appearing as small clusters in the **north, central, east-central, eastern, and notably in a concentrated southern cluster**. This distribution reflects **recreational travel patterns** oriented toward shopping malls, parks, cultural attractions, and dining areas rather than employment centers. The presence of an **eastern coastal hot spot cluster** suggests weekend beach or waterfront activities. Overall, the pattern shows that weekend bus demand is **spatially structured but multi-nodal**, serving diverse leisure destinations rather than following the radial commute patterns of weekdays.\n\n## 11. Emerging Hot Spot Analysis (EHSA)\n\nEmerging Hot Spots Analysis (EHSA) is a spatio-temporal statistical technique that identifies and categorizes areas where clusters of high or low values of a phenomenon are developing, intensifying, or diminishing over time. It combines the Getis-Ord Gi\\* statistic, which measures spatial clustering, with the Mann-Kendall trend test, a non-parametric trend analysis, to detect trends in these clusters within a “space-time cube” of data. This process allows for the detection of patterns such as new hot spots, persistent trends, or diminishing cold spots across different confidence levels\n\n![](images/clipboard-1479093949.png)\n\n![](images/clipboard-786588997.png)\n\n![](images/clipboard-448655566.png)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon_with_stops <- hexagon_with_stops %>%\n  mutate(HEX_ID = as.character(HEX_ID))\ntrips_morning_st_data <- trips_hex_agg %>%\n  filter(TIME_PERIOD == \"Weekday_Morning\") %>%\n  mutate(\n    HEX_ID = as.character(HEX_ID),  \n    time_index = case_when(\n      YEAR_MONTH == \"2025-07\" ~ 1,\n      YEAR_MONTH == \"2025-08\" ~ 2,\n      YEAR_MONTH == \"2025-09\" ~ 3)) %>%\n  select(HEX_ID, time_index, TOTAL_TRIPS) %>%\n  rename(\n    location = HEX_ID,\n    time = time_index,\n    value = TOTAL_TRIPS)\n\nall_combinations_morning <- expand.grid(\n  location = as.character(hexagon_with_stops$HEX_ID),\n  time = 1:3,\n  stringsAsFactors = FALSE)\n\ntrips_morning_complete <- all_combinations_morning %>%\n  left_join(trips_morning_st_data, by = c(\"location\", \"time\")) %>%\n  mutate(\n    value = replace_na(value, 0),\n    location = as.character(location))\n\nhexagon_for_st <- hexagon_with_stops %>%\n  mutate(location = as.character(HEX_ID)) %>%\n  select(location, geometry)\n\ncat(\"Geometry for spacetime has location column:\", \"location\" %in% names(hexagon_for_st), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry for spacetime has location column: TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\ntrips_morning_st <- spacetime(\n  .data = trips_morning_complete,\n  .geometry = hexagon_for_st,\n  .loc_col = \"location\",\n  .time_col = \"time\")\n\ncat(\"Is spacetime cube:\", is_spacetime_cube(trips_morning_st), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIs spacetime cube: TRUE \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Time periods:\", unique(trips_morning_complete$time), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTime periods: 1 2 3 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Locations:\", n_distinct(trips_morning_complete$location), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLocations: 834 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nehsa_morning <- emerging_hotspot_analysis(\n  x = trips_morning_st,\n  .var = \"value\",\n  k = 1,          \n  nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\n```\n\n\n:::\n\n```{.r .cell-code}\nehsa_morning_sig <- ehsa_morning %>%\n  filter(p_value < 0.05)\n\nhead(ehsa_morning, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   location tau p_value       classification\n1     H0118  -1       1    sporadic coldspot\n2     H0146  -1       1  persistent coldspot\n3     H0174  -1       1  persistent coldspot\n4     H0175  -1       1 consecutive coldspot\n5     H0200  -1       1 consecutive coldspot\n6     H0201  -1       1  persistent coldspot\n7     H0202  -1       1  persistent coldspot\n8     H0203  -1       1  persistent coldspot\n9     H0227  -1       1  persistent coldspot\n10    H0228  -1       1  persistent coldspot\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_morning_patterns <- ehsa_morning %>%\n  filter(classification != \"no pattern detected\")\nhex_ehsa_morning <- hexagon_for_st %>%\n  left_join(ehsa_morning_patterns, by = \"location\")\nhex_ehsa_morning <- hex_ehsa_morning %>%\n  filter(!is.na(classification))\n\ntmap_mode(\"plot\")\n\nehsa_map_morning <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(hex_ehsa_morning) +\n  tm_polygons(\n    fill = \"classification\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"consecutive coldspot\" = \"#2c7bb6\",\n        \"consecutive hotspot\" = \"#d7191c\",\n        \"persistent coldspot\" = \"#abd9e9\",\n        \"persistent hotspot\" = \"#fdae61\",\n        \"new coldspot\" = \"#4575b4\",\n        \"new hotspot\" = \"#d73027\",\n        \"sporadic coldspot\" = \"#74add1\",\n        \"sporadic hotspot\" = \"#f46d43\")),\n    fill.legend = tm_legend(title = \"EHSA Pattern\")) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Emerging Hot Spot Analysis - Weekday Morning Peak\\n(July-September 2025, all detected patterns)\",\n    main.title.size = 0.8,\n    legend.outside = TRUE,\n    legend.outside.position = \"right\",\n    frame = TRUE,\n    bg.color = \"grey98\") +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scalebar(position = c(\"right\", \"bottom\"))\n\nehsa_map_morning\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n\n**EHSA insight (weekday morning):** Morning demand is **stable rather than emerging**—long **consecutive/persistent coldspot** corridors dominate the west and south-west, while **hotspots** appear as **consecutive/persistent** clusters in the north-east/east and a few central pockets. **New hotspots are sparse**, so the strongest origins are established residential feeders, not newly forming areas.\n\n-   **Weekday Afternoon**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_afternoon_st_data <- trips_hex_agg %>%\n  filter(TIME_PERIOD == \"Weekday_Afternoon\") %>%\n  mutate(\n    HEX_ID = as.character(HEX_ID),\n    time_index = case_when(\n      YEAR_MONTH == \"2025-07\" ~ 1,\n      YEAR_MONTH == \"2025-08\" ~ 2,\n      YEAR_MONTH == \"2025-09\" ~ 3\n    )\n  ) %>%\n  select(HEX_ID, time_index, TOTAL_TRIPS) %>%\n  rename(location = HEX_ID, time = time_index, value = TOTAL_TRIPS)\n\nall_combinations_afternoon <- expand.grid(\n  location = as.character(hexagon_with_stops$HEX_ID),\n  time = 1:3,\n  stringsAsFactors = FALSE\n)\n\ntrips_afternoon_complete <- all_combinations_afternoon %>%\n  left_join(trips_afternoon_st_data, by = c(\"location\", \"time\")) %>%\n  mutate(value = replace_na(value, 0), location = as.character(location))\n\ntrips_afternoon_st <- spacetime(\n  .data = trips_afternoon_complete,\n  .geometry = hexagon_for_st,\n  .loc_col = \"location\",\n  .time_col = \"time\"\n)\n\nset.seed(1234)\nehsa_afternoon <- emerging_hotspot_analysis(\n  x = trips_afternoon_st,\n  .var = \"value\",\n  k = 1,\n  nsim = 99\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\nWARNING: Error exit, tauk2. IFAULT =  12\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_afternoon_patterns <- ehsa_afternoon %>%\n  filter(classification != \"no pattern detected\")\n\nhex_ehsa_afternoon <- hexagon_for_st %>%\n  left_join(ehsa_afternoon_patterns, by = \"location\") %>%\n  filter(!is.na(classification))\n\ntmap_mode(\"plot\")\n\nehsa_map_afternoon <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(hex_ehsa_afternoon) +\n  tm_polygons(\n    fill = \"classification\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"consecutive coldspot\" = \"#2c7bb6\",\n        \"consecutive hotspot\" = \"#d7191c\",\n        \"persistent coldspot\" = \"#abd9e9\",\n        \"persistent hotspot\" = \"#fdae61\",\n        \"new coldspot\" = \"#4575b4\",\n        \"new hotspot\" = \"#d73027\",\n        \"sporadic coldspot\" = \"#74add1\",\n        \"sporadic hotspot\" = \"#f46d43\"\n      )\n    ),\n    fill.legend = tm_legend(title = \"EHSA Pattern\")\n  ) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Emerging Hot Spot Analysis - Weekday Afternoon Peak\\n(July-September 2025, all detected patterns)\",\n    main.title.size = 0.8,\n    legend.outside = TRUE,\n    legend.outside.position = \"right\",\n    frame = TRUE,\n    bg.color = \"grey98\"\n  ) +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scalebar(position = c(\"right\", \"bottom\"))\n\nehsa_map_afternoon\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n\n**EHSA insight (weekday afternoon):** After-work demand is **expanding**, not just stable—there are **new and consecutive hotspots** popping up along the central spine and north-/north-east clusters, while a **broad consecutive/persistent coldspot corridor** holds along the west–south-west coast. Translation: evening origins spread to more hexagons, but the west coastal belt remains consistently weak.\n\n-   **Weekend/Holiday**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_weekend_st_data <- trips_hex_agg %>%\n  filter(TIME_PERIOD == \"Weekend_Holiday\") %>%\n  mutate(\n    HEX_ID = as.character(HEX_ID),\n    time_index = case_when(\n      YEAR_MONTH == \"2025-07\" ~ 1,\n      YEAR_MONTH == \"2025-08\" ~ 2,\n      YEAR_MONTH == \"2025-09\" ~ 3\n    )\n  ) %>%\n  select(HEX_ID, time_index, TOTAL_TRIPS) %>%\n  rename(location = HEX_ID, time = time_index, value = TOTAL_TRIPS)\n\nall_combinations_weekend <- expand.grid(\n  location = as.character(hexagon_with_stops$HEX_ID),\n  time = 1:3,\n  stringsAsFactors = FALSE\n)\n\ntrips_weekend_complete <- all_combinations_weekend %>%\n  left_join(trips_weekend_st_data, by = c(\"location\", \"time\")) %>%\n  mutate(value = replace_na(value, 0), location = as.character(location))\n\ntrips_weekend_st <- spacetime(\n  .data = trips_weekend_complete,\n  .geometry = hexagon_for_st,\n  .loc_col = \"location\",\n  .time_col = \"time\"\n)\n\nset.seed(1234)\nehsa_weekend <- emerging_hotspot_analysis(\n  x = trips_weekend_st,\n  .var = \"value\",\n  k = 1,\n  nsim = 99\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_weekend_patterns <- ehsa_weekend %>%\n  filter(classification != \"no pattern detected\")\n\nhex_ehsa_weekend <- hexagon_for_st %>%\n  left_join(ehsa_weekend_patterns, by = \"location\") %>%\n  filter(!is.na(classification))\n\ntmap_mode(\"plot\")\n\nehsa_map_weekend <- tm_shape(land_sg) +\n  tm_polygons(fill = \"white\", col = \"grey60\", lwd = 0.8) +\ntm_shape(hex_ehsa_weekend) +\n  tm_polygons(\n    fill = \"classification\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"consecutive coldspot\" = \"#2c7bb6\",\n        \"consecutive hotspot\" = \"#d7191c\",\n        \"persistent coldspot\" = \"#abd9e9\",\n        \"persistent hotspot\" = \"#fdae61\",\n        \"new coldspot\" = \"#4575b4\",\n        \"new hotspot\" = \"#d73027\",\n        \"sporadic coldspot\" = \"#74add1\",\n        \"sporadic hotspot\" = \"#f46d43\"\n      )\n    ),\n    fill.legend = tm_legend(title = \"EHSA Pattern\")\n  ) +\n  tm_borders(col = \"grey30\", lwd = 0.3) +\n  tm_layout(\n    main.title = \"Emerging Hot Spot Analysis - Weekend/Holiday\\n(July-September 2025, all detected patterns)\",\n    main.title.size = 0.8,\n    legend.outside = TRUE,\n    legend.outside.position = \"right\",\n    frame = TRUE,\n    bg.color = \"grey98\"\n  ) +\n  tm_compass(type = \"8star\", size = 2, position = c(\"right\", \"bottom\")) +\n  tm_scalebar(position = c(\"right\", \"bottom\"))\n\nehsa_map_weekend\n```\n\n::: {.cell-output-display}\n![](Take-Home_Exercise02_files/figure-html/unnamed-chunk-54-1.png){width=672}\n:::\n:::\n\n\n\n**EHSA insight (weekend/holiday):** Origins shift from commuter corridors to **destination hubs**—many **consecutive/new hotspots** appear across central, east and southern clusters—while a **persistent coldspot belt** holds along the west–south-west coast. Translation: weekend demand concentrates around leisure/shopping areas; industrial/coastal belts remain consistently weak.\n\n## 12. Conclusion\n\nOver a period of three months and across various time windows, bus demand is highly concentrated and consistent during the weekday morning commute, driven by well-established suburban routes into the city. Evenings are stronger and more dispersed, with several new or continuing hotspots along the central spine and in the north and north-east, which is evidence of spreading after-work activity. On weekends and public holidays, demand shifts towards destination hubs (retail, leisure and waterfronts) rather than commuter corridors. A persistent low-demand belt appears along the west–southwest coast in every period.\n\nBus demand is clustered and consistent on weekday mornings (stable suburb-to-city corridors), heavier and more dispersed on weekday evenings (new and continuing hotspots along the central spine and in the north and northeast), and destination-led at weekends and on public holidays (retail, leisure and waterfront hubs). A persistent low-demand belt appears along the west–southwest coast in all periods.\n\nRather than relying on global averages, we have shown where neighbourhoods differ (durable high–high cores, sharp edges and weak zones), and we have detected emerging patterns (evening expansion and weekend hubs) that indicate where demand is growing or shifting.\n\nPrioritise evening reliability on aligned high–high corridors (tighter headways, short turns and larger buses), add flexible extras to new/continuous evening hotspots and retime resources for weekend hubs during events and leisure periods. In the persistent cold belt, favour lighter or demand-responsive supply over blanket increases.\n",
    "supporting": [
      "Take-Home_Exercise02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}