---
title: "In-class_Ex05"
---

## 5.1 Getting Started

Installing and loading the R Packages

```{r}
pacman::p_load(sf, sfdep, tmap, tidyverse)
```

## 5.2 **Import csv file into r environment**

```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan") %>% 
  st_transform(crs = 32650)
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

### 5.2.1 Combining both data frame by using left join

```{r}
hunan <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)
```

## 5.3 Global Measures of Spatial Association

Step 1: Deriving Queen's contiguity weights: sfdep methods

```{r}
wm_q <- hunan %>%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(
           nb, style = "W"),
         .before = 1) 
```

## 5.4 Performing Global Moran' I permutation teat

```{r}
set.seed(1234)
```

```{r}
global_moran_perm(wm_q$GDPPC,
             wm_q$nb,
             wm_q$wt,
             nsim = 99)
```

```{r}
lisa <- wm_q %>% 
  mutate(local_moran = local_moran(
    GDPPC, nb, wt, nsim = 99),
         .before = 1) %>%
  unnest(local_moran)
```
